### ISSUE TITLE
CMake Python bindings fails when building on different disk

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#1066]
I build acts on a fast disk, using `cmake -B . -S src` where `src` is a symlink to a different (slower) disk. When I enabled `-DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=on`, CMake failed with messages:

```
CMake Error at Examples/Python/CMakeLists.txt:147 (file):
  file failed to create link
  '/home/ppd/adye/acts/build/python/acts/__init__.py': cross-device link not
  permitted
```

It could got it working in `Examples/Python/CMakeLists.txt`:

```
-file(CREATE_LINK ${CMAKE_CURRENT_SOURCE_DIR}/python/acts/${f} ${_target})
+file(CREATE_LINK ${CMAKE_CURRENT_SOURCE_DIR}/python/acts/${f} ${_target} SYMBOLIC)
```

If that works just as well, should I submit a PR with this change?

Labels: Bug, Impact - Minor

**Comment by paulgessinger** [comment]
Oh I didn't actually know that `CREATE_LINK` creates a hard link by default. So yes, @timadye, by all means please create a PR!
