### ISSUE TITLE
Create CylinderBounds with inclined cut-off

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#1072]
In order to create Volume shapes needed e.g. for the ATLAS MS coils or the EIC/ATHENA inclined beam pipe cut-out, an addition to the current cylinder bounds for surfaces is needed.

![Screenshot 2021-11-08 at 15 26 51](https://user-images.githubusercontent.com/26623879/140759612-f6fcd7b7-00c6-429e-b965-b21f66e54c90.png)

This should be possible to be done on either side independently, steered by appropriate parameters.

**Comment by paulgessinger** [comment]
See #1104

**Comment by asalzburger** [comment]
This has been implemented.
