### ISSUE TITLE
MaterialMapping logic is flawed

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#1088]
The logic of assigning material hits to surfaces is flawed (which might have been my mistake even).

Imagine the following setup:

![Screenshot 2021-11-29 at 15 56 33](https://user-images.githubusercontent.com/26623879/143890508-84ace11d-ad2a-46cc-bc08-3f14234dc30f.png)

In this case, the blue recorded material point will be assigned to the dashed line, rather to the closer blue solid one, as only one surface switch is done by the algorithm.

This can be reproduced using the `OpenDataDetector` with following one particle along eta=0.

(1) Record one Geantino:

```shell
./ActsExampleMaterialRecordingDD4hep --dd4hep-input ../../../dev/acts-main/thirdparty/OpenDataDetector/xml/OpenDataDetector.xml -n1 --output-root --gen-eta  0:0
```

(2) Map it back on:

```shell
./ActsExampleMaterialMappingDD4hep --dd4hep-input ../../../dev/acts-main/thirdparty/OpenDataDetector/xml/OpenDataDetector.xml -n1000 --output-root --input-root on --input-file geant4_material_tracks.root  --mat-output-file odd-material-map.root -l0 | tee logfile
```

The last hit should be associated with the solenoid surface, but is mapped onto the boundary. I've augmented some output to show this:

```shell
------------------------------
   Distance to previous 359.339144
   Distance to current 159.633159
   Distance to next    74.588317
   Distance to next-next 19.999947
```

So, it should be mapped onto the next-next surface ... 

I've added just a few ``cout`` statements:

```c++
    // Do we need to switch to next assignment surface ?
    if (sfIter != mappingSurfaces.end() - 1) {

      if ( sfIter != mappingSurfaces.begin()){
        std::cout << "   Distance to previous " << (rmIter->position - (sfIter-1)->position).norm() << std::endl;
      }
      std::cout << "   Distance to current " << (rmIter->position - sfIter->position).norm() << std::endl;
      std::cout << "   Distance to next    " << (rmIter->position - (sfIter+1)->position).norm() << std::endl;
      if ( (sfIter+2) != mappingSurfaces.end()){
        std::cout << "   Distance to next-next " << (rmIter->position - (sfIter+2)->position).norm() << std::endl;
      }
```

**Comment by paulgessinger** [comment]
Can you help me understand why this is? Why is the solid blue surface *next-to-next* surface here and not *next*?

**Comment by asalzburger** [comment]
The problem was the implementation:
- as input you have a list of material steps on the one hand and a list of surfaces on the other
- both of them are ordered (by construction) from the origin

In order not to do searches of every step with every surface, the logic is:
a - start from the first material, find the closest surface (i.e. the next one is further away then the current)
b - then this somehow dynamically walks through the detector and assigns the hits to the surfaces 

The problem was in the implementation of a) which assumed that the next surface (if closer to the hit) is the one to take, without checking if there are even closer ones if you just looked further (the solid one needs to steps further), etc.

The inserted ``continue`` now allows to pick the surface that is closest until the one next is again further away.

**Comment by asalzburger** [comment]
<img width="826" alt="Screenshot 2021-11-30 at 16 57 42" src="https://user-images.githubusercontent.com/26623879/144087970-fcf4aad8-1559-46ee-81ef-3d5dcdc5b641.png">

fixed.
