### ISSUE TITLE
Separate Geantino recording and full Geant4 simulation

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#111]
Running the full Geant4 simulation with track recording introduces a factor 60 slow down and is not needed for the Geantino recording. Either add configuration options to disable or split into two separate algorithms.

_Originally posted by @Corentin-Allaire in https://github.com/acts-project/acts/pull/82_

**Comment by Corentin-Allaire** [comment]
I think a separate algorithm would probably be better that way we keep the geantino recording for material mapping purpose only.

**Comment by asalzburger** [comment]
I agree.

**Comment by paulgessinger** [comment]
Did this happen @Corentin-Allaire ?

**Comment by Corentin-Allaire** [comment]
From what I can see the track recording  has been removed and not put back but maybe I am missing it.

**Comment by msmk0** [comment]
No, but it it needs to go back in soonish.
