### ISSUE TITLE
Autodiff plugin is not compatible with current versions of autodiff

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#1135]
Trying to build the ACTS autodiff plugin against a current version of autodiff will fail because the autodiff 0.6.x release series moved around several headers, including the autodiff/forward.hpp header that the ACTS autodiff plugin relies on.

cc @benjaminhuth

**Comment by benjaminhuth** [comment]
I did not follow the developements in the `autodiff` library, but I'll work out a PR to make it compatible again...
