### ISSUE TITLE
Enable Response File for job configuration

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#114]
Parsing ROOT/DD4Hep geometry or changing the many parameters int he examples is pretty hand-crafty.

BOOST does offer the `boost_program_options` to be fed from 
`#include <boost/property_tree/json_parser.hpp>` 

This relies on 
- [ ] #82 to be merged in.

This will be fixed with #116

**Comment by msmk0** [comment]
I would suggest to **not** use JSON for this. This would add a second (incompatible?) format for input parameters and add a second JSON parser in addition to `nlohmann::json`. The parameters are also not really nested but are just single variables and I would prefer to not support anything more complicated than that in the examples configuration.

I would instead suggest to use the [response file](https://www.boost.org/doc/libs/1_72_0/doc/html/program_options/howto.html#id-1.3.32.6.4) solution suggested by `program_options`.

**Comment by asalzburger** [comment]
That's a good suggestion, I actually used nlohman for a small test, but if there's anyway a way `program_options` are suggesting, then we should stick to it.

**Comment by asalzburger** [comment]
I've implemented as suggested by in `boost` documentation.

With the PR coming on top of #82 one will be able to run:
```sh
./ActsExampleHelloWorld @response.cfn   
```

or:
```sh
./ActsExampleHelloWorld --response-file=response.cfn   
```

or call the options explicitly:
```sh
./ActsExampleHelloWorld -n1 -l0 
```

The `cat response.cfn` would yield here
```sh
-n1 -l0
```

**Comment by asalzburger** [comment]
@msmko - is that what you were thinking of?

**Comment by asalzburger** [comment]
Oh - this one is funny, it got closed automatically.

**Comment by msmk0** [comment]
That is what I thought and thus re-opened it.

**Comment by asalzburger** [comment]
Closing this one as it was merged.
