### ISSUE TITLE
Can we require cmake 3.17

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#115]
For the CUDA plugin, this would improve the way cmake handles command line options to nvcc. 
Can we do this only for the plugin? So that we have a 'soft' failure if the version is too low, ONLY if the plugin is enabled?

/cc @msmk0 wants to follow up.

**Comment by msmk0** [comment]
The minimum CMake version is mandated by the lowest LCG release we support. At the moment this is 95apython3 with CMake 3.11.
