### ISSUE TITLE
ITk Information expected in TGeo Example

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#1153]
There is currently ITk information expected in the TGeometry JSON reader for example [here](https://github.com/acts-project/acts/blob/7a4814b4d375db8d43da2637aa773bfeef5c200a/Examples/Detectors/TGeoDetector/include/ActsExamples/TGeoDetector/JsonTGeoDetectorConfig.hpp?_pjax=%23js-repo-pjax-container#L144). Is this intended to be present given that these examples can be used to do the material mapping? The TGeometry standalone example can't run unless the JSON configuration has some expected ITk geometry info.

**Comment by paulgessinger** [comment]
The reason this is there is that we needed specific functionality to enable the ITk geometry. In principle, if the splitting here is disabled, this should be equivalent to the defaults before the introduction of the splitting functionality. 

In any case, obviously the standalone example should not be broken by out of the box by the existence of this options.

@niermann999 could you take a look at this?

**Comment by paulgessinger** [comment]
In discussion today, we realized that there is another key `geo-tgeo-cyl-disc-split` that has to be there, but can be safely configured to do nothing.

**Comment by niermann999** [comment]
This works for me regarding the ITk option. Should I treat the ```geo-tgeo-cyl-disc-split``` the same way?
