### ISSUE TITLE
Proposal for the segmentation,resolution,... file format

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#119]
We need to be able to configure various geometry dependent quantities, e.g. segmentation or resolution. Quantities are usually set for larger structures within the geometry hierarchy, e.g. a volume or a layer, but can be set also at the module/ sensitive surface level. More specific settings (e.g. overrides for a few specific modules) must override the higher level settings.

The following JSON-based format is proposed to store such configuration. Each file would store one specific object type anchored in the geometry hierarchy.

```
{
  # this key must always be present to identify the file type
  "acts_geometry_hierarchy" : {
    # must always be present and set to zero
    # intended as a forward-compatible version number. the value should be increased if the file structure changes
    "version": 0,
    # identify the object type that is stored in the geometry hierarchy
    "object": "<identifier_for_stored_objects>",
  },
  # stores objects in a flat list; the hierarchy is encoded by setting some of the geometry identifier components
  "entries":  [
    {
      # volume must always be present
      "volume": 12,
      # item-specific settings are stored under `value`
      "value": {
        "<segmentation_specific_setting>": 1,
        "something_else": [1, 2, 3]
      }
    },
    {
      # more specific entry overrides the volume setting for elements at or below this node in the hierarchy
      "volume": 12,
      "layer": 3,
      "sensitive": 14,
      "value": {
        "<segmentation_specific_setting>": 2
      }
    },
  ],
}
```

**Comment by asalzburger** [comment]
In this light, I think even if we move away from `Layers` as dedicated objects as described in #13, we should keep them as a logical object.

**Comment by asalzburger** [comment]
Do you foresee a `resolution` for parameterised smearing and `segmentation` for the geometric/general digitisation?

**Comment by msmk0** [comment]
> In this light, I think even if we move away from `Layers` as dedicated objects as described in #13, we should keep them as a logical object.

I agree. The proposed structure does not really care about the physical organization, only about the logical hierarchy.

> Do you foresee a `resolution` for parameterized smearing and `segmentation` for the geometric/general digitization?

Yes, the resolution could also be used in the reconstruction. In the case of binary pixels (or close enough), the resolution can also be derived from the segmentation. So the two things should be distinct.

As an aside: the same config structure (anchored in the geometry hierarchy) could also be used to configure e.g. the cuts for the CKF in #102. The file format might only be used within the examples but the basic structure (as introduced in #120) could be used also outside the examples.

**Comment by msmk0** [comment]
@Corentin-Allaire I updated the file format description to include a file type identifier and switch to a simpler one object type per file structure.

**Comment by msmk0** [comment]
The structure of the file format is already implemented by the `GeometryHierarchyMapJsonConverter`. How the information for concrete datatypes is encoded can be clarified later. I will close this for now.
