### ISSUE TITLE
Do we need ACTS_PLUGIN_GEOMETRYID?

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#121]
Do we want to make an `ACTS_PLUGIN_GEOMETRYID` that allows this to be overwritten ?

_Originally posted by @asalzburger in https://github.com/acts-project/acts/pull/120_

**Comment by msmk0** [comment]
I do not think that we do. The `GeometryID` interface is used everywhere and a lot of code relies on the specific structure. The only thing that could be changed at this point would be the bit with of the different components. Given that there is plenty of headroom available to change that, I would prefer to not add additional configuration that is not currently needed.

**Comment by msmk0** [comment]
@asalzburger If you do not have any objections, I will close this issue.

**Comment by asalzburger** [comment]
Fine with me.
