### ISSUE TITLE
Gain Matrix Update fails sometimes for the ODD

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#1215]
This looks to me like for some reason the gain matrix contains NaNs in the case of the ODD. This does not occur with the Generic Detector, so my suspicion is that it has something to do with the ODD material.

Should be reproducible by running `CI/physmon/physmon.py` with the python bindings compiled and set up.

This requires (temporarily) disabling the log level failure threshold in the CI for the python level tests and the physics monitoring.

/cc @asalzburger

**Comment by paulgessinger** [comment]
@andiwand brought up that there might be a way to do an alternative (approximate?) inversion that could still be calculatable if the full inverse results in NaNs.

**Comment by andiwand** [comment]
for reference this is where it happens https://github.com/acts-project/acts/blob/main/Core/src/TrackFitting/GainMatrixSmoother.cpp#L64

after a little digging I think this is the smoother that is currently implemented https://en.wikipedia.org/wiki/Kalman_filter#Rauch%E2%80%93Tung%E2%80%93Striebel
an alternative would be https://en.wikipedia.org/wiki/Kalman_filter#Modified_Bryson%E2%80%93Frazier_smoother which does not require the inverse

**Comment by andiwand** [comment]
should we close this issue? @paulgessinger @asalzburger

**Comment by paulgessinger** [comment]
Let's do that when we remove the failure masking in the pytest tests.

**Comment by andiwand** [comment]
looks like it works https://github.com/acts-project/acts/pull/1302 :tada:
