### ISSUE TITLE
feat: Remove Clusterization.hpp/ipp

### ISSUE THREAD

**Issue by gagnonlg** [acts-project/acts#1219]
After #1190 is merged, we'll have two competing clusterization implementation. From my benchmarking, it's clear that the current version underperforms : ![test_ACTS](https://user-images.githubusercontent.com/2743680/160934561-7b595c72-887c-4bbf-8dab-de67b11bc0d3.png)

Since it has been in the Core library for a while now, I suggest deprecating the header for a few release cycle (#1190 does that) and remove it sometimes in the future. This issue should serve as a reminder to do just that.

Note that #1190 is not a drop-in replacement as the api is slightly different (a necessity to make it faster)

If anyone disagrees, please shout

L-G

**Comment by paulgessinger** [comment]
Sounds like a good idea to me.

**Comment by gagnonlg** [comment]
unstaling this as this is a reminder issue
