### ISSUE TITLE
Python bindings: ship modules containing the `addXYZ` functions

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#1242]
This would allow us to conveniently configure the full chain example in e.g. the ODD.

I guess one option would be to include them under the `acts` package, maybe something like `acts.examples.fragments`?

/cc @timadye

**Comment by timadye** [comment]
If they were all in one package, you could simplify the imports. Eg. instead of
```
from particle_gun import addParticleGun, MomentumConfig
from fatras import addFatras
```

you could say:

```
from acts.examples.fragments import addParticleGun, MomentumConfig, addFatras
```

I must say I don't like the name `fragments`, which refers to what is implemented, rather than what it does. I'll try to think of an alternative, but hopefully someone else has a better idea first.

**Comment by paulgessinger** [comment]
One question would if we put them in there as python packages under `fragments` (or other name). That would look like 

```
fatras
  ├── __init__.py
  ├── __main__.py
```

where `__init__.py` contains the actual `addFatras` function, and `__main__.py` has the code to run the isolated example.
That would allow one to run

```console
python -m acts.examples.fragments.fatras
```

**Comment by timadye** [comment]
Setting up a `__main__.py` would mean moving the `runFatras` function as well.

**Comment by paulgessinger** [comment]
That is correct. I guess the benefit would really be that the "canonical" examples could be part of the package itself, but I think it does come with a number of downsides. So definitely needs further discussion.

**Comment by jmasik** [comment]
Sorry for a tangential comment but why there is a directory structure with twice python and twice examples in the path? 
Are there other .py files not considered as examples? And is the extra fragments subdir needed?

**Comment by jmasik** [comment]
I meant ./Examples/Python/python/acts/examples which looks duplicating

**Comment by paulgessinger** [comment]
I see. That is only for code organization reasons. The    `acts` tree and below is what is visible as the python import hierarchy, and the folders above are meant to indicate that the entire python bindings are only supposed to be used with/for the examples. 

I don't want to put the python binding code further up the chain because they are not really part of the core ACTS "product". 

Does that make sense?

**Comment by jmasik** [comment]
OK, thanks for clarification

**Comment by CouthuresJeremy** [comment]
> I must say I don't like the name `fragments`, which refers to what is implemented, rather than what it does. I'll try to think of an alternative, but hopefully someone else has a better idea first.

Does splitting `fragments` in `simulation` and `reconstruction` would be better?

It would then looks like:

```
from acts.examples.simulation import addParticleGun, MomentumConfig, addFatras
from acts.examples.reconstruction import addSeeding, addCKFTracks
```

**Comment by timadye** [comment]
> Does splitting `fragments` in `simulation` and `reconstruction` would be better?

I like this. It adds some modularity, without people having to know where everything lives. Maybe others `itk` and and `ODD` for the detector setup.

**Comment by tboldagh** [comment]
Above idea looks very good. I guess an PR would be in place? Does it have to happen in one go? I guess not. Is anyone on this?

**Comment by paulgessinger** [comment]
I don't think anyone is currently actively working on this.

**Comment by tboldagh** [comment]
I think it would be helpful to (almost mechanically) split the examples in Examples/Scripts/Python into sth. that can be imported and reused and the test themselves. People love python bindings and will build around it.

**Comment by tboldagh** [comment]
Please have a look at the branch:
https://github.com/tboldagh/acts/pull/new/refactor-example-python-scipts

I basically did two things there:
moved file fatras.py into acts.examples.simulation.fatras.__init__.py and separated out the __main__.py to have it runable.

If that looks good I would expand this.

Such change would also require an immediate update of the documentation I guess?

**Comment by paulgessinger** [comment]
In principle, I guess this would be a useful improvement overall.
Maybe we could do this for the individual components and use `__main__.py` as demonstrators, but keep the "standalone" 
higher level scripts as actual scripts (like the full chain scripts, or CKF tracks, but not sure).

I think feedback from @timadye would also be very helpful.

**Comment by timadye** [comment]
@tboldagh, thanks for making a concrete proposal and especially thinking about the build requirements. I think this would be an improvement already, so I hope further discussion (even if I add to it 😉) doesn't delay us too much longer.

One immediate simplification: With this layout, I don't think we need to split `simulation` and `reconstruction` into separate namespaces. We could just have `acts.examples.fatras` and `acts.examples.seeding`.

I think the  @CouthuresJeremy's idea was to group all simulation routines in a single package to allow simpler `import`s, eg.
```
from acts.examples.simulation import addParticleGun, MomentumConfig, addFatras
from acts.examples.reconstruction import addSeeding, addCKFTracks
```
I like that option, but I don't think it is needed if we already split each function in its own package.

(I'll follow up on @paulgessinger's suggestion next.)

**Comment by timadye** [comment]
@paulgessinger, yes I agree it would be a bit clearer to keep the `runFatras` code to test and run `addFatras` in a stand-alone script along with the other examples, ie. in `Examples/Scripts/Python/fatras.py`.

That keeps a clear distinction between functions that are can be used by everyone (`addFatras` in @tboldagh's new `Examples/Python/python/acts/examples/fatras/__init__.py`) and example usage that people are encouraged to play with (`runFatras` and `__main__`  in `Examples/Scripts/Python/fatras.py`).

That said, I'm not sure what we could do in `Examples/Python/python/acts/examples/fatras/__main__.py`. Can one test `addFatras` without `runFatras` (or a similarly complicated `__main__`)? Maybe we don't need a separate test here.

One disadvantage of this approach is that we can't remove the requirement for `pytest` to add `Examples/Scripts/Python` to `sys.path`. That wouldn't be necessary if `runFatras` were in the `acts.examples.fatras` namespace. But I don't think that's a big deal, and anyway we might still need it for other tests.

**Comment by paulgessinger** [comment]
I think having the `__main__.py` has some benefits too, but potentially we could dial down the standalone scripts in `Examples/Scripts/Python` to the "main" ones, and then have the smaller individual runnables only in `__main__.py`.

**Comment by timadye** [comment]
@tboldagh, would it help if I made a proto-MR with my suggestion to compare?

**Comment by timadye** [comment]
> I think having the `__main__.py` has some benefits too, but potentially we could dial down the standalone scripts in `Examples/Scripts/Python` to the "main" ones, and then have the smaller individual runnables only in `__main__.py`.

I see what you mean. So would we put the `runFatras` in the `fatras` package's `__main__.py`? I'm not so sure they belong in the `acts.examples.fatras` namespace, even if that might be convenient for the pytest.

So what are the "main" examples of the use of the `addXYZ` functions? Maybe `full_chain_itk.py`, `full_chain_odd.py`, `itk_seeding.py`, `truth_tracking_gsf.py`, `truth_tracking_kalman.py`, `truth_tracking_telescope.py`, and `vertex_fitting.py`.

We have so far had `ckf_tracking.py` as the Generic detector equivalent of the full-chain examples (at least until they get the ambi, final fit, and vertexing added in). Should we make a `full_chain_generic.py` for that case. That might duplicate the `ckf_tracking`'s lengthy `runCKFTracks`, which is a bit ugly but would allow them to diverge later.

**Comment by tboldagh** [comment]
Maybe we can do adiabatic change. I.e. only move addFatras and leave everything else as is? There is som merit to it. Ie.. no need to touch the documentation. @timadye - I do not mind seeing what you have in mind :-).

**Comment by timadye** [comment]
This is the really simple idea: https://github.com/timadye/acts/commit/c23c3f9
That puts both `addParticleGun` and `addFatras` (and later `addDigitization`) together in `acts.examples.simulation`. This makes `simulation.py` a longer file than might be comfortable, but simplifies the `import`s.
I'd plan to make `acts.examples.reconstruction`, `acts.examples.itk`,  and `acts.examples.odd`.

**Comment by tboldagh** [comment]
Looks convenient and straightforward. 
One thing, if one decided not to build FATRAS binding, would one still be able to make use of this file? Or there will be import issues preventing it?

**Comment by timadye** [comment]
Good point. Is it useful to use the particle gun without Fatras? If so, maybe we can add a catch protection, but I don't know the neatest way to do that.

**Comment by tboldagh** [comment]
One can probably hide necessary imports in function body. And thus it will fail only if explicitly (miss)used.
So, what it the next step here?

**Comment by timadye** [comment]
> One can probably hide necessary imports in function body. And thus it will fail only if explicitly (miss)used.

Good idea.

> So, what it the next step here?

I can try to do the rest, but won't have a chance to do much in the next few days (still playing with your `confTool.py`). Anyone else is welcome to give it a go, but please speak up here first so we don't duplicate.

**Comment by paulgessinger** [comment]
Do you think we should discuss this again next Tuesday in the developer meeting?

**Comment by tboldagh** [comment]
@timadye  I would like to try this (just to have first PR) in Acts behind me. Discussing on Tuesday is good idea before doing it.  Maybe even better idea will show up.
