### ISSUE TITLE
ObjPropagationStepsWriter doesn't work with the python binding on MacOS

### ISSUE THREAD

**Issue by Corentin-Allaire** [acts-project/acts#1253]
The python binding for ObjPropagationStepsWriter don't seem to work with ObjPropagationStepsWriter on MacOS.

For example when running `propagation.py ` one get the following error : `IndexError: Type mismatch for object 'propagation-steps'`

My guess is that it has something to do with the fact ObjPropagationStepsWriter is templated on the step type (since RootPropagationStepsWriter which is extremely similar doesn't experience the same issue).

What is also really weird is that changing the value given to the collection arg changes the error : 

```    s.addWriter(
        acts.examples.ObjPropagationStepsWriter(
            level=acts.logging.INFO,
            collection="propagation-steps",
            outputDir=outputDir + "/obj",
        )
    )
```
gives : `IndexError: Type mismatch for object 'propagation-steps'`

While 
```    s.addWriter(
        acts.examples.ObjPropagationStepsWriter(
            level=acts.logging.INFO,
            collection="steps",
            outputDir=outputDir + "/obj",
        )
    )
```
return : `IndexError: Object 'steps' does not exists`

I haven't tested if other python bindings are affected.

**Comment by paulgessinger** [comment]
We should probably add the python tests to the CI job. If we want to enable the hash checks we'd have to store multiple reference files since the hashes might be different between OSs.

**Comment by Corentin-Allaire** [comment]
I am not even sure we need to do the hash checks. Checking that they run might be enough

**Comment by plariono** [comment]
@Corentin-Allaire is the issue gone for you? I'm still getting it

**Comment by Corentin-Allaire** [comment]
I don't know, I don't use this function regularly. But I don't see why it would be gone since the issue was never resolved. As I said last time just comment out the line and it should be fine.

**Comment by Corentin-Allaire** [comment]
I just retried this and it seem to be fixed somehow...
@plariono could you also try ? (using the propagation.py for example ?) If it also work for you I guess we can resolve this

**Comment by plariono** [comment]
@Corentin-Allaire Yes, also for me the error disappeared.

**Comment by paulgessinger** [comment]
Ok then let's tentatively close. Feel free to reopen if the issue pops up again.
