### ISSUE TITLE
Nontrivial Changes to Seeding

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#1280]
We have updated our sPHENIX version of Acts from v17.0.0 to v19.1.0 this week. We have found that the performance of the seeding algorithm from Acts degrades slightly, even in single particle simulations, between the two versions. In our simulations, the seeding efficiency drops by a few percent (maybe 2-4%) in single particles. I assume this degradation will then be worse in our typical high multiplicity occupancies.

Looking through the change logs, there are a significant number of changes to the seeder which looks like they are related to seeding studies in the ITk. Note that in updating from 17.0.0-19.1.0 we did not change any of our seeding configuration parameters. What is the best way to debug what has changed in the seeder that causes the performance degradation between the two versions?

**Comment by paulgessinger** [comment]
Was discussed at any point?

**Comment by osbornjd** [comment]
Yes, we discussed it at a dev meeting when I think you were on vacation. The solution was as follows:
1. Develop a CI test which reads in a typical sPHENIX event for seeding so that we can monitor any possible changes.
2. I am working with @robertlangenberg to identify where the loss in efficiency comes. I provided him an example single track 3 space points that were found in v17 but were not found in v19 with the same seeding parameters. I think the debugging is ongoing.

**Comment by LuisFelipeCoelho** [comment]
From my side, the only PR that changes the final seeds when using the default configuration is PR #1213, but that is a fix to the previous scatter calculation, which was wrong.

**Comment by LuisFelipeCoelho** [comment]
But in that same PR #1213 the sorting of SP by cotTheta is changed to default, maybe that is a reason for the loss of efficiency?

**Comment by robertlangenberg** [comment]
The seed is rejected because of the new scattering calculation. It is also BARELY rejected, if the measurement uncertainty was 10% higher or there was 10% more material configured, the seed would pass.

**Comment by osbornjd** [comment]
To close this, if we scale our space point uncertainties by a certain factor we can recover the previous performance. So we have at least understood where the decrease in performance comes from - therefore I propose we close this issue.
