### ISSUE TITLE
[Bug] FATRAS has trouble simulating electrons with eta between -4 and -1

### ISSUE THREAD

**Issue by Maury-arty** [acts-project/acts#1284]
When given the output of Particle Gun for electrons (uniform distribution of eta from -4 to 4), FATRAS has trouble simulating electrons which have eta between -4 and -1. The output of Particle Gun was manually checked and has a uniform distribution in eta as asked.

Concretely, for some electrons, no hits are generated. Those electrons are all with eta between -4 and -1 (in their initial state).
Also, when plotting the eta distribution of all hits, one can see a depletion for electrons between -4 and -1, whereas this distribution remains uniform for muons.

As can be seen in the spatial plot of all hits, in the case of electrons, there is a lack of hits in the "rear" part of the detector while in the muon case, the whole detector has hits.

This issue also arises when using the ITk geometry, the ATLAS B field, different regions of pT, both signs for particles...

To reproduce the error (I used the (deprecated) executables), with the TrackML geometry and a constant B field:
`ActsExampleParticleGun --events=10000 --output-dir=1_particle_gun --output-csv --gen-vertex-xy-std-mm=0.012 --gen-vertex-z-std-mm=50 --gen-eta=-4:4 --gen-eta-uniform --gen-pdg=11 --gen-mom-gev=1:5 --gen-mom-transverse`
`ActsExampleFatrasGeneric --input-dir=1_particle_gun --output-dir=2_fatras --output-csv --remove-neutral --bf-constant-tesla=0:0:2`

Replace --gen-pdg option with 13 for muons (mu-).

![spatial_hits_electrons](https://user-images.githubusercontent.com/62028932/174828186-b218e9ee-fa91-4d50-83c8-ae650693e109.png)
![spatial_hits_muons](https://user-images.githubusercontent.com/62028932/174828192-f7c812da-509c-44d7-bfa1-3bb9bcb590cd.png)
![fatras_hits_muons_electrons_eta](https://user-images.githubusercontent.com/62028932/174828195-61d47245-325f-4207-93ca-adc86f8097f8.png)
![initial_state_electrons_eta](https://user-images.githubusercontent.com/62028932/174828201-111c7454-7483-4c36-919a-cfe116addcfa.png)

**Comment by andiwand** [comment]
removing the material with `--mat-input-type=none` or turning off EM radiation with `--fatras-em-radiation=0` removes the artifacts

I was not able to reproduce this with python yet because I could not get the materials up for the `GenericDetector` which is used by `ActsExampleFatrasGeneric`

**Comment by andiwand** [comment]
after enabling the interaction in python I can see the same artifacts

![image](https://user-images.githubusercontent.com/487211/175033921-72863607-e21b-4196-9414-e5d5fc1e1462.png)

**Comment by asalzburger** [comment]
Looks like this is a problem of either the material description (should not be), or - more likely - a bug in the energy loss module.

One might have to put some cout's in the energy loss function and see what it means.

**Comment by Maury-arty** [comment]
It seems that when disabling the fatras-em-radiation option (=0), we don't get this issue.

**Comment by andiwand** [comment]
energy loss from https://github.com/acts-project/acts/blob/main/Fatras/include/ActsFatras/Physics/ElectroMagnetic/BetheHeitler.hpp#L65

![Figure_1](https://user-images.githubusercontent.com/487211/175044154-5f4dc217-f25c-471b-901e-0da99d5362c3.png)

**Comment by Maury-arty** [comment]
@andiwand Interesting! [slab.thicknessInX0()](https://github.com/acts-project/acts/blob/main/Fatras/include/ActsFatras/Physics/ElectroMagnetic/BetheHeitler.hpp#L60) indeed seems to get negative values. Thanks for this hugely useful indication ;)
When I put a simple std::abs for this variable, everything seems to get back in order: no missing hits, all electrons have hits from eta -4 to 4.
I'm currently digging as to why this value could be negative and what is its impact.

**Comment by asalzburger** [comment]
BUG BUG BUG ALERT!

`std::abs` should do the trick, great work @andiwand
