### ISSUE TITLE
World without layers

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#13]
[GitLab issue: #712](https://gitlab.cern.ch/acts/acts-core/issues/712)

`Layer` objects got more and more the functionality of Volumes.

Actually it only needs:
- DetectorVolumes with boundary portals

InternalDescriptors:
- `ContainerDescriptor` for navigation in the volume hierarchy
- `LayerDescriptor` for volumes representing a layer
- `BoundingHieararchyDescriptor` for volume representing a BB hiearachy

This will be tested on a new `DetectorVolume` which will replace eventually the `TrackingVolume`, this should help for ITk, ATLAS TRT, ATLAS Calorimeter, etc.

**Comment by msmk0** [comment]
Switch to Long Term since this is a bit larger.
