### ISSUE TITLE
add monitoring for vertexing in physmon

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#1313]
we have vertexing as part of the odd full chain now in [´full_chain_odd.py´](https://github.com/acts-project/acts/blob/main/Examples/Scripts/Python/full_chain_odd.py) but no monitoring in [`physmon.py`](https://github.com/acts-project/acts/blob/main/CI/physmon/physmon.py)

see discussion here https://github.com/acts-project/acts/pull/1299

**Comment by paulgessinger** [comment]
I'm working on this.
