### ISSUE TITLE
Remove obsolete parameter enum typedefs

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#137]
Replace the usage of the following deprecated enum typefs
```
using ParDef = BoundParametersIndices;
using ParID_t = BoundParametersIndices;
using ParValue_t = BoundParametersScalar;
```
in favor of the specific underlying enums and remove them from the `ParameterDefinition.hpp` file.

This is a larger change that needs to be split over multiple PRs.

**Comment by paulgessinger** [comment]
The other names are sooooo much longer... :/

**Comment by msmk0** [comment]
That was kind-of the point of introducing them; to have descriptive names that allow more than one parameters type.

It does not really matter that much for the indices enums. Since they must be regular enums (as discussed in the context of [their introduction](https://gitlab.cern.ch/acts/acts-core/-/merge_requests/785) the enum values do not need be qualified. You can use use e.g. `eBoundPhi` instead of `BoundParametersIndices::eBoundPhi`.

Depending on the decision in #151 we might consider shortening them a bit, e.g. to just
```cpp
enum BoundIndices { ... };
using BoundScalar = ...;
```
However, that must happen before we start removing the obsoleted typedefs.
