### ISSUE TITLE
Add conical volume bounds

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#14]
[GitLab issue: #711](https://gitlab.cern.ch/acts/acts-core/issues/711)
Referenced by the following MRs on GitLab: [!779](https://gitlab.cern.ch/acts/acts-core/-/merge_requests/779)

For the description of e.g. Belle-2 we need conical volume bounds.

**Comment by asalzburger** [comment]
Code exists, will have to be imported after #73 is fixed.

**Comment by msmk0** [comment]
@asalzburger Is this still open or has it been already fixed?

**Comment by asalzburger** [comment]
Fixed.
