### ISSUE TITLE
Full chain vertexing with AMVF

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#1406]
> Looks ok, let's go with IVF first and look into AMVF. Do you know if AMVF runs into errors in the current status?

AMVF will produce an error in the current scenario. I guess it is because we loose one of the muons and then fail to fit the vertex. with 4 muons AMVF works but IVF even works with 2 but I am not sure why

_Originally posted by @andiwand in https://github.com/acts-project/acts/issues/1299#issuecomment-1206199044_

**Comment by tboldagh** [comment]
In ATLAS. We'll soon have HI run where significant part of  the data are UPC events. Typically a (very)few particles in event. 
Given AMVF is part of ATLAS reco already this may be affecting reconstruction (I do not think we care about it in HLT). 

How does one reproduce this issue actually? 
Setup vertex ting chain with AMVF and particle gun to generate 4,3,2 muon events. Right?

**Comment by andiwand** [comment]
to reproduce this issue you can run `full_chain_odd.py` with AMVF instead of IVF. the underlying problem seems to be the high number of duplicated tracks. the vertex fitting blows up under these conditions which seems fair.
