### ISSUE TITLE
Stepper failure during fatras simulation

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#142]
Currently, most of the fatras simulation will fail with stepper error: `Step size adjustment exceeds maximum trials`. This is not observed before though.

**Comment by HadrienG2** [comment]
This could be a problem with the mechanism that allows the step size to go up, which I brought back in #85 .

To check if that is the case, please got to `EigenStepper::step`, inner lambda `tryRungeKuttaStep`, and replace the return statement with its older form, `return (error_estimate <= state.options.tolerance);`.

If that fixes the problem for you, then keep that feature reverted for now, and...

1. Provide me with clear instructions on how to replicate your problem.
2. Make sure that the CI includes a reproducer of that problem (can be a unit test, integration test, or example).

**Comment by msmk0** [comment]
Did I still work just after the move of Fatras into the Core repository (and subsequent cleanups)? Before, all propagation errors where silently ignored in the simulation. Now, they are reported. It might be that the stepper errors were there all along but were ignored.

**Comment by XiaocongAi** [comment]
@HadrienG2 @msmk0 , if we see those errors just because we report it, then it should be fine. But the problem seems to be more complicated since I noticed that the fitted parameter resolution is affected as well. I will go to debug the `stepper` a little bit as @HadrienG2  suggested. 
![image](https://user-images.githubusercontent.com/30073719/80288442-cd1f3600-86ec-11ea-8752-4d656106409e.png)

**Comment by XiaocongAi** [comment]
@HadrienG2 , you're right! Those errors will disappear by replacing the last line of `tryRungeKuttaStep` with `return (error_estimate <= state.options.tolerance);`
However, the fitting results are still not right. It looks like the average chi2 of KF filtering gets larger and the fitting resolution is worse. Not sure if this might be related to some change in particle smearing. @msmk0 Is there any change of particle/hit smearing recently?

**Comment by XiaocongAi** [comment]
@msmk0  Sorry, my bad... The resolution is OK as below. Just forget to use magnetic field for reco while using that for sim.  Please ignore my question above for the resolution. 
![image](https://user-images.githubusercontent.com/30073719/80293332-577a9080-8713-11ea-9855-f08865c4fb3e.png)

**Comment by asalzburger** [comment]
That's good to see!

**Comment by asalzburger** [comment]
Closing this one as it was fixed.
