### ISSUE TITLE
Documentation update: Contribution guidelines

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#1423]
- [x] `CONTRIBUTING.rst` remove style guide part + link to docs style guide
- #1525
  - [x] How to run the formatting (@AJPfleger)
  - [x] How to build the documentation (@paulgessinger)
  - [x] What is clang-tidy (@paulgessinger)
  - [x] What is physmon (@paulgessinger)
  - [x] What are root file hash checks (@paulgessinger)
  - [x] MyST markdown cheat sheet (@benjaminhuth)

**Comment by AJPfleger** [comment]
@paulgessinger
It looks to me, that we finished all tasks. Can we finish/close this project/issue? :)
