### ISSUE TITLE
Remove `AxisDefs` enum

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#143]
The `enum AxisDefs` was initially intended to provide symbolic access to space point information. It is conflicting with multiple other ways to this information and should therefore be removed to avoid confusion.

* Full space points should use the `SpacePointVector` definition and the related enum. The internal layout can be set by the user (e.g. t,x,y,z instead of x,y,z,t) and could thus be inconsistent with `AxisDefs`.
* `Eigen::Vector`s always provide `.x()`, `.y()`, `.z()`, `.w()` accessors for all appropriately-sized types. The index positions are hardcoded. This is the most often used way to access components (by far).

To avoid any confusion and have always a single well-defined way of accessing information. true space-points must use `SpacePointVector` and related enums. Lower-dimensional vectors must use the `.{x,y,z}()` accessors. `enum AxisDefs` should be removed.

**Comment by msmk0** [comment]
I might need to rethink this: the `SpacePointVector` also has the `.x()`, `.y()`, `.z()`, `.w()` accessors from Eigen. If a user defines a custom `enum SpacePointIndices` this is again inconsistent.

One way to avoid this would be to remove the user-configurable `SpacePointVector` and always use a regular 4d vector instead. Then, the non user-configurable `enum AxisDefs` should be kept with an additional entry for time. While regular access can go via the `.{x,y,z,w}()` accessors, e.g. projection matrices must use indices and thus need the enum.

**Comment by XiaocongAi** [comment]
With a second thought on this, the `enum AxisDefs` might be needed for retrieving Euler angles for the alignment. Provided a 3D rotation matrix, we could retrieve different Euler angles by providing the ordered axis indices (e.g. `0, 1, 2` or `2, 1, 0`) via [`Eigen::eulerAngles`](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#title20). So here we need an enum  for the axis indice.

**Comment by msmk0** [comment]
I agree. As discussed in my comment above, I think we should keep `enum AxisDefs`, renamed as `enum AxisIndices` for consistency with the parameter enums. We would also need to add a `eT` entry for the temporal component. That is currently not possible as it conflicts with the `eT` index in the bound parameters. That one is obsolete anyways as discussed in #190, so we could reuse it for the axis index.

A bit off-topic: I am always reluctant to allow different rotation angle conventions because they are just confusing, especially the true Euler angles. My personal preferences is to pick one convention and stick to it throughout the code base.
