### ISSUE TITLE
Do not share the magnetic field, share the field map

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#144]
The `SharedBField` is used to avoid having multiple copies of large field maps by wrapping the underlying magnetic field in a `std::shared_ptr`. This adds indirection even in cases where the magnetic field is easily copyable, e.g. constant or parametrized fields.

Instead, magnetic fields should always be treated as value-types. Interpolated magnetic fields based on field maps should have a `SharedFieldMap` internally that replaces the `SharedBField` that is then shared between different instances of the interpolated magnetic field types.

This could also provide a better way to handle field maps on accelerators; by having different shared field map implementations, e.g. based on pre-allocated accelerator buffers.

**Comment by paulgessinger** [comment]
We will need some form of type erasure mechanism here at some point. The B Field type being a compile time only parameter doesn’t fit well with runtime configuration models like in Atlas for example. 

Apart from that, SharedBfield has the benefit of working with any B field type, not just our interpolated one, which I think is a benefit.
