### ISSUE TITLE
Return surface local-to-global Jacobian by value

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#145]
Make `initJacobianToGlobal(...)` return the matrix by-value instead of returning it by output reference for clearer code. Should probably also be renamed to `makeJacobianToGlobal(...)` to clarify the updated functionality.

**Comment by msmk0** [comment]
@XiaocongAi This was fixed in #534, correct?

**Comment by XiaocongAi** [comment]
Exactly!

**Comment by msmk0** [comment]
Ok, I will close this issue then.
