### ISSUE TITLE
Bug: SpacePointGridCreator::createGrid() fails when minHelixRadius < config.rMax / 2

### ISSUE THREAD

**Issue by askamkin** [acts-project/acts#1456]
If `minHelixRadius < config.rMax / 2`, createGrid (Core/include/Acts/Seeding/SpacePointGrid.ipp) takes the square root of a negative number:
```
float maxR2 = config.rMax * config.rMax;
float xOuter = maxR2 / (2 * minHelixRadius);
float yOuter = std::sqrt(maxR2 - xOuter * xOuter);
```
It seems strange that the method does not work for detectors w/ some configurations. Perhaps the method functionality should be revisited.

I suggest adding a check for this situation w/ a proper error message.

**Comment by paulgessinger** [comment]
Hey @askamkin, thanks for the issue.

@LuisFelipeCoelho, can you comment on this?

**Comment by LuisFelipeCoelho** [comment]
I can add a check for this situation with an error message.

I am also adding @robertlangenberg here in case he has any suggestions.

**Comment by robertlangenberg** [comment]
Not allowing smaller radii is sensible, as otherwise the particle would not escape the detector (i.e. reach rMax). Of course, it should have been checked for in the code. Thank you for notifying us!
