### ISSUE TITLE
Return surface global-to-local Jacobian by value

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#146]
Make `initJacobianToLocal(...)` return the matrix and the reference frame as a `std::tuple` by-value instead of return it by output reference for clearer code. Should probably also be renamed to `makeJacobianToLocal(...)` to clarify the updated functionality.

**Comment by paulgessinger** [comment]
You mean as an output argument reference?

**Comment by msmk0** [comment]
@XiaocongAi This was fixed in #534, correct?

**Comment by msmk0** [comment]
@XiaocongAi Could you clarify whether this was fixed in #534?

**Comment by msmk0** [comment]
@XiaocongAi Could you check that this is fixed #534 ?
