### ISSUE TITLE
Consider always building Fatras

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#149]
There are now a large number of build options that result in a lengthy `CMakeLists.txt` file. To reduce complexity we should consider making some components non-optional. `Fatras` is a good candidate as it does not require additional dependencies, does not any core plugins, and is relatively light-weight (compared e.g. to the unittests).

**Comment by paulgessinger** [comment]
How will this affect our terrible build times?

**Comment by msmk0** [comment]
For the CI builds nothing changes. If you have a build with examples nothing changes because Fatras is automatically activated. If you were building just the Core before it will of course increase, but the build time for the Fatras components is small compared e.g. to the unit tests.

**Comment by msmk0** [comment]
As discussed this morning, Fatras will stay an optional component.
