### ISSUE TITLE
Revisit the logger implementation

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#150]
Each `Logger` currently creates all necessary implementation objects and stores them via `std::unique_ptr`s. This also necessitates that the loggers are always stored via `std::unique_ptr`s themselves. Originally, this was intended to allow maximum per-logger configurability. However, this is not the way it is used. Almost all loggers are created with the default configuration (decorators and ouput policy).

Following other logging libraries we could:
* Split the output handling and the logger object by introducing a `Sink` interface, with a global default sink, e.g. writing to stdout.
* The `Logger` only stores a reference to the `Sink`.
* With most of the functionality moved to the `Sink`, the `Logger` object can be a simple value-type and does not need to be handle via `std::unique_ptr`.

**Comment by paulgessinger** [comment]
We still need the ability to store a level per logger. I actively use this in Athena code. The output decoration can go though in my opinion.
