### ISSUE TITLE
Error while i run ActsExampleAdaptiveMultiVertexFinder  

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1506]
Hi! 
My main goal is to create tracks and vertexes based on real particle information from Pythia and by using ACTS to reconstruct tracks and vertexes. when i try to use ActsExampleAdaptiveMultiVertexFinder  i get error : terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_any_cast>'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast

How can i fix this error? 
![Acts](https://user-images.githubusercontent.com/111228683/189533021-51f9ae9a-83f7-4c72-a0a2-5cf29e92ebac.jpg)

**Comment by paulgessinger** [comment]
Hey @rubihason, thanks for creating an issue.
I think that's a bug in how the options are (not) setup. I created a PR with a fix: https://github.com/acts-project/acts/pull/1508
