### ISSUE TITLE
Separate context and config information in SeedFinderConfig

### ISSUE THREAD

**Issue by tboldagh** [acts-project/acts#1522]
In the SeedFinder integration in Athena 
https://acode-browser1.usatlas.bnl.gov/lxr/source/athena/Tracking/Acts/ActsTrkTools/ActsTrkSeedingTool/src/SeedingTool.cxx
we need to copy construct the config object over and over because the config mixes actual configuration and more of context information.

Separating the two would allow us to reuse SeedFinderConfig object and since it will be made only once (faster) and maybe even think of some validation?

It would be breaking change though.

Tagging: @LuisFelipeCoelho @asalzburger 

BTW. Why the capitalisation Seedfinder is used instead of SeedFinder (like one would expect)?

**Comment by tboldagh** [comment]
Hi Experts, I have some spare cycles and can do the required changes. How does the idea sound?

**Comment by LuisFelipeCoelho** [comment]
The idea sounds good to me.

FYI: @robertlangenberg

**Comment by tboldagh** [comment]
So I had a look. Whereas the beam spot position update is kind of expected update, how realistic is to change magnetic field when processing events? Outside of LHC experiments say.

**Comment by tboldagh** [comment]
See the set of proposed changes:
https://github.com/acts-project/acts/compare/main...tboldagh:acts:refactor-seed-finder-config-and-context?expand=1

**Comment by LuisFelipeCoelho** [comment]
I agree with the changes

**Comment by LuisFelipeCoelho** [comment]
@robertlangenberg, do you know why Seedfinder is not capitalised?

**Comment by robertlangenberg** [comment]
That was a simple oversight, I have no objection against renaming :)

**Comment by asalzburger** [comment]
Yes, let us rename - I always disliked the `Seedfinder` spelling.

**Comment by tboldagh** [comment]
The PR finally addressed this issue entirely. There are small optimisation that I still planned to do but otherwise this ticket can be closed.
