### ISSUE TITLE
Add combined space point accessor to track parameters

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#153]
Track parameters only provide separate `.position()` and `.time()` accessors. Add a combined `.position4()` accessor that returns a `SpacePointVector`.

**Comment by paulgessinger** [comment]
Is this needed anywhere? You always say to not add features if there’s no concrete use case.

**Comment by msmk0** [comment]
I would like to use this e.g. in Fatras. Currently, `.position()` and `.time()` are used, but always together. I expect similar simplifications are possible in the vertex code.
