### ISSUE TITLE
Bring back multi-threaded reproducibility tests

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#157]
The `acts-framework` used to have some tests that cross-checked that an Acts-based computation produces consistent results in single-threaded and multi-threaded mode. These tests were not ported to the new monorepo, and #155 would be an opportunity to fix this.

Note that the old framework MT reproducibility tests should only be used as a source of inspiration, and not copied as-is, as they had some issues:

- Designed at a time where only propagation was in shape suitable for testing, these tests were never extended to cover other Acts activities which need to be thread-safe too.
- [At some point, the number of simulated events was dropped so low that the test would not meaningfully assert the absence of race conditions in the parallel version anymore.](https://gitlab.cern.ch/acts/acts-framework/issues/186)

**Comment by HadrienG2** [comment]
Blocked on #155 .

**Comment by HadrienG2** [comment]
Still blocked on #155.

**Comment by robertlangenberg** [comment]
@HadrienG2 working on it

**Comment by HadrienG2** [comment]
Still blocked on #155, but the good news is, #155 itself is getting closer.

**Comment by HadrienG2** [comment]
Alright, I'm finally bringing this back for propagation! Once that's done, it should be relatively easy to adapt it for other examples that emit ROOT files.

Right now, I have a setup that works well on most Propagation examples, but fails for the PropagationPayload example specifically. This might be a genuine failure indicating a thread-safety problem in the PayloadDetector. But getting back into this work after a long time made me discover that compareRootFile's output could be clearer when the comparison fails, indicating more precisely at which point it failed and why.

So I'll work a bit on this script to make it emit clearer diagnostics on comparison failure, before submitting the PR. One promising track is to stop treating the input files as symmetrical, and instead treat the single-threaded run output as an authoritative reference against which the multi-threaded run output is checked.

Another improvement which I could try to do along the way is to turn compareRootFiles from a ROOT script to a real standalone C++ program. It shouldn't be too hard since no ROOT interpreter functionality is used, and it will bring reduced startup latency (no re-JITting every time the script is re-run) and possibly slightly better performance (not a concern for the number of events that we're running on in CI tho).

I could also try to merge the `testReproducibility.sh` functionality into the program in order to avoid path confusion. I don't think anyone ever used compareRootFiles separately, so the relocability of monolithic program is probably more desirable.

**Comment by HadrienG2** [comment]
I've started work on the compareRootFiles rework, but then got sidetracked by other things like AIDAinnova preparation so it'll take more time than I hoped to finish.

**Comment by HadrienG2** [comment]
Same status as before: blocked on more urgent things.

**Comment by HadrienG2** [comment]
Still waiting for its turn, slowly rising to the top of the work stack...

**Comment by HadrienG2** [comment]
With health issues now also getting in the way, it's fair to say that I just won't get this done anytime soon. So let's at least remove one little source of hurt in my life by preventing the stalebot from periodically reminding me about it.
