### ISSUE TITLE
output of ActsExampleAdaptiveMultiVertexFinder

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1594]
hello,
I was running the example and everything was fine, but the only output is the running time.
there is any possible way to output the data of the vertex, like position or energy and etc?
root or CSV format?
![Acts](https://user-images.githubusercontent.com/111228683/195305245-7bd95bdd-ed94-40e2-8e01-7c18b2678695.jpg)

**Comment by paulgessinger** [comment]
Hey @rubihason! There is indeed the possibility to write information in at least ROOT format (not sure we have CSV for the vertices). The executable here likely has options that control the output.

However, these executable examples are deprecated, so you should consider switching to the python based examples.

**Comment by rubihason** [comment]
Hey, thanks for helping!
I switched to python and the only script for a vertex is "vertex_fitting".
The only data that I received from this script is this:
![Acts](https://user-images.githubusercontent.com/111228683/196371284-cb56863b-cb70-42e3-8a2d-3566d2481724.jpg)
Maybe have more information about the tracks from each vertex?
Perhaps that are more scripts of vertex?

**Comment by paulgessinger** [comment]
About the script: the vertex fitting should also be part of `full_chain_odd.py` and can be configured in the python anywhere else if needed.

Indeed this is only the output used for performance monitoring. There's no coherent output of all the quantities, we only partially have this for particles and tracks. The IO model of the Examples framework is bare-bones.

If you have the need for a particular format, the best way forward is likely to write a writer that you can attach to the job.

**Comment by rubihason** [comment]
Hi, i was trying full_chain_odd.py and it ask for DD4hep, I installed DD4hep and he had some problems finding the file.
maybe you know this error?
![Acts](https://user-images.githubusercontent.com/111228683/196929569-560eb290-f79a-4c8d-bd2a-5c0385755dab.jpg)
