### ISSUE TITLE
Error in running the ATLAS ITk example

### ISSUE THREAD

**Issue by abidihaider** [acts-project/acts#1641]
I am trying to run the ITk tutorial that @timadye ran in the ACTs workshop in September. The only change I have made is to pull the latest HEAD

When I try to run the full_chain_itk.py script, I run into the following error when the vertexing is configured:

```
Traceback (most recent call last):
  File "/home/sabidi/ATLAS/Tracking/ACTS/acts/Examples/Scripts/Python/full_chain_itk.py", line 96, in <module>
    addVertexFitting(
TypeError: addVertexFitting() got multiple values for argument 'outputDirRoot'
```

Let me know if you need any more information

**Comment by andiwand** [comment]
just talked to @paulgessinger if we can/should monitor the ITk full chain somehow but the problem is that we need permissions for that in the CI. I also never ran the ITk full chain locally so I fear this will come up again in the future. any ideas how to avoid this in the future? @timadye

**Comment by timadye** [comment]
I think it would be good to keep the odd and itk examples in sync, but that means being able to test both. Can you run try to run it locally? Once the `acts-itk` repo is downloaded, it isn't a big deal to test. Or don't you have access to that?

**Comment by andiwand** [comment]
I think I have access but never tried it because I haven't been working on the ITk. I will try to set it up

**Comment by timadye** [comment]
> I think I have access but never tried it because I haven't been working on the ITk. I will try to set it up

If you have any trouble, you can find help in my Workshop slides, eg. p5 here:
https://indico.cern.ch/event/1195929/contributions/5036509/attachments/2517451/4328300/tutorial_standalone.pdf

**Comment by andiwand** [comment]
okay that was much easier than I feared - I will try to run this from time to time. hopefully I won't break it so easily in the future @timadye
