### ISSUE TITLE
Analysis apps return different output with different number of threads while reconstruction

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#1657]
In https://github.com/acts-project/acts/pull/1654 we observed that the analysis apps will return different outputs if the reconstruction ran on multiple threads. Our suspicion is that the event order will modify the output of the program.

I attached the observed and reference root files below.

[root_files.zip](https://github.com/acts-project/acts/files/9939321/root_files.zip)

[8_Physics performance checks.txt](https://github.com/acts-project/acts/files/9939426/8_Physics.performance.checks.txt)

**Comment by andiwand** [comment]
it looks like root will produce different histograms when your data is shuffled. our output seems to be equivalent except for the order, which comes from multi threading.

not sure what the solution to this is.
- we could sort the root file before creating the histograms. I had no success sorting the root file in memory tho
- otherwise we have to refactor the analysis scripts which might be a ton of work
  - or we move them to uproot and rewrite them

any opinions @asalzburger @paulgessinger @benjaminhuth

**Comment by HadrienG2** [comment]
> it looks like root will produce different histograms when your data is shuffled. our output seems to be equivalent except for the order, which comes from multi threading.

That makes sense, floating point summation is not associative so if you do summation in different order, you get slightly different results.

The solution IMO is to only test for bitwise histogram reproducibility when running in sequential mode, and resort to some tolerant approximate comparison in the parallel case (may be a simple matter of checking that bins are within N ulps of the expected result, or a fancier histogram statistical test).

**Comment by benjaminhuth** [comment]
I agree.

I think the purpose of physmon is to check that the general performance of our algorithms is constant (e.g., I would also say it would be good if all that works with a random seed instead of a fixed one). However, if e.g. reordering let these tests fail, we are again close to a bitwise-test, and for that we have the root-hashes.

So I would argue instead of refactoring our tools we should think about how we can adjust the tests that they are not so sensitive...

**Comment by andiwand** [comment]
> That could actually make sense. Making a (weighted) histogram is basically computing the sum of a bunch of floats, and floating point summation is not associative, so if you do summation in different order, you get slightly different results.

I thought in order to decide on the bins it has to do some min/max or sorting of the data but it looks like it doesn't. not sure how this works

so we could also use static binning but not sure how to come up with good values

> So I would argue instead of refactoring our tools we should think about how we can adjust the tests that they are not so sensitive...

I agree. I think the histcmp is quite good for that as long as root histograms don't change their binning. the problem is the analysis script which creates a ton of histograms and some of them will have quite low statistics which makes the hist compare useless in that case

I guess we could also just drop the analysis script from the CI if we don't think it is useful

**Comment by andiwand** [comment]
for reference here are the two histograms I saw

single threading

![image](https://user-images.githubusercontent.com/487211/203962222-81508251-1e6a-4927-bb6b-d76841d304f5.png)

multi threading

![image](https://user-images.githubusercontent.com/487211/203962286-e5c4676a-ab98-41cd-be8e-e4347f94bda9.png)

**Comment by HadrienG2** [comment]
It would be nice to have this on a log scale to see the little bins that drive the scale.

**Comment by andiwand** [comment]
good idea

![res_eLOC0_prt-mt](https://user-images.githubusercontent.com/487211/203974793-ddbee272-7981-48f6-8238-235f558c7551.png)
![res_eLOC0_prt-st](https://user-images.githubusercontent.com/487211/203974796-dbfdd5f0-7ac0-4ee2-9f8f-fbe7c36324fa.png)

somehow the reason for the different ranges stays hidden

**Comment by HadrienG2** [comment]
Actually those results look significantly different around -100. Maybe you found an actual parallelism bug ?

**Comment by andiwand** [comment]
I believe it just looks different because of the binning. I checked the two files with https://github.com/acts-project/acts/blob/main/Examples/Python/tests/helpers/hash_root.py and a custom script and they seem to be identical

**Comment by HadrienG2** [comment]
Ah yes you're right, forgot that binning could be different.

**Comment by andiwand** [comment]
it's interesting that there seems to be no data at 350. no clue why or how root comes up with that range. I will check the data with uproot for min max

**Comment by andiwand** [comment]
just checked the range of values in this branch `[-116.75067, 117.44283]`

**Comment by paulgessinger** [comment]
Is this fixed?

**Comment by asalzburger** [comment]
Hi, we use the fist n numbers of events for calculating the range of the histograms, of there's a different order, that could cause differences, right?

**Comment by andiwand** [comment]
I think this is a pure root histogram issue. so the problem does not originate from within acts. I tried messing with the root plotting params but no success. not sure how to follow up on this @paulgessinger @andiwand

**Comment by paulgessinger** [comment]
@andiwand can we close this?

**Comment by andiwand** [comment]
I think we can close it for now. the issue is still there but seems to be caused by root
