### ISSUE TITLE
error while i running full_chain_odd.py

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1661]
Hello,
I was trying to run the script full_chain_odd in python, and I got this error:
```
root@Rubi:~/Thesis/acts/Examples/Scripts/Python# python3 full_chain_odd.py
Error in <TFile::ReadBuffer>: error reading all requested bytes from file /root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root, got 133 of 300
Error in <TFile::Init>: /root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root failed to read the file type data.
Traceback (most recent call last):
  File "full_chain_odd.py", line 18, in <module>
    oddMaterialDeco = acts.IMaterialDecorator.fromFile(oddMaterialMap)
  File "/root/Thesis/acts/acts.build/python/acts/__init__.py", line 60, in _decoratorFromFile
    return ActsPythonBindings._examples.RootMaterialDecorator(
  File "/root/Thesis/acts/acts.build/python/acts/_adapter.py", line 30, in wrapped
    fn(self, cfg, *args, **_kwargs)
RuntimeError: Could not open '/root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root: iostream errorroot@Rubi:~/Thesis/acts/Examples/Scripts/Python#

**Comment by paulgessinger** [comment]
This is likely because you need to initialize and update the ODD repository. You should also double-check that you have git lfs installed.

**Comment by rubihason** [comment]
Hi, it is still not working.
The file odd-material-maps.root is still 133 bytes. Is there are options to download the file?
I followed this https://acts.readthedocs.io/en/latest/getting_started.html#the-opendatadetector.

**Comment by paulgessinger** [comment]
You can download the file from the CERN GitLab directly via the web interface.
This definitely works in a correct git lfs setup, so if it's likely a local issue on your system, that I can't really debug from my end.

**Comment by paulgessinger** [comment]
Was this solved @rubihason ?

**Comment by rubihason** [comment]
No, i can't get in CERN website i dont have a Cern user.
Are there different ways to download this file?

‫בתאריך יום ד׳, 21 בדצמ׳ 2022 ב-12:17 מאת ‪Paul Gessinger‬‏ <‪
***@***.***‬‏>:‬

**Comment by rubihason** [comment]
Hi paul, I have one more question about acts.
I saw the script of the vertex finder, which matching tracks to vertex
inside the algorithm.
Are there some ways to output this data?



‫בתאריך יום ד׳, 21 בדצמ׳ 2022 ב-19:01 מאת ‪hason Rubi‬‏ <‪
***@***.***‬‏>:‬

**Comment by paulgessinger** [comment]
@rubihason did you manage to grab the file? The ODD Gitlab should be world visible, even without a CERN account.

**Comment by owtscharenko** [comment]
I have the same issue, I use the *ubuntu2204_master* docker container with singularity. It seems git lfs is not available there. Unfortunately I am not familiar with docker and singularity. If I try to install git lfs inside the container
`Singularity> sudo apt install git-lfs` I just get *sudo command not found*
Without root rights i can not install git lfs.

I also get the same iostream error message on lxplus after sourcing the LCG 103 script. There git lfs is available and I did 
`git submodule init` and
`git submodule update`
before building. After the build the data files in thirdparty/OpenDataDetector/data/ are only 133 bytes large.

**Comment by rubihason** [comment]
Hello, I tried to use it again after building DD4hep and ODD inside the ACTS build. I followed the instructions from the website: [https://acts.readthedocs.io/en/latest/getting_started.html#the-opendatadetector]. When I ran the command 'python3 full_chain_odd.py,' I encountered the following error:
'''
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
DocumentHandler  INFO  +++ Loading document URI: /home/rubi/Thesis/Acts/thirdparty/OpenDataDetector/xml/OpenDataDetector.xml [Resolved:'/home/rubi/Thesis/Acts/thirdparty/OpenDataDetector/xml/OpenDataDetector.xml']
DocumentHandler  INFO  +++ Document /home/rubi/Thesis/Acts/thirdparty/OpenDataDetector/xml/OpenDataDetector.xml succesfully parsed with TinyXML .....
PluginService    ERROR Factory requested: lccdd_XML_reader (N10__cxxabiv120__function_type_infoE) :bad any_cast
PluginService    ERROR Stub is invalid!

 *** Break *** segmentation violation
'''

**Comment by paulgessinger** [comment]
I think this is related to DD4hep not finding it's main `lccdd` plugin. Did you source the DD4hep install?

**Comment by rubihason** [comment]
yes, you right now its working. 
Thank you!
