### ISSUE TITLE
Update of calibrate measurement size should become internal to the MTJ backend

### ISSUE THREAD

**Issue by tboldagh** [acts-project/acts#1743]
In the MTJ implementation we have such line:
https://github.com/acts-project/acts/blob/5cab50d75dc892b31fb76a45e230c41f66e8429d/Core/include/Acts/EventData/MultiTrajectory.hpp#L931

This sets the size of the calibrated measurement. However with different backend (xAOD in ATLAS) we do not need this extra size as the data is kept in vector<vector<scalar>> and the size is known. We can add a fictional method to update the size but 
it seems that we can eliminate this method:
https://github.com/acts-project/acts/blob/5cab50d75dc892b31fb76a45e230c41f66e8429d/Core/include/Acts/EventData/MultiTrajectory.hpp#L888
and let the allocateCallibrated to handle this update. 

Tagging @paulgessinger 
and for info @CarloVarni Marcin Wolter

**Comment by paulgessinger** [comment]
So you would make `calibratedSize` to be purely read-only?

**Comment by tboldagh** [comment]
That was quick. Thanks. There may be another small issue here. The calibratedSize is now using "component" to get to the actual size. In ATLAS xAOD implementation this would require that we somehow get the pointer to the vector size property. Not sure if that is doable. Not sure how to best solve it. Duplicating this information in the vector & in mesdim variable seems like asking for trouble.

**Comment by paulgessinger** [comment]
Oh that's a good point I didn't consider yet. I suppose we could instead special case the `calibratedSize` call to either call a fixed function, or change the component function to return that by value and not as a pointer.

**Comment by tboldagh** [comment]
We can indeed specialise it! Nonissue then.

**Comment by paulgessinger** [comment]
No I believe you're right than in the current implementation it tries to cast it to a pointer, which will break if the backend passes the size by value. So I think some form of fix is still needed.
