### ISSUE TITLE
Get number of shared hits on a track

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#175]
Info of whether a hit is shared or not could be helpful to evaluate the quality of a track. In CKF, those shared source links have the same storage index (i.e. `iuncalibrated`) which is realized via an explicit copy of the `iuncalibrated` [here](https://github.com/acts-project/acts/blob/master/Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp#L813). But still, we have no way to tell whether a hit on a track is shared before all tracks are found.

Below are some ideas of how to get such information by some changes in `MultTrajectory`:
- Add a `status` (shared or unshared) for the source link storage indices.
- Add a method to set the `status` of the source link storage index (will be called in CKF).
- Add a method to return whether a source link is shared (i.e. whether the `status` of the storage index of this source link is shared).

**Comment by XiaocongAi** [comment]
@paulgessinger  What do you think? Does that sound something which could be implemented without complicating the `MultiTrajectory` too much to you? Please feel free to edit the issue if you have better idea.

**Comment by paulgessinger** [comment]
I'll think about this.

**Comment by msmk0** [comment]
@XiaocongAi I have a clarification question: do you want to know the shared status within just the `MultiTrajectory` or within the whole event.

In the latter case, you would have to make sure that multiple threads can access this information since we want to be thread-safe. So you need either atomic operations or some locking. Even with the technical problems solved, the track finding probably becomes unpredictable. Imagine e.g. you have a cut on the number of allowed shared hits: this now depends on the order in which multiple threads update the information.

In the former case, you would not have worry about multi-threading. However, now the track finding depends on the order of your initial seeds if you have hit-count dependent cuts.

My suggestion would be to not have this information as part of the `MultiTrajectory`. Instead, I would suggest this is handled independently. Instead of modifying the `MultiTrajectory` I would propose a separate algorithm that takes all the `MultiTrajectory`'s after reconstruction and then computes the shared hit count taking all trajectories into account.

**Comment by XiaocongAi** [comment]
@msmk0 , that's a very good point! Thank you.

Originally, I was thinking to get the shared status within the whole event. But with a second thought, I realize the problem is more complicated than I thought. The shared status might be even impossible via the `MultiTrajectory` since a `MultiTrajectory` keeps info of track states from just one seed. 

So I agree that it's better to get this info after reco. But currently, I really have no idea how to check if a hit is shared or not.

**Comment by paulgessinger** [comment]
On another note, in principle one could use on singe MJ for the entire event, rather than for a single seed.

**Comment by XiaocongAi** [comment]
@paulgessinger , in principle, yes. But that seems to be non-trivial for the `MultiTrajectory`. Does the `MultiTrajectory` already support multiple (i.e. thousands of)  'first mother'? I assume this might be difficult for the storage indices management, but not sure.

**Comment by paulgessinger** [comment]
Well in principle it can have an arbitrary number of mother track states, any TS that has SIZE_MAX parent is considered a mother. If you have a reasonable estimate what the total number of track states will be, you could reserve ahead of time. That could be relatively efficient even I could imagine.

**Comment by XiaocongAi** [comment]
Suppose we have a `MultiTrajectory` for the whole events, all track states on this `MultiTrajectory` should have different storage index, right? If yes, for mothers with SIZE_MAX, when adding track states to them, we should make sure the index of the added tracks will not start from 1 (or 0?). Otherwise, there could be many track states with the same indices.

**Comment by paulgessinger** [comment]
The added track states all get their own indices. Suppose you have two seeds, that means you have two seed track states with `iprevious = SIZE_MAX`, and their indices are `0` and `1`. No suppose both of these seeds generate two additional track states. They can safely have their `iprevious` set to `0` and `1` respectively. In the end, as long as you group the track tip indices, or entry indices correctly, it shouldn't matter which seed track state they come from. In the end, the navigation only happens backwards. Does that make sense?

**Comment by XiaocongAi** [comment]
I see. So the seed track states will have different indices. That makes much sense!

**Comment by XiaocongAi** [comment]
If we take the approach as discussed above, then one  CKF `findTracks` invocation will take all seeds as the inputs.  And there will only one `propagate` invocation as  well (in order to make the propagator carry the CKF result along). Not sure if the propagator will be happy for this marathon.

**Comment by paulgessinger** [comment]
I think it could still be called with individual seeds. The ordering shouldn’t really matter.

**Comment by XiaocongAi** [comment]
But each `propagate` will try to initialize the `result`, no?

**Comment by msmk0** [comment]
> On another note, in principle one could use on singe MJ for the entire event, rather than for a single seed.

That is an interesting idea. You would still need to be able to handle multiple `MultiTrajectory`s for the case where you split the track search over multiple threads, e.g. with multiple quandrants.

On the implementation side I would really prefer I this could be done in a separate function or algorithm. Just to avoid overloading the `MultiTrajectory` interface and retain its initial idea of being just a *dumb* container.
