### ISSUE TITLE
perigee of bound track parameter

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1776]
Hello, 
The class BoundTrackParameters uses six parameters.  I saw that the first and the second (d0/loc0,z0/loc1) parameters are relative to the perigee point. 
My question is this a perigee to the beam spot? Or something else? 
I would be happy to hear more details about it.

**Comment by asalzburger** [comment]
ACTS implements a model where `BoundTrackParameter` are always expressed to a reference surface.
If this surface is a `PerigeeSurface`, i.e. a line that represents the beam line or the global z-Axis or whatever reference axis you have chosen, then indeed the first local parameters are `d0` and `z0`.

If your surface is a plane surface, e.g. if you're track parameterisation is for a planar measurement sensor, then the first local coordinates are `l0`, `l1` in the cartesian frame of the planar surface. If it's a disc surface, it's polar ...

**Comment by rubihason** [comment]
Just to make sure, i asked it because I took information about the vertex and the track from AMVF  algorithm. I also saw that in the include file: "Acts/Surfaces/PerigeeSurface.hpp".
That means that my surface is PerigeeSurface so the track parameterization is loc0=d0 and loc1=z0?

**Comment by asalzburger** [comment]
That is correct.
