### ISSUE TITLE
Import OBJ writing infrastructure into Core

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#18]
[GitLab issue: #700](https://gitlab.cern.ch/acts/acts-core/issues/700)

The classes to write `.obj` files representing `surfaces`, `vertices` and `trajectories` is independent of any framework technology.

It should go into `Plugins/Obj` to be used directly.

The framework versions should then use the writer module.

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2020-02-05 16:05:23](https://gitlab.cern.ch/acts/acts-core/issues/700#note_3167481)

 Actually `Core/Utilities` does have already some functionality in the `ObjHelper`.

This should be updated.

**Comment by asalzburger** [comment]
This is closed, the `Core/Utilities` (after being moved to `Visualisation`) should be used for this.
