### ISSUE TITLE
Track projection to spheres

### ISSUE THREAD

**Issue by c-dilks** [acts-project/acts#1822]
We are trying to figure out a way to project tracks to a spherical surface.

Our sphere is defined as a DD4hep `Sphere`, with typical `theta` and `phi` ranges, but we use Boolean intersections to cut away more parts of the sphere. We make 6 of these spheres, and position them as azimuthal sectors in the back of the detector envelope; this is a RICH detector and the spheres are mirrors, designed to reflect Cherenkov photons to sensors.

The following figure shows the spherical mirrors (dark grey) in the RICH volume (green); tracks enter the RICH volume from the left.

![2023-02-02-122456_281x569_scrot](https://user-images.githubusercontent.com/7843751/216397979-81f73bf4-9eb5-4e03-8199-58adf85ff2cd.png)

We want to be able to project charged particle tracks (identified by track reconstruction from upstream tracker subsystems) onto the spherical mirrors, so that we can analytically determine where to expect the reflected Cherenkov photons. If we have a track point on the spherical surface, we know its position and momentum direction and can therefore calculate the reflected optics.

We've had some internal discussions how to proceed and have a few ideas:

- Make a new `Surface`-derived class for spheres; this would give us a sphere to project to, but does not handle the Boolean cuts (which will soon be more complicated than the above figure shows)
- Triangulate the sphere, such that each triangle is a planar surface; will this perform well if we need a high-resolution triangulation? We would also need a triangulation algorithm, if none exists yet
- Alternative approach: we already project tracks to disc surfaces throughout the RICH volume, so that we know the charged particle path. We could try projecting to discs near the spherical mirrors and binary search to find a point that is close enough to the sphere surface. This is the easiest option for us given what we know how to do, but is restricted in application since it will only work for our RICH.

**Comment by asalzburger** [comment]
So far we have not had a case for spherical surfaces, but I think in this case I would suggest to to create a new `SphereSurface` derived class.

I was planning to have a future `TriangulatedSurface` as you suggest, but not so much for actually measurements where you need to be very precise, but for inert material objects, such as e.g. magnetic coils or support structures where the interesting part is more a generic inclusion of the material into the track fit.

Hence, I suggest we introduce a `SphereSurface` first and follow up on the triangulated surface later. Do you need help/advice on the first part?

**Comment by asalzburger** [comment]
Concerning surfaces with `boolean` operations, in ATLAS, where the original ACTS has its origin, we had a dedicated 'SubtractedSurrface` class, but if we re-implement that I would rather extend the functionality with a `BooleanSurface` class that has some basic operations, but eventually acts like a `Surface` through the same API.

**Comment by paulgessinger** [comment]
I think we should be very careful adding boolean surfaces. I'm a bit worried this can explode complexity significantly.

**Comment by asalzburger** [comment]
Yes, that's the reason why they were not transcribed at first place - anyway, in this case here we can tackle that with appropriate bounds, I suppose.

**Comment by paulgessinger** [comment]
Hey @c-dilks, is this something you're still interested in?

**Comment by c-dilks** [comment]
Closing here, since work is ongoing with our "dRICH specific alternate approach".
