### ISSUE TITLE
Athena compilation with Acts v23 tag: undefined symbol: _ZTVN4Acts22GeometryIdentifierHookE

### ISSUE THREAD

**Issue by CarloVarni** [acts-project/acts#1829]
Bumping Tag `v23.X.Y` in Athena showed the following compilation issue.
```console
ERROR: failed to load libActsTrkFindingTool.so: /afs/cern.ch/user/c/cvarni/work/ACTS/BumpTag23/build/x86_64-centos7-gcc11-opt/lib/libActsGeometryLib.so: undefined symbol: _ZTVN4Acts22GeometryIdentifierHookE
```

This is observed when trying to compile the `ActsGeometry` package in Athena.

This problem has been bypassed by moving the implementation of the `decorateIdentifier` method from https://github.com/acts-project/acts/blob/main/Core/src/Geometry/GeometryIdentifier.cpp to https://github.com/acts-project/acts/blob/v23.1.0/Core/include/Acts/Geometry/GeometryIdentifier.hpp 

See https://github.com/acts-project/acts/pull/1828 for a quick bypass in order to support the Tag Bump in Athena

I'm afraid this is a symptom of a bigger issue in the Acts CMake configuration

**Comment by CarloVarni** [comment]
[ActsGeometrySo.zip](https://github.com/acts-project/acts/files/10661815/ActsGeometrySo.zip)

**Comment by andiwand** [comment]
when I demangle this symbol I get the following

```
$ c++filt _ZTVN4Acts22GeometryIdentifierHookE
vtable for Acts::GeometryIdentifierHook
```

which does not make a lot of sense

**Comment by CarloVarni** [comment]
It looks like this was a problem on how we set a custom Acts tag in Athena. So, not a problem from the Acts side. 
We'd need to update the documentation on the atlas twiki.

Closing this
