### ISSUE TITLE
Bug: last material interaction missing in validation output?

### ISSUE THREAD

**Issue by noemina** [acts-project/acts#1882]
While mapping the material on the ITk tracking geometry (using the standalone workflow), I have seen that the material interaction for the outer boundary seems not to be collected in the root file. 
Things I have already tested:
- I checked that the mapping procedure hit the boundary layers I am selecting in the json file (I see the material indeed appearing in the mapping file)
- I also run the navigation in verbose mode to check that the same boundaries I map the material onto are hit 

I start believing that the last material interaction is simply not saved in the output file of the material validation job?

@Corentin-Allaire, could you help me with this?

**Comment by noemina** [comment]
![material_comparison](https://user-images.githubusercontent.com/58694235/220409190-c2be4312-d326-4ff9-be94-1cc94ed3d033.png)

**Comment by Corentin-Allaire** [comment]
I can have a look at the writing in the validation tomorrow. I will let you know. But we agree it only affect the validation and not the performance right ?

**Comment by Corentin-Allaire** [comment]
So looking at `MaterialInteractor` I notice the following lines (61-64) :
```
    // If we are on target, everything should have been done
    if (state.navigation.targetReached) {
      return;
    }
``` 
It seem we do not perform the material interaction on the target surface. In a way this makes sense as it doesn't matter for the propagation but to get proper validation plots maybe we should change it to : 
 ```
    // If we are on target, everything should have been done
    if (state.navigation.targetReached && !recordInteractions) {
      return;
    }
```
That way we would record material even on the target surface.
Let me know if that fixes your issue.

**Comment by Corentin-Allaire** [comment]
@asalzburger I am pretty sure that the split factor even if it exit is not used anywhere right now. But if we where to properly implement it everywhere you are right that it would make sense

**Comment by noemina** [comment]
Hello @Corentin-Allaire , I have tested your suggestion this morning, but unfortunately the last material interaction is still missing. :(

**Comment by Corentin-Allaire** [comment]
Hi @noemina, so I am a bit at a loss at this point. The propagator action should happen before the aborter so I don't understand why we don't go through the `MaterialInteractor`... If you have the time at some point could you add a cout statement to the `MaterialInteractor` (for example one that print the surface ID) just to be sure if the issue is that we don't record the material or if it is that we don't write it to file properly ?

**Comment by Corentin-Allaire** [comment]
Never mind my last message, we don't do the interaction because else we would print the energy loss and we don't.

**Comment by noemina** [comment]
After some investigation, I found the reason of this issue. It is now fixed. 

![material_comparison](https://user-images.githubusercontent.com/58694235/226305878-b3623a09-91c2-4aa8-b2ec-b2bb8c43126b.png)
