### ISSUE TITLE
suppress TGeoITkModuleSplitter INFO

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#1975]
When running `full_chain_itk.py`, `TGeoITkModuleSplitter` generates 17888 `INFO` messages like:
```
TGeoITkModul INFO Splitting disc node av_53192_impr_1_ITkStrip__ECSensor0_pv_0_ECSensor00x33a48f50 using split ranges of category EC0
```
`itk.py`'s `buildITkGeometry` sets the default `logLevel=acts.logging.WARNING`, but this doesn't seem to suppress these `TGeoITkModuleSplitter` messages. Can we pass the `logLevel` on, as we do with `TGeoDetector.create(surfaceLogLevel, layerLogLevel, volumeLogLevel)`?

17888 messages is too many!

**Comment by Corentin-Allaire** [comment]
The issue is probably here : https://github.com/acts-project/acts/blob/1b6362688367682dadb8e449c26ac65bb950b2be/Examples/Detectors/TGeoDetector/src/TGeoDetector.cpp#L122 we don't propagate the TGeo log level to the splitter log level

**Comment by andiwand** [comment]
hey @timadye ! the fixes from @goetzgaycken are merged now - can you confirm that the problem disappeared?

**Comment by timadye** [comment]
> hey @timadye ! the fixes from @goetzgaycken are merged now - can you confirm that the problem disappeared?

Yes, the messages are gone now. Thanks, @goetzgaycken!
