### ISSUE TITLE
Issue with track.nMeasurements() in CKF tracks

### ISSUE THREAD

**Issue by pbutti** [acts-project/acts#1999]
When calling track.nMeasurements() on tracks reconstructed with the CKF, the return value is always 0. 
@paulgessinger checked and confirmed that CKF doesn't fill this correctly (While KF and other fitters seem like they do)

**Comment by paulgessinger** [comment]
So I guess the CKF should probably also loop over its tracks and calculate it.

**Comment by pbutti** [comment]
@paulgessinger will you take care? Alternatively you can point me to the relevant parts and I can take care of this. Also, perhaps we could add chi2sum ndf to the TrackProxy?

**Comment by paulgessinger** [comment]
I'll add it!
