### ISSUE TITLE
Running ACTS FW FittingAlgorithms in parallel env brings no performance improvement

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#20]
[GitLab issue: #690](https://gitlab.cern.ch/acts/acts-core/issues/690)

Intel TBB library is used to parallelise the main loop in ACTS FW FittingAlgorithm.cpp.

Observations:

1.  The number of TBB threads can only be configured once (when the TBB scheduler is first initialised). Later or local configurations are ignored (unlike OpenMP or UNIX Pthreads). 
2.  Since the Sequencer already uses as many threads as physical cores, looks like the processor is already busy full-time, so a later parallelisation seems to be useless.
3.  The parallel threads in Sequencer do not need any synchronisation due to data independence. The threads in Fitter need to synchronise on the output result: the trajectories. Therefore having the parallelisation done only here would not be so beneficial as having it in Sequencer. 

See attached PDF with time measurements which seems to support the above observations: [TBBFittingParallelExecutionTimes.pdf](/uploads/ffda04d5b106be22f19e06fb7d227c0f/TBBFittingParallelExecutionTimes.pdf)

Code is committed in ACTSFW/parallel-fitter branch.

**Comment by paulgessinger** [comment]
[Original comment by: hgraslan at 2020-01-24 16:38:08](https://gitlab.cern.ch/acts/acts-core/issues/690#note_3137248)

 May I suggest also recording the RAM footprint of the various jobs? I would intuitively expect an intra-event parallelization scheme to perform better than an inter-event one from this perspective, but it would be interesting to quantify this benefit, and see whether it's worth the loss of execution efficiency.

**Comment by paulgessinger** [comment]
[Original comment by: gmania at 2020-01-24 16:41:37](https://gitlab.cern.ch/acts/acts-core/issues/690#note_3137268)

 Yes, of course. I will re-run the tests on a more powerful machine and I will record both execution time and memory footprint.

**Comment by msmk0** [comment]
@paulgessinger @asalzburger I would suggest we close this for now.
