### ISSUE TITLE
ACTS compilation failure with gcc13

### ISSUE THREAD

**Issue by elmsheus** [acts-project/acts#2040]
Hi,

as discussed by email, I've tried to build AthenaExternals (uses ACTS v24.0.0) with a locally complied gcc13 pre-release version on an AlmaLinux9/GCP host. The final version of gcc 13.1.0 should be released next week or so. 

There are ACTS build failure in:
Acts/Core/include/Acts/EventData/TrackStatePropMask.hpp
Acts/Core/include/Acts/Utilities/EnumBitwiseOperators.hpp

My naive suspicion is that a simple "#include \<cstdint\>" might be missing for the definition of uint8_t.

The full AthenaExternals build log is at: /afs/cern.ch/user/e/elmsheus/public/acts/external.log 

Cheers, Johannes

**Comment by paulgessinger** [comment]
Thanks! For reference, see also #2054
