### ISSUE TITLE
ParticleID collision in Geant4

### ISSUE THREAD

**Issue by Corentin-Allaire** [acts-project/acts#2041]
We have noticed that the particles' barcode of the Geant 4 simulation can (and does) overlap during simulation. This means that many for a given track ID, we can have the hits corresponding to many simulated tracks associated. For now, we believe that if the standard particle selection is applied, this effect should be negligible (as it mainly affects the secondary), but this should be tested.

@benjaminhuth and @andiwand are looking into modifying the barcode information stored in the G4 simulation to avoid such overlap. For now, those barcodes are directly inherited from the Fatras simulation and might not be appropriate when used in G4.

@benjaminhuth has also opened a PR related to this issue: #2039.

**Comment by andiwand** [comment]
what I got from the code is that `EventGeneration` will only use the primary vertex ID, `Pythia` will only use the secondary vertex ID and `Geant4` will only use the particle generation

from the code and discussions I understand the barcode in the following way
- `primary vertex` is simply the primary vertex ID, no ambiguity here
- `secondary vertex` is the secondary vertex ID. this could come from event gen but also from simulation. we have to be careful if both of them touch this information
- `particle` is the particle ID within that primary and secondary vertex
- `generation` is used for everything after primary and secondary
- `sub particle` identifies the particle within each generation

this is even more complicated that I thought. the secondary vertex part should only be used for the secondaries and not tertiaries

**Comment by Corentin-Allaire** [comment]
Maybe I am missing something but in the G4 case shouldn't the `sub particle` value be different for all particles then ?

**Comment by benjaminhuth** [comment]
Hmm I don't think so. It should be just different within one generation, right?

**Comment by Corentin-Allaire** [comment]
Ah yes you are right I think I see it now !

**Comment by Corentin-Allaire** [comment]
Resolved by  #2039
