### ISSUE TITLE
Debugging the propagation integration test is painful

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#21]
[GitLab issue: #687](https://gitlab.cern.ch/acts/acts-core/issues/687)

The `PropagationIntegrationTest` does a lot of work. Its execution time is somewhat reasonable in "release" `-O2` builds, at around a minute here, but that degrades into a painful extreme of 2 hours and a half when run on "debug" `-O0` builds, which if the usual 30x orders of magnitude apply means that it would typically take several days to run such a build under a valgrind tool (memcheck, verrou...).

I personally find this a bit concerning, because some bugs are hard to track down on a release builds, even with debugging symbols on. But maybe I'm overreacting an others don't think that this is a problem?

If we do agree that this is a problem, how do we want to approach it? Here are some tentative ideas:

- Break the test down into multiple sub-programs.
- Evaluate wisdom of tuning down iteration count in long-running parts.
- If that loses coverage/physics, then consider allowing the caller of the test to execute or replay only a subset of it (e.g. "re-run iterations 10000 to 10100").

**Comment by HadrienG2** [comment]
AFAIK this is still an issue. It would be great if an author/contributor of these tests could chime in and comment on whether the extremely long running time is necessary for the test to do its intended job, or just a tuning parameter (e.g. number of simulated tracks) that we could reasonably envision adjusting.

**Comment by paulgessinger** [comment]
I thought this was simply because our code is just slow in non optimized builds. Even if you tune down the numbers, it will still be terribly slow.

**Comment by HadrienG2** [comment]
There are various degrees of "terribly slow" though. Valgrind runtimes of a few minutes (corresponding to optimized runtimes of a few seconds) are something that can totally be lived with, whereas runtimes of a few days are too much for reasonable debugging iterations.

Ways to improve this range from tuning down numbers of loop iterations (or just making them externally configurable for those who need) to breaking this rather complex test which tests a lot of different things into multiple smaller tests.

**Comment by msmk0** [comment]
@HadrienG2 Do you think you could find so time to check whether #373 helped?

**Comment by HadrienG2** [comment]
Sure, I intend to cross-check that in the coming days along with rebasing my dev branches.

**Comment by msmk0** [comment]
@HadrienG2 Did you find time to check if it works better now?

**Comment by HadrienG2** [comment]
To paraphrase mattermost discussion: I have a debug build of it that crashes on an assertion, now I need to get that sorted out and after that I can check running times. Should be done this afternoon unless unexpected stuff happens.

**Comment by msmk0** [comment]
I think I now why the assertions appear. If its okay for you, I will propose a PR for that.

**Comment by HadrienG2** [comment]
So, current execution times in Debug builds are...

- CompareEigenStraightLine: 0.6s
- CompareAtlasEigenConstant: 13s
- StraightLine: 2m15s
- AtlasConstant: 3m3s
- EigenConstant: 11m41s
- DenseConstant: 80m27s

Of those, I would consider the DenseConstant integration test to remain hard to debug, with the others being workable (though if you need a valgrind run, it will definitely take a few hours to run through on the multi-minute ones...).

**Comment by paulgessinger** [comment]
80 minutes for a single compilation unit??? 😮

**Comment by HadrienG2** [comment]
These are execution times ;)

**Comment by HadrienG2** [comment]
In case you're curious how that translates into Valgrind-instrumented execution times, I started a couple of runs on my laptop on Friday evening and they finished last night.

- CompareEigenStraightLine: 24s (40x slower)
- CompareAtlasEigenconstant: 8m47s (41x slower)
- StraightLine: 87m9s (39x slower)
- AtlasConstant: 159m13s (52x slower)
- EigenConstant: 520m4s (45x slower)
- DenseConstant: 3992m1s (49x slower)

So the 30x order of magnitude that I remembered for the valgrind-induced slowdown was a bit optimistic, it's more like a 40-50x slowdown in practice. Anyway, hopefully that can give you an idea of how painful it is to run Valgrind-based tools on these various integration tests!

- Totally livable up to the StraightLine tests
- AtlasConstant gets into the "annoying" teritory, but I can still start valgrind before lunch and get the results at the end
- EigenConstant gets into the "very annoying" territory, I need two consecutive days to start valgrind and get the results.
- If I find a problem in DenseConstant, it will be faster to debug it manually via print statement than to use debugging tools on it. It is already too slow for interactive debugging via GDB, and several days of running time under Valgrind is too much for that tool to be useful as well.

**Comment by msmk0** [comment]
To summarize: we are still deep in the *painful-to-debug* region for the majority of the integration tests.

At the moment I do not see how this can be fixed in the integration tests alone. They are now already split into multiple parts and the parameter space has been reduced. Reducing the runtime will require cleanup/ simplification in the code itself.

We can either leave this as a long-term issue or close it for now as there is no immediate action possible. My preferences is on the later.

**Comment by paulgessinger** [comment]
Are we even sure we can fix this? I'm not really surprised that a Debug build is **a lot** slower than a Release build.

**Comment by msmk0** [comment]
You could still reduce the parameter space. That should be ok if you do that locally for your own debug build. I do not want to reduce it further for the regular tests, since it is important that we actually test all the parameter space that we expect to see in an experiment.

So no, I do not think that we can easily fix this. Thus my preference to close this issue for now.

**Comment by msmk0** [comment]
There was no further feedback. I will close the issue.
