### ISSUE TITLE
Unnecessary wrapping of VectorMTJ in MTJ

### ISSUE THREAD

**Issue by tboldagh** [acts-project/acts#2150]
In the examples & core part of the library one can meet a filling type declarations:
example from (AlignmentEngine.hpp):
```
const Acts::MultiTrajectory<traj_t>& multiTraj
```
It is essentially wrapping VectorMTJ in MTJ. But this is not necessary, i.e. the VectorMultiTrajectory is already inheriting from Acts::MultiTrajectory so contains all necessary typedefs & methods.

I believe I witness issues because of that when trying to use Atlas MTJ  instead VectorMTJ. 
I can't give my hand for it because error messages due to templates are realy confusing. 
In any case such wrapping is not necessary and could be avoided. 

@paulgessinger @andiwand @timadye

**Comment by paulgessinger** [comment]
I don't think it's actually double wrapping, it's just specifying as what type the reference is held. Your code snippet specifies it to be the base class, and the base class methods will static cast back to the derived class given by CRTP.

So switching this to just `traj_t` should be functionality equivalent, I believe.

**Comment by tboldagh** [comment]
> I don't think it's actually double wrapping, it's just specifying as what type the reference is held. Your code snippet specifies it to be the base class, and the base class methods will static cast back to the derived class given by CRTP.
> 
> So switching this to just `traj_t` should be functionality equivalent, I believe.

So it would be desirable to simplify the code I guess?

**Comment by timadye** [comment]
> So switching this to just `traj_t` should be functionality equivalent, I believe.

Hi @paulgessinger,

Do you mean use `traj_t` in the caller (eg. `VectorMultiTrajectory` in Athena), or replace `Acts::MultiTrajectory<traj_t>` in Acts core?

Thanks,
Tim.

**Comment by tboldagh** [comment]
The first would not work w/o the later. I think we would need first to cleanup ACTS core & examples. And then in the next ACTS version bump in ATLAS also clean things there. 
It should be all technical (model very long compiler messages about templates that need to be understood).
