### ISSUE TITLE
Support multi-output in ONNX plugin

### ISSUE THREAD

**Issue by gagnonlg** [acts-project/acts#2170]
The current implementation of OnnxRuntimeBase assumes single-input & single-output nodes. However multi-output models are increasingly used in practice, for example when training a model with auxiliary objectives. Looking at the code, it should not be extremely hard to generalize our code to support this use-case.

tagging @benjaminhuth @Corentin-Allaire  for thoughts

**Comment by gagnonlg** [comment]
Multi-output was even easier than I thought -- see https://github.com/acts-project/acts/pull/2171. I propose we leave out multi-input for now since such models are less common.

**Comment by benjaminhuth** [comment]
Yeah sounds good to generalize if there is need for this I would say.

The only thought I have on the implementation is the question if everything would be implemented based on `std::vector`s (probably quite easy), or if we do it compiletime based with `std::tuples` and variadic templates to allow maybe nice things like
```c++
model = Model<2,2>;
auto [out1, out2] = model.runONNXInference(in1, in2);
```

But probably overkill...

**Comment by benjaminhuth** [comment]
Oh I just saw the PR after the comment, so the point is obsolete anyways :)

**Comment by gagnonlg** [comment]
That would be a nice implementation if we ever decide we want to support multi input. I propose to start with #2171 for now!

**Comment by Corentin-Allaire** [comment]
I agree this would be a good idea. I can review the PR this afternoon if you want

**Comment by gagnonlg** [comment]
That would be great, @Corentin-Allaire. Thanks a lot!
