### ISSUE TITLE
Indexed Grid Surfaces generator

### ISSUE THREAD

**Issue by dimitra97** [acts-project/acts#2197]
In the `IndexedSurfacesGenerator.hpp` there is the standard navigation delegate `IndexedSurfacesImpl` used. 
I thought about maybe we pass the navigate delegate as `typename` of the` template ` , so someone can use other delegates (e.g the one I am working on where specific indexed surfaces are extracted for the navigation state update).
Does it make a sense? Do you agree? If so, I can try..!
@asalzburger

**Comment by asalzburger** [comment]
This would turn this into a delegate factory ? Fine with me, if it simplifies things. Can you draft how this looks like and we can check?

**Comment by dimitra97** [comment]
> This would turn this into a delegate factory ? Fine with me, if it simplifies things. Can you draft how this looks like and we can check?
Actually I thought about passing the delegate as template argument, but I do not know if it is good to be done like that..
I pushed my thought here
https://github.com/acts-project/acts/pull/2180#pullrequestreview-1483247343
