### ISSUE TITLE
Bug: Combinatorial Kalman filter fails during track finding

### ISSUE THREAD

**Issue by felix-russo** [acts-project/acts#2226]
When running `CI/physmon/workflows/physmon_vertexing.py`, I encountered the following error (see screenshot). I don't know how much of a problem that is, but I wanted to mention it here!
![image](https://github.com/acts-project/acts/assets/72298366/ebee4c1c-68e3-4e63-9f6d-d2fefd288a06)

**Comment by paulgessinger** [comment]
It's definitely something we'll need to follow up.
Could you try to narrow down where exactly this gets triggered? I'm not sure if this could be a navigation failure, because I wouldn't expect this to cause the global position not to end up on surface. Could it be related to the global-to-local changes that @andiwand made recently?

**Comment by andiwand** [comment]
I would think so yeah - it might have the same origin. So that would be another case were we do not properly propagate back to the perigee and the line surface was happy with that before my change

**Comment by felix-russo** [comment]
When executing `physmon_ckf_tracking.py`, I saw the same error message.

This gets triggered in the function `globalToLocal` in `Linesurface.cpp`!

**Comment by paulgessinger** [comment]
@asalzburger mentions that in case there's an RK step in-between the creation of the parameters and the global to local, a slightly changed momentum could affect if the parameters are on surface or not.

**Comment by andiwand** [comment]
this is what I tried to quick fix here https://github.com/acts-project/acts/pull/2239

**Comment by paulgessinger** [comment]
@felix-russo can you verify that you see this as fixed on your end?

**Comment by felix-russo** [comment]
@paulgessinger all working!
