### ISSUE TITLE
Bug: Negative variances from AMVF

### ISSUE THREAD

**Issue by felix-russo** [acts-project/acts#2231]
When running `CI/physmon/workflows/physmon_vertexing.py`, I encountered the following error (see screenshot): The variance of the fitted vertex from the AMVF is sometimes negative (the variance from the IVF is fine). 

When running `CI/physmon/workflows/physmon_vertexing.py` with the code from PR #2221, I find that the variance of the track parameters from the AMVF is also not always positive. 

![image](https://github.com/acts-project/acts/assets/72298366/679560f5-311f-4e47-b275-7b90e4c09793)

**Comment by paulgessinger** [comment]
- Does the linearizer cause this? It probably shouldn't as its analytical
- Are these the weights where the combination is not guaranteed to be positive
- Covariances are being subtracted, there might be a bug with the math
- Could be tracks and vertices which are not inside linear regime and resulting uncertainties are broken

**Comment by felix-russo** [comment]
Once this is resolved, we need to revert #2374

**Comment by andiwand** [comment]
I don't think we have to revert it but we should assert on that or `ACTS_ERROR` on it

**Comment by felix-russo** [comment]
Ah sorry, that's right (what we had before #2374 was obviously not good)
