### ISSUE TITLE
Set default CMake build type if none is given

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#228]
Without an explicit build type, CMake does not add any additional build flags. This will result in a default build without any optimizations and without any debug symbols, i.e. the worst compatible solution.

If no explicit build type is given, the build configuration should select a default one. The proposal would be to use `Release` by default.

_Originally posted by @msmk0 in https://github.com/acts-project/acts/pull/223/review_comment/create_

**Comment by HadrienG2** [comment]
I agree with the idea of setting a better default, but would propose `RelWithDebInfo` instead.

The advantage wrt `Release` is that one doesn't need to restart the full Acts build when some profiling or light debugging. The drawback is that a few gigabytes of extra disk space are needed.

**Comment by msmk0** [comment]
Good point. `RelWithDebInfo` should work just as well.

**Comment by msmk0** [comment]
This was fixed in #254.
