### ISSUE TITLE
JSON read failure in ATLAS debug build

### ISSUE THREAD

**Issue by scott-snyder** [acts-project/acts#2331]
In the ATLAS debug build, we're getting failures in the ActsEventCnv test:

```
ActsTrackingGeometrySvc                             FATAL in sysInitialize(): standard std::exception is caught
ActsTrackingGeometrySvc                             ERROR [json.exception.type_error.302] type must be number, but is string
ServiceManager                                      ERROR Unable to initialize service "ActsTrackingGeometrySvc"
```

This is because some compilation units in Plugins/Json try to convert
a BinningValue without including the header UtilitiesJsonConverter.hpp
which has the NLOHMANN_JSON_SERIALIZE_ENUM declaration for BinningValue.
Thus, the conversion can work differently depending on the compilation unit,
and the behavior can also depend on what gets inlined, so can differ
between the optimized and debug build.

The includes are missing from IndexedSurfacesJsonConverter.cpp and PortalJsonConverter.cpp.
The commit here fixes this crash in the ATLAS build:

https://github.com/scott-snyder/acts/commit/9e19d925ecafc881e2259e2e624ad55194553107

(Not submitted directly as a PR since the formatting CI checks want to remove these headers again?  Maybe because they're not directly used?)

**Comment by paulgessinger** [comment]
This is an annoying weakness using extra includes like this.

Thanks for the fix @scott-snyder!
