### ISSUE TITLE
Import the Z vertex finder from space points

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#24]
[GitLab issue: #683](https://gitlab.cern.ch/acts/acts-core/issues/683)

There is a simple algorithm based on Hans Drevermann's z vertex finder which already has been transcribed into `acts-core`. The code is already written and needs only to be cleaned up.

It takes combinations of spacepoints and extrapolates them to the beam line in order to histogram vertices, see attached sample plot for a test event:

![Unknown](/uploads/96d4ea0113150f108fa869907ddd9009/Unknown.png)

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-12-16 09:32:33](https://gitlab.cern.ch/acts/acts-core/issues/683#note_3068920)

 `UnitTest` of this is in `SpacePointVertexFinderTests` running on a four cylinder layer detector.

![Unknown](/uploads/507936832b14148a1dd51b2bb3f00e73/Unknown.png)

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-12-18 13:40:49](https://gitlab.cern.ch/acts/acts-core/issues/683#note_3076344)

 This MR will only work with `BOOST>1.70` as it uses `boost::histogram`

**Comment by msmk0** [comment]
@asalzburger @baschlag Is this still relevant or should we close it?

**Comment by baschlag** [comment]
> @asalzburger @baschlag Is this still relevant or should we close it?

I have not seen this before, maybe we should ask @paulgessinger?

**Comment by paulgessinger** [comment]
@asalzburger opened this, I only did the migration from Gitlab.
