### ISSUE TITLE
Feature - save covariance matrix of fitted tracks

### ISSUE THREAD

**Issue by owtscharenko** [acts-project/acts#2453]
Hi,
I was wondering whether it is possible, or even planned, to add the covariance matrix of fitted tracks to the respective output files produced by the ROOT IO writers?
Using the ODD example we would like to process the simulated tracks after the CKF with external code where it is necessary to know the full covariance matrix.
So far I hacked something in my fork of acts:
[https://github.com/owtscharenko/acts/tree/vertexSim/Examples/Io/Root/include/ActsExamples/Io/Root](https://github.com/owtscharenko/acts/tree/vertexSim/Examples/Io/Root/include/ActsExamples/Io/Root), but this can for sure be done better.
I just added a `std::vector<TMatrixD>` to the Tree where the covariance matrix is saved in.
This however means that I need to build a dictionary for the struct before compiling acts. The only way I managed to do it was by using rootcint and adding the compiled files to the include directory. 

`rootcint -f vectorMatrix_dict.cxx -c RootTrajectorySummaryWriter.hpp LinkDef.h -I/home/niko/git/acts/Core/include/ -I/home/niko/anaconda3/envs/acts/include/eigen3/ -I/home/niko/git/acts/Examples/Framework/include/ -I/home/niko/git/acts/Fatras/include/ -I/home/niko/git/acts/Plugins/FpeMonitoring/include/`

If this feature is wanted and there are suggestions of how to include generation of the dictionary in cmake, I am happy to try it.

Regards

**Comment by paulgessinger** [comment]
Hey @owtscharenko,
that's an interesting idea. We didn't intend these outputs to be super complete let's say, so we only write what we think we need for validation and testing.
Anyway, we're happy to add this kind of info to the output if that's helpful for you.

If we can at all avoid it, these ROOT output files should not require dictionaries, mostly so they're easier to use. However, it should be possible to just write the contents of the covariance matrices as `std::vector<double>` and then re-interpret them in the downstream software. This is trivial in Eigen, and likely also possible with `TMatrixD`.

What do you think?

**Comment by owtscharenko** [comment]
Sure it is possible to choose some other container. For the downstream code it should not make too much of a difference.
I chose the 6x6 TMatrixD to avoid writing 36 leaves of std::vector<double> to the tree in order to not clutter it too much. 
But it makes sense to keep it simple and to avoid dictionaries.
I can prepare a PR with the simple data type, without dictionaries. However I do not yet know how to make it optional, i.e. how to pass a switch "wirte_covmat" from the python script to the C++ class.

**Comment by paulgessinger** [comment]
You can simply add a boolean flag to `RootTrajectorySummaryWriter::Config`, and then expose it in the python binding code:

https://github.com/acts-project/acts/blob/fb15929969a466178caff1dc7d09cb16eaf707ef/Examples/Python/src/Output.cpp#L326-L329

Then, you can just use a keyword-argument in when creating the object in python.
