### ISSUE TITLE
MT::hasReferenceSurface() throws an exception if there is no surface

### ISSUE THREAD

**Issue by EdwardMoyse** [acts-project/acts#2456]
In ATLAS I tried the following in a unit test:
```cpp
  BOOST_CHECK(!ts.hasReferenceSurface());
  ts.setReferenceSurface(pc.predicted.referenceSurface().getSharedPtr());
```
This throws an exception. This is because `TrackStateProxy` does the following:
[    return m_traj->referenceSurface(m_istate) != nullptr;](https://github.com/acts-project/acts/blob/f7e9f231b5248b043d899c6995714128337a57a4/Core/include/Acts/EventData/MultiTrajectory.hpp#L412)

i.e. it blindly calls `referenceSurface` which in turn calls `referenceSurface_impl`, which for ACTS has the following:
```cpp
  const Surface* referenceSurface_impl(IndexType istate) const {
    return m_referenceSurfaces[istate].get();
  }
```
(ATLAS has a [similar ](https://gitlab.cern.ch/atlas/athena/-/blob/main/Tracking/Acts/ActsEvent/Root/MultiTrajectory.cxx#L346) implementation:).

IMO the solution is to check the size and return `nullptr` in  `referenceSurface_impl` if `istate` is too large?

(Incidentally I do not seem to be able to edit labels etc)

**Comment by paulgessinger** [comment]
Likely the problem is that it's incorrectly trying to dereference an empty shared_ptr which is not well-defined.

**Comment by paulgessinger** [comment]
It seems to me like this is not a problem in the transient vector backend, as we allocate an empty `shared_ptr` which correctly returns `nullptr` on `.get()` if it's empty.

**Comment by EdwardMoyse** [comment]
Can confirm that this was a problem specific to the ATLAS implementation, see: 
https://gitlab.cern.ch/atlas/athena/-/merge_requests/66279

Apologies for the noise!
