### ISSUE TITLE
RootMeasurementWriter does not save angles of incidence

### ISSUE THREAD

**Issue by gagnonlg** [acts-project/acts#2484]
In RootMeasurementWriter.hpp, we have the following function to save truth quantities associated to a measurement:
```cpp   
    /// @param lp The true local position
    /// @param xt The true 4D global position
    /// @param dir The true particle direction

    void fillTruthParameters(const Acts::Vector2& lp, const Acts::Vector4& xt,
                             const Acts::Vector3& dir) {
      trueBound[Acts::eBoundLoc0] = lp[Acts::eBoundLoc0];
      trueBound[Acts::eBoundLoc1] = lp[Acts::eBoundLoc1];
      trueBound[Acts::eBoundPhi] = Acts::VectorHelpers::phi(dir);
      trueBound[Acts::eBoundTheta] = Acts::VectorHelpers::theta(dir);
// ....
```
`lp` is local to a sensor, therefore `loc0` and `loc1` are bound and local to a surface. However, _if I understand the code correctly_, the `dir` vector (given by averageSimHits) encodes the particle direction in the lab frame, therefore those angles are _not_ those at the surface where we have the positition.

Not sure if this is the desired behavior -- I think it would be better to give the angles local to the surface, and possibly also save the global vector additionally (like we do for the position)

**Comment by gagnonlg** [comment]
The same thing is done in TransformationFreeToBound.cpp, so I may have misunderstood what is needed.

What I need is a way to get that direction _from the surface_. Presumably I can do that by fetching the surface's normal vector.

**Comment by gagnonlg** [comment]
I guess they are, and that is what I was misunderstanding -- clearly no problem with that. 

What I would like to get, is the angle of incidence on the surface. It can be different from the direction in the lab frame since a surface can be oriented differently, is it not?

**Comment by gagnonlg** [comment]
I think something like
```cpp
trueBound[Acts::eBoundTheta] - (Acts::VectorHelpers::theta(normal) - M_PI_2)
```
does the trick. I'm leaving the issue open since I'd like to add this to the writer at some point.

**Comment by paulgessinger** [comment]
I think we calculate the incidence angle in a few places already (for path correction of projected material, I believe).

**Comment by gagnonlg** [comment]
I looked up what was done elsewhere but I need something slightly different -- I need the 2 incident along the axes of the local measurement reference frame. I think this does it, but I've yet to test it:
```cpp
std::pair<double, double>
incidentAngles(const Acts::Vector3& direction,
	       const Acts::RotationMatrix3& refFrame)
{
  Acts::Vector3 trfDir = refFrame.dot(direction);
  double angle0 = std::atan2(trfDir[2], trfDir[0]);
  double angle1 = std::atan2(trfDir[2], trfDir[1]);
  return {angle0, angle1}
}
```
Here, `refFrame` would come from `surface.referenceFrame(gctx, ...)`
