### ISSUE TITLE
Missing DD4HepVolumeBuilder.cxx in CMakeList

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#25]
[GitLab issue: #680](https://gitlab.cern.ch/acts/acts-core/issues/680)
Referenced by the following MRs on GitLab: [!721](https://gitlab.cern.ch/acts/acts-core/-/merge_requests/721)

The following discussion from !685 should be addressed:

- [ ] @ asalzbur started a [discussion](https://gitlab.cern.ch/acts/acts-core/merge_requests/685#note_3051959): 

    > The `DD4hepVolumeBuilder` is missing in this, which creates a linking error.

**Comment by paulgessinger** [comment]
Has this been resolved? @asalzburger

**Comment by msmk0** [comment]
I am pretty sure this is fixed. Will close the issue.
