### ISSUE TITLE
Reduce Debug output size w/o disabling components

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#263]
The size of output artifacts in debug mode is too large. This impacts CI jobs as we seem to hit the disk quota (14Gb). #262 disabled some components in the debug build as a stop-gap measure. For a long-term solution we need to find a way to reduce the output size while allowing all components to be built and considered for the coverage.

**Comment by msmk0** [comment]
I played a bit with the [GCC Instrumentation Options](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html) and it looks like we are already using the minimal settings.

**Comment by HadrienG2** [comment]
I would like to propose the counter-hypothesis that we might be running out of RAM, not disk. This hypothesis is motivated by the following arguments:

- In RelWithDebInfo mode, our largest jobs are far above Github runner's RAM limit.
- @paulgessinger tested that the situation is much less dire for Release builds, which suggests that debug info plays a big role in this problem. So in principle, Debug build should be affected too (though that was not tested).
- The initial version of https://github.com/acts-project/acts/pull/315 failed and reducing build concurrency to 1 fixed it, which would not happen if disk space were the issue.

**Comment by paulgessinger** [comment]
Current not pressing anymore. Closing for now.
