### ISSUE TITLE
Component listing in installed CMake config is broken

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#265]
on `find_package(Acts)`, our generated CMake config should list available and enabled components. In Athena I get this output:

```console
-- found Acts version 0.25.1 - 6e8a1ea6d
-- supported components:
-- loading components:
--   - Core
```

/cc @msmk0

**Comment by msmk0** [comment]
I looked into this and this seems to be a reporting issue, i.e. the printing uses a variable that does not exists, but the information is there. I discovered some additional issues with the CMake install configuration and will prepare a PR.
