### ISSUE TITLE
Add example project with Acts as external dependency

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#27]
[GitLab issue: #674](https://gitlab.cern.ch/acts/acts-core/issues/674)

We currently do not test that installed CMake configs work. We should have a small example project that builds a (non-trivial) example executable using Acts via the `find_package(...)` mechanism. This should look as simple as a single directory in the repository:

```
ExampleProject\
ExampleProject\CMakeLists.txt
ExampleProject\Propagate.cpp
```

Having this directly in the repository would allow us to build this in the CI using the installed build products from one of the Core build jobs. In principle, this could also be done as a separate project. Gitlab supports multi-project pipelines but only in the premium edition. This is currently not an option for us.

**Comment by asalzburger** [comment]
I guess this is still an issue even though we have the mono repository now - as this would test client usage, right?

**Comment by paulgessinger** [comment]
Has a PR assigned.
