### ISSUE TITLE
Can we replace MultiTrajectory and FittableMeasurement with an ECS?

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#280]
As discussed in the meeting, I think we could potentially solve storage of our polymorphic measurements, using Entity Component System. Measurements right now are polymorphic in the number of dimensions, which is solved by overallocation. This won't go away with an ECS, however, with the potential addition of volume measurements in #272, there might be an additional variation. This type could be captured well with ECS I think. 

The KF for instance could by a system (S in ECS) that operates on measurements with surfaces. A volume fitter could use the same mechanism to operate on volume measurements. These measurements could be stored in a uniform storage backend, however. Say we also wanted to add a fitter that fits both surface and volume measurements, using such an ECS it could potentially. use the same data structure I think.

We should investigate whether the performance characteristics and ergonomics make sense for us, and whether this would be something we want to try out.

@HadrienG2 made me think of this recently, maybe you have thoughts on this?

**Comment by HadrienG2** [comment]
If I understand correctly the idea would be to have three possible components:

- Measurement data (some kind of matrix)
- Associated surface
- Associated volume

...and then Fitters would be systems which access the measurement data, and either or both of the associated surface/volume component.

Is that correct?

**Comment by paulgessinger** [comment]
That's what I was thinking of at this point, yeah.

**Comment by HadrienG2** [comment]
Am I correct to assume that the reason why you are not envisioning to simply store this as a (Data, Option<SurfaceID>, Option<VolumeID>) triplet is that there will be lots of these around and the storage and runtime processing needs of this simple solution would be unacceptable ?

**Comment by paulgessinger** [comment]
Well, that's what we have right now more or less with `Measurement` and `FittableMeasurement`. `MultiTrajectory` can only handle reference **surfaces** as of now. If the flexibility to add components as needed is not necessary, or if it's too complicated, then `MultiTrajectory` already fits the bill here, I think.

**Comment by HadrienG2** [comment]
Well, I certainly expect an ECS implementation in C++ to be a fair bit of a code complexity investment, either on the user's or the implementation's side depending on how much black magic we add to make it convenient to use. So I want to make sure that we need an ECS enough to justify the complexity budget, and that we don't have any simpler data organization tool at our disposal for the problem at hand.
