### ISSUE TITLE
`LineSurface` jacobians seem incomplete

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#2809]
In the `LineSurface` we define a `boundToFreeJacobian` but not a `freeToBoundJacobian` which seems incorrect to me. If the jacobian is different compared to the one from a plane surface in one direction it should also be the case in the other direction

https://github.com/acts-project/acts/blob/f7106bc1adc803700eef3690f8dc43046c73bb61/Core/include/Acts/Surfaces/LineSurface.hpp#L120-L128

https://github.com/acts-project/acts/blob/f7106bc1adc803700eef3690f8dc43046c73bb61/Core/src/Surfaces/LineSurface.cpp#L198-L249

**Comment by paulgessinger** [comment]
Maybe @beomki-yeo has thoughts on this.

**Comment by beomki-yeo** [comment]
Indeed. I will update my PR on line surface jacobian soon so you can check the details there (#2657)

Summary:
It should not be defined and it's OK not to be defined. J_{G->L} X J_{L->G} is always identical in the current implementation

**Comment by andiwand** [comment]
thanks I will check. still seems odd to me as there should be a correlation between direction error and position error for both transformations

**Comment by beomki-yeo** [comment]
That's a funny behavior of two different transforms - it will be described in the Discussion section. :wink:
