### ISSUE TITLE
Redundancy of bound and curvilinear state

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#2812]
While refactoring the [`CovarianceEngine`](https://github.com/acts-project/acts/blob/main/Core/include/Acts/Propagator/detail/CovarianceEngine.hpp) and the [`JacobianEngine`](https://github.com/acts-project/acts/blob/main/Core/include/Acts/Propagator/detail/JacobianEngine.hpp) I noticed that we duplicate quite some code for handling bound and curvilinear states as they are very similar.

I am not sure if that is based on performance reasons or if this is just grown historically.

In any case I think we could remove the duplication by merging the concept or we could split the curvilinear parameters from the bound parameters which would remove the dependency on a shared pointer surface under the hood.

Ultimately this depends on the performance implications of merging them I guess since this would be the most general and easiest solution IMO.

**Comment by beomki-yeo** [comment]
Curvilinear state is just a special case of bound state where the surface normal vector is direction. 

I suppose we can make our interface smarter with surface normal vector argument. (ex) put a surface normal vector for bound state and put a track direction for curvilinear state)

**Comment by paulgessinger** [comment]
Just want to add that in curvilinear the plane rotation around the normal is also fixed.

**Comment by andiwand** [comment]
After having a deeper look at this it seems to me that this is an optimization step. We are basically doing the same math but with less expressions in case of the curvilinear surface.
