### ISSUE TITLE
Material class names are misleading

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#29]
[GitLab issue: #671](https://gitlab.cern.ch/acts/acts-core/issues/671)

`Material` defines the material properties for a material of undefined dimensions while `MaterialProperties` defines a block/slab/slice of a concrete material.

Suggestion: rename `MaterialProperties` to `MaterialSlab`.

**Comment by msmk0** [comment]
After discussions with @Corentin-Allaire we decided to rename `MaterialProperties` to `MaterialSlab`.
