### ISSUE TITLE
bad hole count passed to CKF branch stopper

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#2905]
Using the CKF branch stopper from Athena cuts many more tracks than expected in the ITk for |&eta;|>2.5.

Athena's branch stopper is passed an [`Acts::CombinatorialKalmanFilterTipState`](https://github.com/acts-project/acts/blob/main/Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp#L67) object `tipState`, and returns `true` for those with `tipState.nHoles > 2`. This should have the same effect as removing those tracks from the output collection after the CKF is run but, as [these slides](https://github.com/acts-project/acts/files/14067621/ckf_5.pdf) show, there is a large reduction in efficiency.

This issue is observed with Athena `main,r2024-01-18`, which uses ACTS v31.2.0. It does not include the change to the `BranchStopper` signature introduced in #2757, which comes with v32.0.0.

This is probably a bug in ACTS Core, but not critical.

**Comment by timadye** [comment]
Unless someone has a better idea, I will try to reproduce this issue in ActsExamples.

**Comment by paulgessinger** [comment]
It might be a good idea to use the track state that is now passed to the branch stopper to count the holes the track has so far and just compare that with what the tip state claims.

**Comment by timadye** [comment]
I checked whether I could reproduce the issue with standalone ACTS, but it seems to work fine - at least with the latest `main`. I tried introducing the same selections that Athena uses (#2934), but still no problem.
The problem is still there with Athena + ACTS v32.0.2, so unless it was fixed since v32.0.2, it is probably something in how the CKF is called from Athena.

**Comment by timadye** [comment]
Now I am looking at the track state passed from Athena. I guess I can use `TrackStateProxy::typeFlags()` to see the holes. 
Once I found the `Acts::ConstTrackStateType` printout label listed the flags the wrong way round (I'll submit a PR fix), I can see the holes that are shown in the tip state counts.
I continue to investigate...

**Comment by timadye** [comment]
OK, I think I see what's going wrong.

In Athena (at least), the `BranchStopper` is called several times after the last measurement. The additional track states are on the same branch (increasing `previous`, `pathLength`, and radius). They are flagged as either material or holes. Without the branch stopper, the returned trajectory ends with the last measurement, so the extra holes are not counted when checked outside the CKF.

The problem is that if, with these extra holes, there a more than 2 holes (`maxHoles`) then the branch is dropped entirely. I guess we could retain the track if we had enough measurements. More efficient might be if we could stop the branch at that point but still retain it in the output (is this possible)?

In the latter case, the logic is, in principle, a bit different from checking the holes afterwards: we allow a gap of 3 holes to stop the trajectory rather than a final measurement(s) giving us a track that will fail the hole cut even if there are enough measurements before that. This could be an improvement, if it ever occurs in practice.

Or is there a better way to check for this circumstance?

**Comment by timadye** [comment]
Perhaps @andiwand also has some comments on the last findings.

**Comment by andiwand** [comment]
Maybe the branch stopper can also return if the track should be kept or not? I could imagine that we could use both scenarios: early removal of uninteresting tracks and stopping the propagation to save CPU and keeping the tracks.

**Comment by timadye** [comment]
Yes, that could be very useful. I wondered if there was a clever way to do it already (with v32) using the TrackStateProxy, which is (oddly) passed by non-const ref.

**Comment by paulgessinger** [comment]
No particular reason having it as non const

**Comment by timadye** [comment]
The problem I was seeing with Athena was fixed with [!68980](https://gitlab.cern.ch/atlas/athena/-/merge_requests/68980):
> Only stop branch with >2 holes if it also has fewer than the required number of measurements. If there are enough measurements, we only stop it after 3 holes followed by another measurement. This logic prevents the branch being stopped (and therefore discarded) if there are missing measurements at the end of an otherwise perfectly good track.

It would still be useful to allow keeping the stopped branch, but that can be the subject of another Issue.
