### ISSUE TITLE
Improvement: allow CKF to keep stopped branch

### ISSUE THREAD

**Issue by timadye** [acts-project/acts#2967]
Following on from #2905, @andiwand suggested:

> Maybe the branch stopper can also return if the track should be kept or not? I could imagine that we could use both scenarios: early removal of uninteresting tracks and stopping the propagation to save CPU and keeping the tracks.

Maybe instead of the CKF's `BranchStopper` returning a `bool`, it could return an:

```
enum BranchStopperResult {
  ContinueBranch = 0,
  DiscardBranch = 1,
  StopAndKeepBranch = 2
};
```

Although the `enum` and `bool` values are upwardly compatible, the type is obviously different, so I guess this would require a breaking change.

If we are already changing the API, it might be useful to simplify the [call signature](https://github.com/acts-project/acts/blob/main/Core/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp#L89) to pass the track state by `const &`:
```
  using BranchStopper = Delegate<TrackStateFlag(const CombinatorialKalmanFilterTipState&,
                                      const typename traj_t::TrackStateProxy&)>;
```

This proposal is not urgent, so it could be included with the next breaking release.

**Comment by AJPfleger** [comment]
@andiwand @timadye what is the status on this?

**Comment by andiwand** [comment]
this is handled with https://github.com/acts-project/acts/pull/3102
