### ISSUE TITLE
Initial Navigation Path Length

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#321]
The initial step of the navigation in the sPHENIX geometry sometimes skips the MVTX, as indicated in these two figures:

[materialMapEvNr1.pdf](https://github.com/acts-project/acts/files/4919637/materialMapEvNr1.pdf)
[materialMapEvNr4.pdf](https://github.com/acts-project/acts/files/4919638/materialMapEvNr4.pdf)

The figures each show a single event with 100 muons - they show that the KF does not register half of the MVTX hits, and that this 180 degree half seems to randomly change event-by-event. I traced the bug to the `Intersection::<` operator, where sometimes the compared pathLengths are negative and sometimes they are positive. When they are positive, the navigation proceeds as expected, but when they are negative the wrong approach surface is selected and the MVTX is skipped. I also made some slides and discussed them in the developers meeting, linked [here](https://indico.cern.ch/event/916517/).

As discussed in the meeting, the solution is to restrict the pathLength to be positive only for the first step from the point of closest approach to the initial surface, and then allowing the pathLengths to be either positive or negative depending on what the RK integration step sees fit.

**Comment by osbornjd** [comment]
I believe this was fixed by [this](https://github.com/acts-project/acts/commit/a43373c6def3c4682f1a4a8219b319b14db5b53b) commit, so this issue can be closed to my understanding.

**Comment by msmk0** [comment]
Did you check that this fixes your issue with the sPHENIX detector?

**Comment by osbornjd** [comment]
Yes, it does for us.

**Comment by msmk0** [comment]
Thanks for the clarification. I will close the issue.
