### ISSUE TITLE
ci: kodiak does not update branches on automerge

### ISSUE THREAD

**Issue by AJPfleger** [acts-project/acts#3234]
## Issue
When the `automerge`-label is set, the PR needs to be updated manually, to merge it. Otherwise it will get stuck.

## Example Error
copied from https://github.com/acts-project/acts/pull/3208/checks?check_run_id=25575393299

⚠️ problem contacting GitHub API with method 'pull_request/update_branch'

Errors encountered when contacting GitHub API.

API call 'pull_request/update_branch' failed with HTTP status '403' and response: 'b'{"message":"refusing to allow a GitHub App to create or update workflow .github/workflows/analysis.yml without workflows permission","documentation_url":"[https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch"}\](https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch%22%7D%5C)''

## Hints to solve this issue
Maybe a token expired.

**Comment by paulgessinger** [comment]
I think this is an issue in branches and merges which would touch CI files. I believe this has never worked, and the PRs just need to be updated manually until the changes are through the pipeline of updates. 

I think I tried to follow this up with the Kodiak developer and there was no way to fix this.

**Comment by AJPfleger** [comment]
Seems like we cannot do enough about this, since it is intended to work like this. Since we just need to update manually, when there was a CI change before, it is not a huge issue. Close it for now and keep it in the archive.
