### ISSUE TITLE
CKF example breaks

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#330]
The CKF example breaks when the `CKFSourceLinkSelector` config is set up [here](https://github.com/acts-project/acts/blob/master/Examples/Algorithms/TrackFinding/src/TrackFindingOptions.cpp#L35)

It gives the error like below:

> terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_any_cast>' what():  boost::bad_any_cast: failed conversion using boost::any_cast

I guess this happens when the #278 is merged in (we probably failed to run the CKF reco then thus not aware of the problem)

 @msmk0 ,  do you have any idea how this could be fixed?

**Comment by msmk0** [comment]
I do not think this is the `GeometryHierarchyMap` since it does not use any boost libraries. I suspect this is an issue in the options parsing since this is the part that uses `boost::any` internally.

**Comment by XiaocongAi** [comment]
OK, I will take a look.
