### ISSUE TITLE
Cylinder surfaces are complicated to handle during navigation

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#3440]
In a discussion with @benjaminhuth we arrived at the point again where we concluded that cylinder surfaces are tricky to handle during navigation because they can have two intersections with a straight line. Sine we are reworking the geometry an alternative approach would be to split the cylinder into >=3? phi sectors to avoid this case and deal with it as with any other surface.

**Comment by asalzburger** [comment]
I hope the problem is greatly reduced using Gen2/Gen3 geometry. 
(I do have - in fact for the Gen2 geometry - a test version where I approximate all cylinders except for portals with a configurable number of rectangles).

**Comment by asalzburger** [comment]
One more thought though:

"However, in Gen2, as the portal surfaces mainly act as support (so does e.g. the beam pipe portal surface act as the beam pipe) I currently have no single cylindrical support surfaces left for the moment."

Although this is true at the moment, I would not want to rely on that, having a cylindrical surface in a volume is perfectly ok and we should come up with a solid solution how to handle this. We can use the Gen-2 geometry work to develop it and test it.

I suggest we talk about this today: @benjaminhuth @andiwand

**Comment by asalzburger** [comment]
And finally, on Gen3:

If @paulgessinger 's design holds (and I have no doubts), we have a full representation of the geometry in hand as a tree - and similar to what we planned to translate this at this stage into `detray`, we could think of translate this into a planar-only geometry where cylinders and discs are represented as either rectangles/polygons - or if you want fully as a triangulated mesh - the latter would allow only one intersection method as it is standard in ray tracing.

**Comment by paulgessinger** [comment]
I've based the my current work on the assumption that each portal surface ends up being a single continuous surface for each side of a volume. That's why I've been working on the portal merging, including merging cylinder phi sectors to make them continuous.

If we kill this assumption, I think my approach to build the portals up from the bottom up also breaks apart, because the approach of stitching a pair of surfaces together to glue volumes doesn't work anymore. (E.g. if a cylinder outer cover can have arbitrary surfaces). 

So if this makes the navigation easier, we might have to do it, but from thinking about it now I'd probably have to scrap the geometry construction.

**Comment by paulgessinger** [comment]
Also: doesn't this increase the number of expensive cylinder intersections we have to run by a factor of 4?

**Comment by andiwand** [comment]
> Also: doesn't this increase the number of expensive cylinder intersections we have to run by a factor of 4?

Yes this also worries me a bit. I don't see an easy way of deduplicating these.

About the breaking of the construction: wouldn't it be possible to build the full geometry and then split the cylinders in a final step?

I also thought about splitting during navigation by providing different bounds depending on where you are aiming but that might also be cumbersome.

**Comment by asalzburger** [comment]
As I wrote: for the portal surfaces cylinders are easier to handle and I would not drop them easily, a cylinder intersection is more costly, but by no means intersecting a reasonable number of segments is faster. 

I still think we need to solve this in the navigation;

I have a suggestion comment in my latest PR that foresees a split of surface candidates from the intersection buffer - in this case a cylinder can always show up as a single surface candidate with 0,1 or 2 candidate intersections that can be re-evaluated.

Stay tuned.

As of the glueing: if we wanted e.g. to have (try out) a fully triangulated mesh as tracking geometry - my approach would be to generate this from the glued cylinder / disc setup, which can be done similar to the detray geometry conversion - however, I would see that as blue sky R&D at most.

**Comment by paulgessinger** [comment]
> About the breaking of the construction: wouldn't it be possible to build the full geometry and then split the cylinders in a final step?

Not really, because you can have binning on the surfaces to potentially accommodate different target volumes. So I'd have to merge while binning, then split the binning when splitting the surface, which is probably an order of magnitude more complicated than what I was planning so far.

**Comment by andiwand** [comment]
We discussed this in a meeting and concluded that cylinders have to be handled correctly in the navigation and are a central part of our geometry. Splitting them does not solve the problem because a nearly tangent ray will always result in two intersections. Closing.
