### ISSUE TITLE
`MultiEigenStepperLoop` returns position not on surface while components are

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#3441]
Taking about cylinders... with curved surfaces the `MultiEigenStepperLoop` can end up reporting being on surface while the position is not because we average in global coordinates which pulls you a bit off surface.

This confuses the navigation and in https://github.com/acts-project/acts/pull/3437 results in endlessly trying to target a boundary we are actually sitting on.

I think @asalzburger suggested once to average the components on the surface and then transform to global. Is that possible @benjaminhuth?

Alternatively I can also increase the near limit for now so those intersection would not be seen by the navigator. But ultimately this problem cannot be solved by the navigator itself in my opinion.

**Comment by andiwand** [comment]
The problem can be observed here https://github.com/acts-project/acts/pull/3442

**Comment by AJPfleger** [comment]
Let's recheck if this is fixed. @andiwand @benjaminhuth

**Comment by andiwand** [comment]
resolved with
- https://github.com/acts-project/acts/pull/3521
- https://github.com/acts-project/acts/pull/3671
