### ISSUE TITLE
Acts::Measurement infrastructure has unacceptable build overhead

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#350]
After trimming a bunch of Eigen fat, the compile-time overhead of Acts' fitting unit tests and examples becomes bottlenecked by the Measurement infrastructure, and more precisely the "unique ordered sublists" variant that it provides. To quantify this, about 50% of template-related compilation time for these compilation units is spent processing that code alone.

---

Given an N-dimensional state space `(x1, x2, ..., xN)`, this mechanism provides an `std::variant` that goes over all possible tuples `std::variant<(x1), (x1, x2), (x1, x3), ..., (x1, xN), (x2), (x2, x3), ..., (x2, xN), (x1, x2), (x1, x2, x3), ..., (x1, x2, xN), ..., (x1, x2, ..., xN)>`.

As you can imagine, the combinatorics are not in our favor here, and the resulting `std::variant` has a lot of different alternatives. More precisely, since this variant is semantically equivalent to an `(std::optional<x1>, std::optional<x2>, ..., std::optional<xN>)` tuple with the additional constraint of excluding the "all optionals empty" null state, we can easily compute that the number of variants will be 2^N-1, which for the N=6 case that Acts is currently using means 63 different variants.

The overhead associated with generating this type and its basic methods is already quite significant in practice because libstdc++'s implementation of `std::variant` is not optimized for low compile-time overhead, but for high-quality error reporting. It sends the input types through various type traits for SFINAE and static assertions, and type traits themselves are not super cheap to instantiate.

Furthermore, the overhead is not restricted to the instantiation of that `std::variant` and its basic operations like the constructor. Every `std::visit` through that `std::variant` will have its associated code duplicated 63 times. So for example, templated code which has a RAM footprint of 10MB when instantiated once will get, in the worst case where the compiler does not manage to deduplicate anything, a RAM footprint of 630MB when fed through `std::visit`.

---

During my last conversation with @paulgessinger about this mechanism, I did not manage to understand why exactly this std::variant cannot be replaced with `std::tuple<std::optional<x1>, std::optional<x2>, ..., std::optional<xN>>`, or an optimized version thereof.

In general, I do not currently understand this mechanism well enough to see if we actually need it, let alone optimize it. All I can say, from my current perspective, is that getting rid of it, if at all possible, would likely be highly beneficial to Acts' compilation times and build RAM consumption.

@paulgessinger and @msmk0 have expressed interest in working on this. I wouldn't mind helping either, but I need to understand this better to work on it, so if I were to work on this someone first needs to sit down with me for a while until I fully get it.

See also #280 where Paul proposes an alternate design for both Measurement and MultiTrajectory.

**Comment by paulgessinger** [comment]
Yeah I think we need to get rid of this mostly. We do some auto generation that is based on the concrete indices given, but I guess even if we keep that we could maybe replace `std::variant` with what you propose here on a shorter-time scale than #280. The measurement class also contains some logic (partially constexpr) that we would need to replicate, in a type based on an `std::tuple`.

That would also require a replacement for the dispatching mechanism, that right now simply uses `std::visit` to dispatch on the concrete `Measurement` type.

Lets discuss this, maybe over voice-chat, in detail at some point (soon)!

**Comment by msmk0** [comment]
I would be interested in looking into this. I need to catch up a few things this week and could work on this next week.

**Comment by paulgessinger** [comment]
@msmk0  is working on this.
