### ISSUE TITLE
outdated script `acts/Examples/Scripts/run_full_chain.sh`

### ISSUE THREAD

**Issue by nibir98** [acts-project/acts#3548]
I was trying to run `acts/Examples/Scripts/run_full_chain.sh` but none of the CMakeLists.txt creates the ActsSimFatrasGeneric & ActsRecTruthTracks executable which is required in the sh script.

https://github.com/acts-project/acts/blob/main/Examples/Scripts/run_full_chain.sh

**Comment by AJPfleger** [comment]
Hi @nibir98,
Thanks for reporting this. We removed the example binaries a few months ago, unfortunately a few scripts are still floating around.

We now switched completely to python bindings. Please have a look at `Examples/Scripts/Python`. There you can find some scripts, that are similar to the full chain, you wanted to try out.

This part of the documentation might also give you some more details to the bindings itself.
https://acts.readthedocs.io/en/latest/examples/python_bindings.html
