### ISSUE TITLE
Error while building Geant4 plugin

### ISSUE THREAD

**Issue by nibir98** [acts-project/acts#3557]
I get this error while building acts with Geant4 plugin 
error: 'using enum' only available with '-std=c++20' or '-std=gnu++20'
   71 |             using enum AxisType;

Specifically set cxx type to c++ 20 in the CMakeLists.txt file

set(CMAKE_CXX_STANDARD 20)           # Use 17 for C++17 or 20 for C++20
set(CMAKE_CXX_STANDARD_REQUIRED YES) # Ensure the standard is strictly enforced
set(CMAKE_CXX_EXTENSIONS NO)         # Avoid using compiler-specific extensions
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20")

Is it possible that this could be due to conflicts with other dependencies?

**Comment by asalzburger** [comment]
Did you build your externals (including Geant4) also with C++20?

**Comment by nibir98** [comment]
A possible reason could be that I'm using a G4 build on the Fermilab machines. I'm also seeking suggestions on how to get started with ACTS and what the minimum build requirements are to run a full chain analysis. My goal is to implement ACTS in our straw-based detector to reconstruct muons. We have the complete simulation chain, and I want to explore various reconstruction options, such as KF, KCF, and GCF, from ACTS. 
If it’s not too much trouble, could you please provide contact information for the ACTS team so that I may reach out directly?

**Comment by paulgessinger** [comment]
Hey @nibir98, there's a team on the CERN Mattermost [here](https://mattermost.web.cern.ch/acts/), that's usually a good place to start. 

Unfortunately, C++20 is a basic requirement at this point. Is there any way you can get a version of G4 that's compiled with C++20?
