### ISSUE TITLE
Time q/p correlation blows up  propagation performance.

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#36]
[GitLab issue: #653](https://gitlab.cern.ch/acts/acts-core/issues/653)

As discussed on Mattermost, this change

```cpp
D(3, 7) =
      h * state.options.mass * state.options.mass *
      stepper.charge(state.stepping) /
      (stepper.momentum(state.stepping) *
        std::hypot(1., state.options.mass / stepper.momentum(state.stepping)));
```

from !661 seems to obliterate propagation performance, at least the runtime of the fitting example increases by about a factor of 5.

It seems like this is an effect of the assignment of a non-zero value to `D(3, 7)` rather than the calculation happening here.

@ fklimpel can you follow up on this?

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-10-28 13:28:28](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2939467)

 /cc @ asalzbur

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-10-28 14:35:48](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2939762)

 @ pagessin thanks for the detailed investigation - I will run the profiler, as a start, then we can have a more detailed look.

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-10-30 06:45:22](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2946156)

 The change is indeed reproducable:

- master:
![Screenshot_2019-10-29_at_16.06.25](/uploads/acae7926465a2e45c71e7338b6d5bf1f/Screenshot_2019-10-29_at_16.06.25.png)

- by setting the `D(3,7)` component to `0`:
![Screenshot_2019-10-29_at_16.37.28](/uploads/87eaa00cb70055aeb1653dd859015bfb/Screenshot_2019-10-29_at_16.37.28.png)

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-10-30 09:49:44](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2946398)

 Just to confirm, the calculation of the component does not cause the effect, but the presence in the matrix:

```c++
double e =  h * state.options.mass * state.options.mass *
        stepper.charge(state.stepping) /
        (stepper.momentum(state.stepping) *
         std::hypot(1., state.options.mass / stepper.momentum(state.stepping)));
```

I added this as a dummy line, but the time stays still low, if `D(3,7) = 0.;`

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-10-30 09:50:36](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2946402)

 I will now test the `PropagationExample` to check if that is for the transport only - or appears in the `KalmanFilter`.

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-11-25 10:15:11](https://gitlab.cern.ch/acts/acts-core/issues/653#note_3012151)

 We will have to come back to this, after #613 is in, we will have system with `overstepping` which should fix potential navigation problems we still had. I will time again, and we probably need to re-order the internal representation.

**Comment by paulgessinger** [comment]
This is definitely still an issue that absolutely needs fixing!

**Comment by paulgessinger** [comment]
We never fixed this. Is this something we want to fix/finalize before `1.0`? @msmk0 @asalzburger @FabianKlimpel

**Comment by msmk0** [comment]
This does not need to be in `v1.0.0`. It should be fixed but that would not change the external interface and should thus be safe to do later.

**Comment by paulgessinger** [comment]
But it changes the parameter ordering? Is that not public interface?

**Comment by msmk0** [comment]
It might, but I am not sure if the parameter ordering is part of the public interface. The symbolic names in the enum are definitely in the public interface, but we could very well argue that the specific values are not. You should always treat the parameters vector as opaque or access it only through the symbolic names.

**Comment by paulgessinger** [comment]
But realistically, I'm not sure this is the case.

**Comment by msmk0** [comment]
It definitely should be. If this is a problem of parameter ordering, we can also only fix it for our default parameters. The user can override them and define a custom ordering. In that case, a user might accidentally re-introduce this issue.

Adding a requirement to the public api that vector components should only be accessed via their symbolic value removes ambiguity and gives as a bit of flexibility.

**Comment by paulgessinger** [comment]
Sure, but if it is de-facto not the case, it is public api.

**Comment by msmk0** [comment]
But that is our decision to make, right? If we say with `v1.0.0` only access by `enum` is the public api, than that is the public api.

I agree that we should try not to change this if not absolutely necessary.

**Comment by paulgessinger** [comment]
That depends if @baschlag uses index based access in the vertexing code deployed, if he does, it's public.

**Comment by asalzburger** [comment]
> [Original comment by: asalzbur at 2019-10-30 09:49:44](https://gitlab.cern.ch/acts/acts-core/issues/653#note_2946398)
> 
> Just to confirm, the calculation of the component does not cause the effect, but the presence in the matrix:
> 
> ```c++
> double e =  h * state.options.mass * state.options.mass *
>         stepper.charge(state.stepping) /
>         (stepper.momentum(state.stepping) *
>          std::hypot(1., state.options.mass / stepper.momentum(state.stepping)));
> ```
> 
> I added this as a dummy line, but the time stays still low, if `D(3,7) = 0.;`

I could not reproduce this in a simple test last week on master.

**Comment by FabianKlimpel** [comment]
> I could not reproduce this in a simple test last week on master.

Does it mean that the performance is going up when you set it to 0?

**Comment by asalzburger** [comment]
No, I do not see the a significant reduction when I set `D(3,7) = 0`.

Anyhow, I saw quite some timing issues with the `EigenStepper`, it's currently significantly slower than the AtlasStepper.

**Comment by paulgessinger** [comment]
Hm, so last time I had tested this on my end, `D(3,7) = 0` had *good* performance, and `!= 0` had *bad* performance. Do we think that right now this might be masked by something else worsening propagator performance?

**Comment by FabianKlimpel** [comment]
> Hm, so last time I had tested this on my end, `D(3,7) = 0` had _good_ performance, and `!= 0` had _bad_ performance. Do we think that right now this might be masked by something else worsening propagator performance?

The issues @asalzburger found were there for a long time already and are not related to this issue.
But the latest changes in the stepper (#569) give us an opportunity to change it easily in the near future (i.e. after #572). If all matrix and vector elements are accessed by the bound or free enum then re-defining the enum would allow us to move this particular index to another entry in the matrix. Hence the former block of zeros should be restored.

**Comment by HadrienG2** [comment]
> Anyhow, I saw quite some timing issues with the `EigenStepper`, it's currently significantly slower than the `AtlasStepper`.

@asalzburger Just out of curiosity, did you check with and without covariance transport enabled? When I last checked, without covariance transport the speed of the two steppers was comparable, and it was covariance transport specifically which seemed to need some work in the `EigenStepper`.

**Comment by paulgessinger** [comment]
Ok, so we have two issues:

1. `D(3,7) != 0` makes `EigenStepper` slow
2. `EigenStepper` is slow generally

Can you confirm this?

**Comment by asalzburger** [comment]
As I said, I could not easily reproduce the point 1. - but timing is always tricky to do.

For 2. the splitting of the Jacobian calculation into different functions has probably created an unneccessary overhead in creation of matrices, which I can partly reduce when concentrating the math back into one function.

**Comment by paulgessinger** [comment]
But you had reproduced as per you [comment back on GitLab](https://gitlab.cern.ch/acts/acts-core/-/issues/653#note_2946398) (also posted here in my name due to the migration). So it might have gone away or be masked by number 2.

**Comment by asalzburger** [comment]
I know, I tried setting the component to 0 last week and it did not show up (at least not this significantly), I will have to redo the tests, but as @FabianKlimpel said correctly, the reordering of the components would be much easier when #572 and #569 are both in.

**Comment by paulgessinger** [comment]
Ok, that's perfectly fine! I just wanted to know what the current understanding / situation is.

**Comment by asalzburger** [comment]
Hi, I ran the KF_filter test with and without the component set to zero:

* `D(3,7)` set to 0:

```shell
Algorithm:TrackFitterAlgorithm  2.584   0.2584 
```

* `D(3,7)` as spelled outL

```shell
Algorithm:TrackFittingAlgorithm 2.976   0.2976
```

**Comment by robertlangenberg** [comment]
closed as it could not be reproduced, may take a closer look after investigating potentially related issues
