### ISSUE TITLE
DD4hep conversion crashing

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#372]
![vertex_tracker](https://user-images.githubusercontent.com/2065918/89977138-03e37280-dc30-11ea-83a8-6dd1bff2b198.png)

I am trying to convert the barrel detector shown above. The DD4hep constructor can be found here
https://eicweb.phy.anl.gov/EIC/NPDet/-/blob/master/src/ConceptDetectors/topside/src/SiliconTrackerBarrel_geo.cpp

AFAIK, I followed the instructions for the plugin. 
Calling after building the dd4hep geometry with `Acts::convertDD4hepDetector (detector.world(),Acts::Logging::Level::VERBOSE);` gives:

```
00:06:10    DD4hepConver   INFO      Translating DD4hep geometry into Acts geometry
00:06:10    DD4hepConver   INFO      Translating DD4hep sub detector: SiVertexBarrel
00:06:10    D2A_Logger     VERBOSE   Processing detector element:  SiVertexBarrel
00:06:10    D2A_Logger     VERBOSE   Subdetector: SiVertexBarrel is a (sensitive) Barrel volume - building barrel.
00:06:10    D2A_V:SiVert   DEBUG     Configured to build volume : SiVertexBarrel
00:06:10    D2A_LB_SiVer   VERBOSE    No layers handed over for negative volume!
00:06:10    D2A_LB_SiVer   VERBOSE    Received layers for central volume -> creating cylindrical layers
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
00:06:10    D2A_LB_SiVer   WARNING   Could not get Acts::Extension

 *** Break *** segmentation violation
 Generating stack trace...
 0x00007fb929e052d0 in Acts::DD4hepLayerBuilder::centralLayers(std::any const&) const + 0x1a0 from /usr/local/lib/libActsDD4hepPlugin.so
 0x00007fb929318164 in Acts::CylinderVolumeBuilder::trackingVolume(std::any const&, std::shared_ptr<Acts::TrackingVolume const>, std::shared_ptr<Acts::VolumeBounds const>) const + 0x634 from /opt/software/linux-ubuntu20.04-x86_64/gcc-9.3.0/acts-0.29.0-4qfgw4vv47e5y55k6merojqnjktcu7h7/lib/libActsCore.so
 0x00007fb929decf84 in <unknown> from /usr/local/lib/libActsDD4hepPlugin.so
 0x00007fb92938354e in Acts::TrackingGeometryBuilder::trackingGeometry(std::any const&) const + 0x8e from /opt/software/linux-ubuntu20.04-x86_64/gcc-9.3.0/acts-0.29.0-4qfgw4vv47e5y55k6merojqnjktcu7h7/lib/libActsCore.so
 0x00007fb929df4cc4 in Acts::convertDD4hepDetector(dd4hep::DetElement, Acts::Logging::Level, Acts::BinningType, Acts::BinningType, Acts::BinningType, double, double, double, std::function<void (std::vector<dd4hep::DetElement, std::allocator<dd4hep::DetElement> >&)> const&, std::any const&, std::shared_ptr<Acts::IMaterialDecorator const>) + 0x1544 from /usr/local/lib/libActsDD4hepPlugin.so
 0x00007fb927ba82c3 in example_Acts(char const*) + 0x1a3 from /work/whit/projects/EIC/hytop_test/scripts/example_Acts_cxx.so
```

Do I need to sort the DetElements?

Thanks in advance.

**Comment by asalzburger** [comment]
I will have a look, the `DD4HepPlugin` fell a bit behind, when I restructured the `TGeoPlugin` before summer, so probably it needs some update.

In discussions with the FCC folks we were actually wondering IF we need a dedicated `DD4HepPlugin` for the Geometry, when in the background anyway a TGeo geometry is built.

Just for clarification: I should be able to find the DD4Hep file there as well?

**Comment by whit2333** [comment]
@asalzburger 
You can find the compact detector description here
https://eicweb.phy.anl.gov/EIC/NPDet/-/blob/master/src/ConceptDetectors/topside/compact/topside/vertex_tracker.xml
with materials/elements from 
https://eicweb.phy.anl.gov/EIC/NPDet/-/blob/master/src/ConceptDetectors/topside/compact/materials.xml
https://eicweb.phy.anl.gov/EIC/NPDet/-/blob/master/src/ConceptDetectors/topside/compact/elements.xml

I will put together a small repo for testing dd4hep/acts with this detector.

**Comment by whit2333** [comment]
@asalzburger [this repo](https://eicweb.phy.anl.gov/whit/hytop_test) should reproduce the problem.

**Comment by whit2333** [comment]
I have just confirmed the same behavior with v0.30.

**Comment by asalzburger** [comment]
Thanks, I will get behind this first thing next week.

**Comment by whit2333** [comment]
@asalzburger I did some debugging. I found my mistake. The sensitive DetElement inside a module did not have the attached extension. The module's DetElement did. When I corrected this, the crash is fixed.

I will submit a PR which adding a check on this.

**Comment by asalzburger** [comment]
Ok, I can reproduce it:

```shell
Detector         INFO  +++ Patching names of anonymous shapes....
DD4hepVolumeManager INFO  **** running plugin DD4hepVolumeManager !
VolumeManager    INFO   - populating volume ids - be patient ...
VolumeManager    INFO   - populating volume ids - done. 437 nodes.
VolumeManager    INFO  +++ Volume manager populated and loaded.
10:42:38    DD4hepConver   INFO      Translating DD4hep geometry into Acts geometry
10:42:38    DD4hepConver   INFO      Translating DD4hep sub detector: SiVertexBarrel
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension
10:42:38    D2A_LB_SiVer   WARNING   Could not get Acts::Extension

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
```

**Comment by asalzburger** [comment]
The geometry builds with master with two modifications to your setup, in your detector construction, move the declaration of the `Acts::Extension` for the sensitive sensor to flag only the sensitive component:

```c++
        Acts::ActsExtension* sensorExtension = new Acts::ActsExtension();
        sensorExtension->addType("sensor", "detector");
        for (size_t ic = 0; ic < sensVols.size(); ++ic) {
          PlacedVolume sens_pv = sensVols[ic];
          DetElement comp_elt(mod_elt, sens_pv.volume().name(), module);
          comp_elt.setPlacement(sens_pv);
          comp_elt.addExtension<Acts::ActsExtension>(sensorExtension);
        }
```

That makes the detector build, but you get some warnings that layers attach, you can fix those by introducing small envelopes in your xml, that's dirty for the moment, but see some comments later:

```xml
      <layer module="SOIPIXD" id="8" vis="VertexBarrelLayerVis">
        <barrel_envelope inner_r="(VertexTrackerRadius7+VertexTrackerRadius8)/2+0.5*mm" 
                         outer_r="VertexTrackerRadius8+5*mm" z_length="VertexTrackerBarrelLength"/>
        <rphi_layout phi_tilt="10.0*degree" nphi="VertexTrackerNModules8" phi0="0.0" rc="VertexTrackerRadius8" dr="0.0 * mm"/>
        <z_layout dr="0.0 * mm" z0="0.0 * mm" nz="1"/>
      </layer>
```

As for the `TGeo` module I have recently already changed that the actual spacial dimensions a layer needs is not taken from input, but from parsing, in order to avoid errors such as `r2_min < r1_max`, in your case r2_min was exactly r1_max, which is natural, in some sense.

There will be a development in the future (#185) where we will abandon the concept of a layer and make it look like a volume itself, but that will have to wait a little bit, in the meantime I will update the DD4hep plugin accordingly to what the `TGeoPlugin` does.

**Comment by asalzburger** [comment]
![Screenshot 2020-08-17 at 11 32 46](https://user-images.githubusercontent.com/26623879/90382009-7d3ef300-e07e-11ea-9c50-7f9e75aff9bc.png)

**Comment by asalzburger** [comment]
The binning of the BinnedArray is not really good yet, another thing that's already sorted out with the `TGeoPlugin`.

**Comment by whit2333** [comment]
@asalzburger  Thank you!

Looking at #185, I see the new DetectorVolume plan and wonder how this differs from DD4hep?

Also, I realized while reading code this weekend that the segmentation concept is not really needed in Acts because hit (sensor) positions and the covariance matrix can be easily transferred onto the acts surfaces using dd4hep. IMO, as a consequence of not using a detector description tool like dd4hep, ancillary geometry developments are needed which cause extra complexity leading to a bloated implementation of a simple concept, such as a Layer (#13).

I think the layer concept (as a collection of surfaces) is generally a good idea for tracking tools. Is the idea to get rid of it all together?

**Comment by whit2333** [comment]
I'll close this since the segfault issue was resolved.

**Comment by asalzburger** [comment]
> @asalzburger Thank you!
> 
> Looking at #185, I see the new DetectorVolume plan and wonder how this differs from DD4hep?
> 
> Also, I realized while reading code this weekend that the segmentation concept is not really needed in Acts because hit (sensor) positions and the covariance matrix can be easily transferred onto the acts surfaces using dd4hep. IMO, as a consequence of not using a detector description tool like dd4hep, ancillary geometry developments are needed which cause extra complexity leading to a bloated implementation of a simple concept, such as a Layer (#13).
> 
> I think the layer concept (as a collection of surfaces) is generally a good idea for tracking tools. Is the idea to get rid of it all together?

Actually, all what we (I) plan to do is to merge the Volume and Layer description such, but keep the boundary portal mechanism. The positive side effect would be a vast simplification of the `Navigator` module, but as I said, this will come later. Let's for the moment try to iron out the issues we have with the `DD4hep` module.
