### ISSUE TITLE
Add propagation integration tests with non-constant field

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#377]
Add tests based e.g. on a computed (approximated) solenoid field or a field-map-based one.

All current maintained tests use a constant magnetic field. There is a non-working implementation that is supposed to use the ATLAS magnetic field, but the field map is large and not part of the repository. Thus, it is not suited as an automatic integration test.

**Comment by paulgessinger** [comment]
FYI: We have a computed solenoid implementation. There's also a helper function that can make a field map from it (much faster lookup)

**Comment by msmk0** [comment]
I saw that. That might be the best solution: to compute a solenoid field map from the computed solenoid field map. This only needs to done once for the full test anyways.

**Comment by paulgessinger** [comment]
Right, there's no easy way to persist it between test binaries though. Conversion, depending on the binning, can take a few seconds (the analytical implementation is **sloooooow** because of the elliptical inegrals)

**Comment by msmk0** [comment]
No, but I do think that is an issue for the integration tests.
