### ISSUE TITLE
Workpackage: Digitization

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#388]
This Issue describes the longer term work on the digitisation package, which will be done in a series of PRs

- [x] introduce a new generic Measurement constructor, PR: #386 (merged)
- [x] create a `Fatras/Digitization` package with a generic hit smearing module, PR: #387 
- [x] adapt the Framework hit smearing to the new smearer, starting with program options
- [x] create a `json` based dictionary for reading the resolutions, segmentations
- [x] introduce the 2D stepping as alter native to the 3D stepping  
- [ ] eventually remove the 3D stepping module (to be decided)

**Comment by msmk0** [comment]
Work is ongoing.

**Comment by asalzburger** [comment]
This is awaiting the EDM rework.

**Comment by asalzburger** [comment]
Only one issue open

**Comment by robertlangenberg** [comment]
Has been resolved
