### ISSUE TITLE
Stable interface and versioning discussion

### ISSUE THREAD

**Issue by robertlangenberg** [acts-project/acts#392]
As discussed in the meeting on 25.8., the Acts vertexing is going to be used in ATLAS' Athena. We therefore have to decide which guarantees we give regarding our versions. Suggestions so far:
Bump to version 1.0.0 🥳

Bumping with every breaking change
Bumping with every breaking change to a well-defined interface (the part that is used in Athena)
- this should be prominent in the documentation/version description

Decide support for major versions (which versions get backports)

Decide how/when other parties can request parts of the code to be considered stable.

etc etc. Please contribute to the discussion below, we have a limited timeframe before we should give ATLAS the go-ahead to use Acts in their production code. We should therefore look to find an agreement until next week's Tuesday meeting.

Happy arguing and be excellent to each other! 🥊 🥋

**Comment by paulgessinger** [comment]
I don't think there's any way around tagging 1.0.0 very soon (other than not doing semver, which I think wouldn't be a good idea)

How exactly we go about defining and handing breaking changes is basically what we need to converge on.

**Comment by asalzburger** [comment]
Shall we do a 2-week sprint, to actually change the most relevant upcoming changes we already know should happen, e.g.
 * Acts::Surface::localToGlobal() API change
 * Acts::Surface::m_transform from shared_ptr<> to Object
...

**Comment by msmk0** [comment]
I think that is a good idea. I would propose that we tag `v0.32.0` today and then reassign issues/PRs to the `v1.0.0` milestone. Then we can use the milestone to actually plan (for once) what needs to go in before we tag the first major version.

Let's postpone new functionality to after the `v1.0.0` release and stick to cleanups, renaming, etc, i.e. those changes that would break the API but that we have postponed in the past.

**Comment by paulgessinger** [comment]
As for keeping track of when we break compatibility, you could have a look at conventional commit messages: https://www.conventionalcommits.org/en/v1.0.0/#summary

That sort makes the PR opener consider this right away I would hope.

**Comment by asalzburger** [comment]
I think the two merged pull requests (#327 and #328) will create the need to update the Athena glue code.

**Comment by paulgessinger** [comment]
Right, maybe. So that we would probably want to adapt to this for the v1.0.0 bump.
