### ISSUE TITLE
Inconsistent naming of GeometryID retrieval

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#393]
In current master, we have two different naming for `Acts::GeometryID` retrieval.

  * `geoID()` in the Core module (127 occurrences)
  * `geometryId()` in the Examples and Fatras modules (19 occurrences)

I would suggest to streamline this.

**Comment by msmk0** [comment]
My personal preference is the later variant, `.geometryId()`. It is a bit clearer, more consistent with our `mixedCase` naming guidelines, and use the same style as some other accessors, e.g. `.particleId()` in the Fatras code.

This also recommended e.g. by the [Google Styleguide](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules) that also suggest to capitalize only the first letter of an abbreviation for better readability.

**Comment by asalzburger** [comment]
I am fine either way, let's just keep it consistent

**Comment by paulgessinger** [comment]
Should we just do a global replacement `s/geoId()/geometryId()/g`?

**Comment by msmk0** [comment]
Yes, please.
