### ISSUE TITLE
KalmanFitterOptions and PropagationOptions API

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#394]
There is an [option](https://github.com/acts-project/acts/blob/3f2345cb9f9eaff76b965166fa90ad6cd2df20f1/Core/include/Acts/Propagator/Propagator.hpp#L126) to set the navigation direction in the propagator, but this option does not exist in the Kalman Fitter options so that it can be set [here](https://github.com/acts-project/acts/blob/3f2345cb9f9eaff76b965166fa90ad6cd2df20f1/Core/include/Acts/Fitter/KalmanFitter.hpp#L947). It would be a useful feature if the fitter API could be modified such that the [KalmanFitterOptions](https://github.com/acts-project/acts/blob/3f2345cb9f9eaff76b965166fa90ad6cd2df20f1/Core/include/Acts/Fitter/KalmanFitter.hpp#L52) had accessors for all of the available propagator options, such that any and/or all could be configured prior to calling `fit()` to run the fitting.

**Comment by paulgessinger** [comment]
Hm maybe we could have the KF options wrap the PropagatorOptions and just expose that?

**Comment by XiaocongAi** [comment]
@paulgessinger , that's the idea. I guess we don't want to be involved with the action list and abortion list in the KF options, so perhaps we could wrap only those trivial propagation options in a struct and include that in the KF options?

**Comment by osbornjd** [comment]
That seems like a good solution to me - that way it can be provided as a single object through the KFOptions and then the information from that struct could be passed on to the PropagatorOptions. Xiaocong is right, I think, that it should only be trivial options so as to not expose potentially more complicated knobs for non-experts to play with.

**Comment by paulgessinger** [comment]
I see. Problem with that is that we'd have to make sure to keep it in sync.
