### ISSUE TITLE
Issues of using CylinderSurface as measurement surface

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#397]
As far as I understand, when using `CylinderSurface` as the measurement surface, we have two things to consider:
1) Transform between the free parameters and the  `CylinderSurface` bound  parameters( rphi, z). For this, we have to consider not only the coordinate transforms (handled by `localToGlobal` and `globalToLocal`), but also the Jacobian between the free and bound (handled by `initJacobainToGlobal` and  `initJacobianToLocal`).
2) The path correction arising from the geometry constraint, i.e. the intersection of the track should always be on the `CylinderSurface` (handled by the `derivativeFactors`).

So far, we have re-implemented the methods `localToGlobal`, `globalToLocal` and `initJacobainToGlobal` for the `CylinderSurface`, but not others: The `deriviativeFactors` is very complicated to calculate for the `CylinderSurface`, so an approximation might be reasonable. But  if I understand correctly, we are not even overriding the `initJacobianToLocal` for the `CylinderSurface`. 

And we have the similar problems for the `LineSurface`.

Could @FabianKlimpel or others help check if my understanding is correct?

**Comment by FabianKlimpel** [comment]
I looked it up and it seems that this is correct. Additionally, the `initJacobianToGlobal` is missing, too.
Regarding the `LineSurface`, @baschlag looked into it. Maybe he can comment on that part.
