### ISSUE TITLE
Conventional commits

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#402]
This is related to #392 
We will start using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) at least for determining which SEMVER bump a PR will trigger. 

### Prefixes

CC requires every commit to have a prefix that carries a meaning, such as `prefix: My commit message`.
Since we follow a squash & merge approach, this only has to be enforced on the PR title, which will end up being the squashed commit message. The main prefixes in the CC spec are `feat:` and `fix:`.

Effectively, this moves the categorization from our custom set of labels to CCs prefixes.

The spec does not actually give an exhaustive list of prefixes, so technically anything is allowed here. However, some prefixes in CC are associated with a specific SEMVER version bump, such as `feat:` resulting in a MINOR version bump, while `fix:` signifies a PATCH version bump.

Following Angular's de-facto standard set of prefixes apart from `fix:` and `feat:` (`build:`, `chore:`, `ci:`,` docs:`, `style:`, `refactor:`, `perf:`, `test:`), the mapping would be as follows:

| old label | new prefixes |
|:--|:--|
| `New Feature` | `feat:` |
| `Bug` | `fix:` |
| `Improvement` | `refactor:` |
| `Infrastructure` | `ci:`, `chore:`, `build:`, or whatever is appropriate |

The additional prefixes can be used for their respective purposes.

#### Breaking changes
All prefixes can be supplemented with a `!`, which signifies a **breaking change**, like `refactor!: Change API layout`. Additionally, you can provide a section of the PR description starting with `BREAKING CHANGE:` detailing what is causing the breakage. The `!` in the title and `BREAKING CHANGE` in the description are not exclusive, you can use both, and this is actually encouraged!

### Scopes

Finally, the CC spec allows giving an additional scope to these prefixes, like `fix(SCOPE): Some bugfix`. I propose we adopt these as well, thereby deprecating the `Component - XXX` labels in use now. We only use them for cosmetic purposes at the moment, but having them alongside the CC prefix will allow using them as part of the changelog, for instance.

@msmk0, @asalzburger, @robertlangenberg (anyone else is welcome to discuss as well of course!)

**Comment by HadrienG2** [comment]
Seems reasonable as long as this is limited to PR title. I am definitely unable to achieve that level of discipline on my individual dev branch commits, and rewriting the history to enforce it after the fact would take forever.

**Comment by msmk0** [comment]
Yes, that is the plan. Since we are squashing commits anyways this should not be an issue anyways.

**Comment by msmk0** [comment]
As per the discussion in the weekly meeting, we are going to use the de-facto standard prefixes.
