### ISSUE TITLE
Store Surface transformation by value

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#408]
Store the transform by value instead of via a `std::shared_ptr<Transform3D>` and allow construction directly from `const Transform3D&` instead of via a shared pointer.

Using a shared pointer was used under the impression that transforms would be regularly shared between different surfaces. This turned out not to be the case. The shared pointer introduces unnecessary allocation and memory indirection. Construction by `const Transform3D&` removes the need to construct a transient transform on the heap.

**Comment by paulgessinger** [comment]
Why not pass by value?
