### ISSUE TITLE
Move Surface inline code to implementation files

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#409]
A significant portion of the method implementations exists as `inline` methods in `.ipp` files. Since they are almost always called via virtual function calls there should not be any performance improvement from inlining them. Moving them to `.cpp` files should reduce some of the build overhead from having the inline methods around.

**Comment by paulgessinger** [comment]
@asalzburger measured this at some point after I asked him about this, and found a significant performance benefit of keeping it in the headers.

**Comment by asalzburger** [comment]
So, I have a branch almost ready for the change of the internal memory model of Surfaces, Layers and Volumes regarding the HepTransform - after this, I will try once more to measure the the impact of inlining and non-inlining certain functions and document it accordingly (such that we have a reference).

**Comment by asalzburger** [comment]
I want to re-measure anyway wether we gain/lose anything by not checking anymore if the transform can be `nullptr`, but in that case simply use a `Transform3D::Identity`.

**Comment by msmk0** [comment]
Still needs to be investigated how this affects build- and runtime.

**Comment by robertlangenberg** [comment]
performance tests TBD in the beginning of 2021 to make a decision
