### ISSUE TITLE
Add an experimental environment

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#417]
We sort of had something like this with the way the old `Legacy` system worked.

We can either make this a plugin, but that's kind of awkward for what @asalzburger wants to use this for. Instead, for example, we could have a CMake option / feature flag, that conditionally adds `.cpp` files containing the experimental code to the core shared lib, and exposes experimental headers under `Acts/experimental/Surfaces/Volume.hpp`. This way the user (client developer) sees that it's experimental, and once we're happy we can just remove the `experimental` folder and roll it into the main shared lib.

@msmk0

**Comment by asalzburger** [comment]
As discussed int he meeting, we can close this for the moment.
