### ISSUE TITLE
Rename concepts namespace

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#42]
[GitLab issue: #618](https://gitlab.cern.ch/acts/acts-core/issues/618)

Currently concepts are defined in `namespace Acts::concept`. This collides with the new [C++20 concept keyword](https://en.cppreference.com/w/cpp/language/constraints) and is inconsistent with our naming guidelines. Both Doxygen and Sphinx already know the `concept` keyword and complain loudly about this (see #601 / !614) and I expect that other tools will do so in the future. This should be fixed now to be safe.

A possible resolution would be to move all concepts to

    namespace Acts {
    namespace Concepts {
       ...
    }
    }

and concepts implementation details that are not part of the public interface to `namespace Acts::Concepts::detail`; similar to what is currently being done for regular code and its implementations.

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-06-13 16:37:10](https://gitlab.cern.ch/acts/acts-core/issues/618#note_2649930)

 I'd suggest not lumping this into the changes of !614, in case that was your plan. 

I think the separation of `Concepts` and `Concepts::detail` makes a lot of sense.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-06-13 16:59:14](https://gitlab.cern.ch/acts/acts-core/issues/618#note_2650045)

 No, this will not be in !614. I wanted to open this so that we don't forget.

**Comment by msmk0** [comment]
This still needs to be fixed. C++20 `concepts` will come.

**Comment by msmk0** [comment]
@paulgessinger @robertlangenberg @asalzburger I somehow forgot this today. This definitely needs to go into `v1.0.0`. This change **must** happen anyways to avoid conflicts with the C++20 keyword.

**Comment by paulgessinger** [comment]
True. Should be simple search & replace. I opened a PR.
