### ISSUE TITLE
Move all classes/structs into the Acts namespace

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#426]
Some classes/structs are defined in the global namespace, as listed e.g. in the [API documentation](https://acts.readthedocs.io/en/latest/api/api.html). These must be moved to the `Acts` namespace.

The symbols listed are:

- [x] ~~`NeedsRemovedTracks<T, decltype((void) T::tracksToRemove, 0)>`~~
- [x] ~~`Configuration`~~ 
- [x] ~~`Filter`~~
- [x] ~~`GeometryBuilder`~~
- [x] ~~`GeometryObjectSorter`~~
- [x] ~~`NeighborhoodIterator`~~
- [x] `TrackStatePropMask`

**Comment by paulgessinger** [comment]
Only `TrackStatePropMask` seems to actually be wrong. The other cases come from doxygen comments like

```cpp
/// @class Something
template <typename T>
class Something
```

or the `@class` name just being wrong. Then it creates an extra entry because these names are not prefixed with the namespace.
