### ISSUE TITLE
Combine LinearizedTrack position and momentum jacobians to single 8x8 jacobian

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#43]
[GitLab issue: #615](https://gitlab.cern.ch/acts/acts-core/issues/615)

Position and momentum jacobians in LinearizedTrack model currently do not account for correlations, combine them to a single 8x8 jacobian as used in the propagator instead.

**Comment by msmk0** [comment]
@baschlag is actively working on this.

**Comment by robertlangenberg** [comment]
work in progress
