### ISSUE TITLE
Barrel or endcap? DD4hep plugin

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#430]
What is the best way to build the dd4hep ACTS extension for the angled tracking detectors shown here?

![barrel_endcap](https://user-images.githubusercontent.com/2065918/92024567-f64b7500-ed23-11ea-84b3-68de3501acb0.png)

**Comment by asalzburger** [comment]
I think we'll have to write some code to translate into ConeLayer, the layer class exists but currently we do not have a converter from DD4hep out of the box for this.

**Comment by whit2333** [comment]
I suspected this was the case. What is the role of Layers? Is it used for material thickness calculation or something fundamental in the algorithms?

**Comment by asalzburger** [comment]
We will join this with the #509

**Comment by paulgessinger** [comment]
Closed in favor of trying the discussion Github feature: #630
