### ISSUE TITLE
Hard-coded indices for track parameters

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#434]
In principle, we should use the `BoundParametersIndices`/ `FreeParametersIndices` when accessing the element relevant to bound/free parameters. But some part of the code uses hard-coded `0`,`1`... for the indices.This should be fixed to use enum in `BoundParametersIndices`/ `FreeParametersIndices`.

**Comment by msmk0** [comment]
@XiaocongAi We should go once through the code and check for this.
