### ISSUE TITLE
refactor: Remove s_idTransform in favour of Transform3D::Identity

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#441]
I think we do not need s_idTransform anymore, as `Transform3D::Identity()` returns a static object as well, I make a PR to remove that, as `Transform3D::Identity()` is so much clearer.

_Originally posted by @asalzburger in https://github.com/acts-project/acts/pull/411#r484216896_

**Comment by paulgessinger** [comment]
Does this have to be in `v1.0.0`?

**Comment by asalzburger** [comment]
Not really, it's a transparent change, we can move it to next.

**Comment by msmk0** [comment]
Should still happen.
