### ISSUE TITLE
Use consistent module names

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#444]
The tracking and vertexing modules are inconsistently named/organized. Switch to the following consistent organization
```
Acts/TrackSeeding/ # was Seeding 
Acts/TrackFinding/  # was Fitter  
Acts/TrackFitting/    # was TrackFitter
Acts/VertexSeeding/ # was Vertexing
Acts/VertexFinding/  # was Vertexing
Acts/VertexFitting/    # was Vertexing
```
Seeding and finding algorithms could also be grouped together into `{Track,Vertex}/Finding` modules.

**Comment by paulgessinger** [comment]
I think we shouldn't do this without @baschlag's input, so we won't make it in time for `v1.0.0` (if we don't delay that until after he's back).

**Comment by msmk0** [comment]
That is true. I'll move it to `next`.

**Comment by msmk0** [comment]
I reconsidered this. I think we should at least rename the current `Fitter` and `TrackFinder` modules to `TrackFitting` and `TrackFinding` and leave everything else as-is. I prefer `Track{Finding,Fitting}` over `Track{Finder,Fitter}` since the modules can not only contain fitter and finder classes but also related helpers; but everything is related to finding and fitting tracks. This would also be consistent with the `Seeding` and `Vertexing` naming.
