### ISSUE TITLE
Remove the Legacy plugin

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#446]
It is not used anywhere within our code base.

**Comment by paulgessinger** [comment]
I think it includes the cleaned up ATLAS seeder reference.

@robertlangenberg ?

**Comment by robertlangenberg** [comment]
Yep, we had the discussion before. The reference may be helpful to compare the ATLAS and the Acts seeding in depth as there were still small differences. If we decide we won't do this, this can indeed go.

**Comment by paulgessinger** [comment]
Doesn't hurt to keep it around, make sure it continues compiling (I think it's compiled in the CI), if we want to go back and compare at some point. Closing this for now.

**Comment by msmk0** [comment]
It is only compiled in one integration test and not compared with anything else. Neither is it used in any of the examples. In the mean time, the other seeding implementations have progressed quite a bit and I am not sure if this is even still comparable or usable.

**Comment by paulgessinger** [comment]
But it compiles, so it should be ~ straight forward to revive if necessary. Not the case if you go back in git history to try and dig it up.

**Comment by robertlangenberg** [comment]
> he other seeding implementations have progressed quite a bit

The Acts CPU seeding implementation has not changed regarding it's output since it was first included. The GPU versions are striving to mimick the exact behavior of the CPU implementation. Therefore it should indeed be very much comparable.

**Comment by msmk0** [comment]
But they are comparing to the Core version of the seeder, right? Not to the one in the Legacy plugin.

**Comment by robertlangenberg** [comment]
Comparison has always been manual. The tests showing agreement between the Acts CPU impl and the GPU impls is not in the repo.

**Comment by msmk0** [comment]
Following yesterdays discussion in the meeting, the legacy plugin stays in.
