### ISSUE TITLE
Rename the GeometryID

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#447]
The `GeometryID` is the only case where we use an abbreviation in the type name. This is inconsistent with our naming guidelines. A possible consistent name would be `GeometryIdentifier`.

**Comment by paulgessinger** [comment]
I think `GeometryID` is perfectly fine. Let's not make changes for the sake of making changes.

**Comment by msmk0** [comment]
That is why I tagged this as needs-decision. So we can decide whether to do that or not. If we decide to do this, it should be done now or probably not at all.

**Comment by paulgessinger** [comment]
Ok, let's discuss, sure!

**Comment by msmk0** [comment]
Decision: rename the class to `GeometryIdentifier` but leave the `geometryId()` accessors as-is.
