### ISSUE TITLE
Propagator returns parameters by value

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#449]
The propagator result struct contains the final parameters as a `std::unique_ptr`. It should be stored by-value to reduce allocations and improve memory locality.

**Comment by paulgessinger** [comment]
Can the parameter type not vary?

**Comment by msmk0** [comment]
The result is templated on the the input parameters type and none of the existing track parameters classes export any virtual interface that would allow substitution. There is also #450 to consider.

I tagged this as needs-decision, because I do no think that this can go into `v1.0.0` and we should decide that in the meeting.

**Comment by asalzburger** [comment]
Hi, this we should discuss today, as this would be an API change of a core component I would consider as frozen.

**Comment by msmk0** [comment]
Summary from the discussion:
- Polymorphism is not needed. The type of the return parameters is fixed at the time of the `.propagate(...)` call.
- We need to support the case of a premature abort when propagating to a surface. Can be already supported since curvilinear parameters are just bound parameters in disguise, i.e. the returned track is represented as bound parameters on the curvilinear surface at the last propagation position.
- Output parameters can be optional. If stored by-value it should be something like `std::optional`.
- We might benefit from having less memory indirection, but this needs to be checked with proper benchmarks.

The decision was to not change this for now.

**Comment by msmk0** [comment]
After looking at the interface again, I still do not understand why the returned parameter has to be optional. The result struct is wrapped in an additional `Result<...>`; a true propagation error should be communicated through the corresponding result error and the returned parameter is not accessed anyways.

So my question is: in what circumstance could the propagation succeed but the resulting parameters would be undefined? If there is none, than there would not be a need for either `std::unique_ptr` or `std::optional` and we can return parameters object directly.

A similar argument applies to the propagation Jacobian: whether this one is computed or not only depends on the input parameters of the `.propagate(...)` call. If the input parameters have a set covariance, the Jacobian is computed. Thus, the caller already knows if the propagator should return one or not (and if it does not it would be an error that should be propagated via `Result<...>`). Thus, the Jacobian could then also be stored by-value with a sensible default (e.g. identity).

**Comment by paulgessinger** [comment]
Abort by an aborter is not a `Result::failure` and shouldn't be.

**Comment by msmk0** [comment]
I aggree, but in that case we still return a parameters object.

**Comment by paulgessinger** [comment]
That's just an example of why abort should not be `Result::failure`. I could imagine that there are abort conditions for which a returned parameter does not make a log of sense. I think in the case of the path reached aborter, this is sort of clear. Here, it would make sense to return free parameters. That doesn't currently work, but might be what we want.

**Comment by msmk0** [comment]
In the case that the maximum path has been reached, we would still return the curvilinear parameters at the last position, right?
