### ISSUE TITLE
Polyhedron surfaces tests are disabled

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#454]
The polyhedron surfaces tests in `Tests/UnitTests/Core/Surfaces/PolyhedronSurfacesTests.cpp` is not part of the CMake build. It should be re-added and updated to the latest changes in master.

**Comment by paulgessinger** [comment]
@asalzburger what's the status here?

**Comment by asalzburger** [comment]
Will check.

**Comment by robertlangenberg** [comment]
@asalzburger offered to take a look
