### ISSUE TITLE
Track inconsistencies in the ImpactPointEstimator tests

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#455]
The parameters changes introduced in #443 lead to a failure in one test for the `ImpactPointEstimator`. Comparing impact point estimates from multiple tracks for consistency seems to fail for one particular track. It is unclear, whether this is a bug or a transient error e.g. due to numerical instabilities.

The test is currently disabled to avoid blocking #443 any further (`Tests/UnitTests/Core/Vertexing/ImpactPointEstimatorTests.cpp`, lines 296-305).

**Comment by baschlag** [comment]
I don’t like seeing a test just being disabled when it fails after introducing changes. The entire vertexing relies on these estimators and it’s crucial to know that they still work as intended

**Comment by baschlag** [comment]
So @msmk0 could you please make sure that the changes you've introduced do _not_ cause any problems in ImpactPointEstimator and hence in the vertexing?

**Comment by baschlag** [comment]
@msmk0 ping.

**Comment by msmk0** [comment]
My apologies. As discussed this morning, I will have a look.
