### ISSUE TITLE
HepPDT no longer publicly available

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#456]
Hello,

I just wanted to make you aware that the (sort of) dependency, HepPDT, is no longer publicly available. It seems the LGC servers have been shut down. The following links don't work:
- http://lcginfo.cern.ch/pkg/HepPDT (from the RTD page)
- http://lcgapp.cern.ch/project/simu/HepPDT/download/ (via google)

**Comment by HadrienG2** [comment]
The spack HepPDT package has recently been updated to use the following URLs:

- Website: https://cdcvs.fnal.gov/redmine/projects/heppdt/wiki
- Source code mirror: https://lcgpackages.web.cern.ch/lcgpackages/tarFiles/sources/HepPDT-2.06.01.tar.gz

Though that certainly does not void your underlying point regarding long-term maintenance of this package, hopefully it can help you in what you are trying to do?

**Comment by msmk0** [comment]
I think we can get rid of the package altogether. Our Fatras module already carries a PDG particle listing with the relevant quantities.

**Comment by whit2333** [comment]
@HadrienG2, Indeed the spack package saved us, but if the dependency can be removed that would be even better. 

Feel free to close this issue.

Cheers

**Comment by whit2333** [comment]
@msmk0 Outside of Fatras, is there another library that provides the PDG particle codes that is maintained? Do you have any recommendations?

Thanks.

**Comment by msmk0** [comment]
I do not really know. Typically, the PDG values are set e.g. by the generators and then passed through.

**Comment by msmk0** [comment]
To generate the particles tables within `ActsFatras`, I used the [particle](https://pypi.org/project/particle/) Python package. That is a nice (non-C++) package to access particle information.

**Comment by whit2333** [comment]
@msmk0 Thanks!
