### ISSUE TITLE
Evolve SourceLink to handle Surface and Volume measurements

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#463]
This has already been brought up by @FabianKlimpel once: if we want to include free measurements that are not bound to a surface, then the current `SurfaceLinkConcept` is not sufficient/too restrict.

Requiring a `const Surface& referenceSurface()` is certainly not suitable for volume based measurements, unless we create a special `PositionSurface`, but this will be difficult to fit into the `Surface` base class.

One related question, why do we require the following?
```c++
  constexpr static bool default_constructible =
      std::is_default_constructible_v<T>;
  static_assert(default_constructible,
                "Source link must be default-constructible");
```

That sounds counter-intuitive to requiring a `const Surface& referenceSurface() const` in the Concept.

*Summary of the discussion* (so far):

The `SourceLink` would be changed from requiring a `referenceSurface()` method to providing the `GeometryIdentifier`.

This would allow:
 - identify if the source-linked geometry object is a volume or a surface 
 - keep one consistent requirement between the two measurement types
 - have a primitive type 

At the same point the TrackingGeometry should get a fast access to Surfaces or Volumes given a GeometryIdentifier object.

**Comment by asalzburger** [comment]
Tagging @msmk0 @paulgessinger and @XiaocongAi  to allow for discussion.

**Comment by paulgessinger** [comment]
I think we use the fact that they need to be default constructible in the fitters. We should be careful not to implicitly have the requirement if we drop this.

**Comment by FabianKlimpel** [comment]
As far as I remember the uncalibrated measurements in the MultiTrajectory also relies on a default constructor due to memory allocation before the actual assignment.

**Comment by XiaocongAi** [comment]
I think @paulgessinger and @FabianKlimpel are talking the same thing. The `MultiTrajectory::addTrackState` will allocate memory for the source link as only as the mask for `Uncalibrated` is true. Unless we add another parameter for the source link in the `addTrackState` method, we need to make the source link default-constructible.

**Comment by osbornjd** [comment]
There was some discussion today in the developer meeting about templating the `SourceLink` such that a volume or surface would be supplied by the user with a particular `SourceLink` that would then determine whether or not free or bound parameters would be necessary. From a user's perspective, I think this would be a nice solution as it:
1. Minimally impacts the outward API.
2. Continues to mask the measurement infrastructure from the user, such that the very simple `SourceLink` object would contain the necessary information to construct the measurements used by ACTS.
3. Allows the `SourceLink` object to continue to be a "middle man" between the experiment specific cluster object and ACTS measurement object. Currently, in sPHENIX, the `SourceLink` essentially only contains the identifier necessary to map a particular `SourceLink` back to the original sPHENIX cluster object (we call it an `SvtxCluster`).

I think templating the `SourceLink` would allow this object to maintain all three of these nice user facing API features.

**Comment by asalzburger** [comment]
@msmk0 had some other good suggestion - the `SourceLink` could actually be required to return the `GeometryID`, which would perfectly and uniquely identify either a `Surface` or a `Volume`. The `KF` and `CKF` do really need the `Surface` itself, the `Surface` will be provided by the navigator or the geometry (we can add this) - what do people think?

**Comment by asalzburger** [comment]
@XiaocongAi what do you think about this?

**Comment by paulgessinger** [comment]
Hm, but the KF ideally for a (re-)fit run would only target the surfaces identified by the GeometryID. Sure, this can be done via a map lookup, but I would think it's prefferable to avoid that if possible.

**Comment by XiaocongAi** [comment]
This idea makes much sense to me. @paulgessinger Currently, we are already using a map lookup for the source link, no?

**Comment by asalzburger** [comment]
True, though the refit would then ignore passive material, if not stored multi-trajectory, right?

Probably we need to set up a dedicated discussion meeting for this.

**Comment by paulgessinger** [comment]
> This idea makes much sense to me. @paulgessinger Currently, we are already using a map lookup for the source link, no?

That's true, actually.

**Comment by paulgessinger** [comment]
Would this affect your side of things, @osbornjd? I think the items brought up by you should still be fulfilled by switching the reference data type, right?

**Comment by XiaocongAi** [comment]
> So basically we only change the key from Surface* to GeometryID

Yeah, that's exactly what I have in mind.

**Comment by msmk0** [comment]
This also has the benefit of solving @asalzburger original question: all required source link methods return values and not interfaces and requiring the source link to be default constructible is well-defined again.

**Comment by paulgessinger** [comment]
... where the `GeometryID` can then potentially be `0` if default-constructed.

**Comment by msmk0** [comment]
Exactly.

**Comment by osbornjd** [comment]
After reading this discussion, I think that is actually a better solution. That will still keep the outward facing API very simple and, as was already stated, is in some sense already required anyway since the `SourceLink` must be created with an associated `Surface`. Providing the `GeometryID` is essentially the same thing from our side, since we already have to have some code which maps our Geant `TGeoNode` to the Acts `Surface` - so instead of providing the `Surface` in the `SourceLink` creation we just provide the `surface->geoId()`.

**Comment by asalzburger** [comment]
I like where this is going to ... @FabianKlimpel any inputs?

**Comment by paulgessinger** [comment]
Perfect, lets do that then. @asalzburger can you update or replace this issue to reflect this more clearly?

**Comment by asalzburger** [comment]
I will ...

**Comment by XiaocongAi** [comment]
Sorry that I want to bring up a non-relevant issue which I always want to ask. Is it possible to use externally provided geometry ID instead of internally assigned ones when constructing the tracking geometry in Acts? I could imagine that the users might want to have a fixed geometry ID for a physical detector module.

**Comment by paulgessinger** [comment]
In an experiment aware context, you can get the associated detector element from your surface, `static_cast` that to the experiment specific subclass of `Acts::DetectorElementBase` and access the identifier from there. We intentionally removed the requirement of an identifier from the interface in favor of this approach.

**Comment by asalzburger** [comment]
> Sorry that I want to bring up a non-relevant issue which I always want to ask. Is it possible to use externally provided geometry ID instead of internally assigned ones when constructing the tracking geometry in Acts? I could imagine that the users might want to have a fixed geometry ID for a physical detector module.

The real problem I see there is that one needs to have consistency, but actually, we could do this ... at the moment, the GeometryID is created at closing stage of the Geometry, where we already have something like a Material decorator, one could provide a GeometryID decorator as well, with the default implementation being the one done right now, i.e. the recursive creation of GeometryID values.

**Comment by paulgessinger** [comment]
I think we should ideally keep this separate. Do you have an example of where the `associatedDetectorElement()` approach is not sufficient?

**Comment by asalzburger** [comment]
The GeometryID should however always be paired with an Interpreter, which allows you to subclass the object into sensitive, boundary, volume, etc.

**Comment by paulgessinger** [comment]
I think it would be best to keep these concepts separate. We did have an explicit experiment-specific `Identifier` type before that fulfilled exactly this role, before removing it.

**Comment by msmk0** [comment]
> The GeometryID should however always be paired with an Interpreter, which allows you to subclass the object into sensitive, boundary, volume, etc.

I do not think that @XiaocongAi is asking to replace the `GeometryIdentifier` class but to preassign fixed values to certain parts of the geometry. I understand that that is currently not possible as they are auto-generated, but I think that would be really nice to have.

**Comment by paulgessinger** [comment]
Anyway, let's have that discussion on a separate issue, I'd suggest.

**Comment by XiaocongAi** [comment]
> I do not think that @XiaocongAi is asking to replace the GeometryIdentifier class but to preassign fixed values to certain parts of the geometry. 

Exactly!

**Comment by XiaocongAi** [comment]
Yeah, sorry,  let's move to a separate issue.

**Comment by asalzburger** [comment]
> Yeah, sorry, let's move to a separate issue.

I will create one.
