### ISSUE TITLE
Investigate if/Implement possibility that GeometryIdentifier to be externally provided

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#469]
The `GeometryIdentifier` is currently auto-generated at geometry closing stage, where recursively the `GeometryIdentifier` is defined by walking down the hierarchy tree. There might be interest to change the actual numbers of the `GeometryIdentifier` and its interpretation from the client side:

First it should be investigated:
 - [ ] can the assignment be changed into a Decorator structure as for the Material ?
 - [ ] can this be implemented with a corresponding structure that still allows to cast out sensitive_id/layer_id/volume_id ?

If so, a prototype implementation can be tried out.

**Comment by asalzburger** [comment]
For discussion: @paulgessinger @msmk0

**Comment by paulgessinger** [comment]
I think we shouldn't allow changing the meaning of the components. I have no objections in trying to have client code pre-determine what those numbers will be, as long as we implement a sanity-check at geometry closure.

**Comment by paulgessinger** [comment]
One possibility would be to have a client-provided visitor that is invoked during the recursion at geometry closure when set. However, that would maybe require us to sort out the fact that we currently `const_cast` in that recursion to be able to set the identifier.

**Comment by msmk0** [comment]
Agreed. A user-provided tool could provide a custom `GeometryIdentifier` value. The tracking geometry would then have to validated that that value matches the hierarchy and fail hard if it does not.
