### ISSUE TITLE
We require more benchmark coverage!

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#49]
[GitLab issue: #574](https://gitlab.cern.ch/acts/acts-core/issues/574)

ACTS should have more and better benchmarks. Obviously, we're not talking about studying every single line of code in a unit test-like fashion, but we should aim to have easy-to-use microbenchmarks of every component that's known or expected to be performance-critical for at least some ACTS users (e.g. Geometry, EDM, Propagator/Stepper, Kalman Fitter, BField map, Seeding...).

This way, it becomes easy to assess the performance impact of large changes of ACTS and go on a profiling hunt for areas of improvement. In fact, we could even envision to detect regressions automatically if someone can lend us a bit of dedicated hardware for that.

As the toolkit matures, we should also keep the acts-framework examples up to date and improve them, so that it's possible to run a set of semi-realistic tracking scenarios that invoke all major ACTS components, and check how computation time is spread across ACTS components. This allows checking the assumptions that we need to make at this development stage re. what's perf-critical and what isn't.

This issue is half open-ended. Some things we can do today (identify perf-critical components in the current ACTS codebase and write microbenches for them), some things we must continuously keep in mind as ACTS development marches on.

**Comment by asalzburger** [comment]
Issue without clear objectives, we should specify and identify code that needs more coverage and then create specific issues.
