### ISSUE TITLE
Calculating initial parameters as part of seeding?

### ISSUE THREAD

**Issue by robertlangenberg** [acts-project/acts#490]
Pierfrancesco has asked how to plug the seeding into the CKF, since the seeding only provides three measurements instead of initial parameters. In principle, I agree that the seeding should return initial parameters but since it should be more accurate than what the (current) seeding algorithm can do... should the seeding run the CKF? @FabianKlimpel @asalzburger

**Comment by FabianKlimpel** [comment]
The seed should provide some initial parameters and from what I know about your implementation it should be derivable from the concept.
Do I understand it correctly that you want to use the CKF as seeding algorithm?

**Comment by pbutti** [comment]
Just to comment on this topic: CKF should need initial track parameters to start the algorithm. I was hoping that the Seed class would store the initial parameters from the seed finding procedure (they should be available after the circle+line fit, but I'm not sure what you mean with "derivable from the concept"), but the seeds are just a collection of 3 points. Is it expected to run a separate fit on those points by clients or perhaps one could integrate the storage of initial parameters of the seeds in ACTS?

**Comment by FabianKlimpel** [comment]
By concept I meant this combination of individual points, so I think we mean the same thing.
If one intends to use the CKF as seeding algorithm and later on uses the CKF for the actual track finding then the parameters might be biased since the measurements providing the initial parameters are used twice in this case unless the corresponding measurements are neglected in the track finding.

**Comment by pbutti** [comment]
Hi Fabian, 
I wouldn't use CKF for seeding. 
What I think could be added to the Seed class are the LinCircle parameters to then start the TrackFinding. Does this make sense or you suggest to perform a new fit to extract them out of the 3 selected space points?

**Comment by robertlangenberg** [comment]
I thought that wouldn't be the case, as the fitting is updated for each measurement, but you're the expert. I also thought the initial direction from the seedfinder would be too inaccurate as it assumes perfect magfield and doesn't know much about the material. I'm quite sure the seedfinder doesn't actually return this in ATLAS. Maybe @asalzburger can chime in or I can try to find how it's done in ATLAS.

**Comment by pbutti** [comment]
Sorry, to spam here but I think I found the answer in lxr. 

I wonder if shouldn't be a possibility to implement this:
https://acode-browser.usatlas.bnl.gov/lxr/source/athena/InnerDetector/InDetRecTools/SiTrackMakerTool_xk/src/SiTrackMaker_xk.cxx
Line 811 to form an estimate of the track parameters at the first surface of the seed. 
Anyway, I let Andi chime in. 

Cheers and thanks. 
PF

**Comment by robertlangenberg** [comment]
Well done! I think that's what it is and what probably should be done by the track seeder.

**Comment by asalzburger** [comment]
@XiaocongAi has @pbutti and he will find some time in the next weeks to work on this.

**Comment by XiaocongAi** [comment]
This is handled in #621 .

**Comment by robertlangenberg** [comment]
fixed in #621
