### ISSUE TITLE
fix: review relative tolerance for CylinderSurface

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#495]
Coming from ATLAS, there is a relative tolerance setting for CylinderSurface onSurface checks. This was however within a different Propagator setup w/o overstepping and dynamic tolerance control.

We should check/fix if an outside tolerance provided is possible as well in ACTS (harmonised with other Surfaces).

Original post:

That actually comes from ATLAS, I think we try in a separate PR if we omit this awkward scaling.

_Originally posted by @asalzburger in https://github.com/acts-project/acts/pull/494#r496787209_

**Comment by msmk0** [comment]
@asalzburger Is this still relevant or has this been fixed in the meantime?

**Comment by robertlangenberg** [comment]
@asalzburger ping!
