### ISSUE TITLE
[Improvement] Copy-pastee build instructions for lxplus-like environment.

### ISSUE THREAD

**Issue by andriish** [acts-project/acts#502]
Hi all,

it would be nice to have build instructions for lxplus-like environment.

Best regards,

Andrii

**Comment by asalzburger** [comment]
Hi,

There are `lxplus` instructions in the getting started guide:

https://github.com/acts-project/acts/blob/master/docs/getting_started.md

Let me know if there is a problem with the guide, we are happy to clarify/update of course.

Cheers,
Andreas

**Comment by andriish** [comment]
Hi  @asalzburger , thanks! 
Just found it by myself a second ago!
But haven't tested.

Best regards,
Andrii
