### ISSUE TITLE
Directed Navigation KF Fit Non-Functional

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#508]
The directed navigation in the KF is out of date with recent changes (e.g. to the templated struct `KalmanFitterOptions`). It should be updated, probably with an explicit example class such that the compiler will be a "reminder" to update this function with changes to the Acts code.

For example, compare [this](https://github.com/acts-project/acts/blob/b88b0759b9ec529d1200377e8ab015669cab0650/Core/include/Acts/TrackFitting/KalmanFitter.hpp#L1052) line and this [line](https://github.com/acts-project/acts/blob/b88b0759b9ec529d1200377e8ab015669cab0650/Core/include/Acts/TrackFitting/KalmanFitter.hpp#L960), which show that the `PropagatorOptions` takes three arguments on construction now instead of the previous two.

**Comment by osbornjd** [comment]
I can work on tackling this, as I already developed some code which revealed the bug.

**Comment by osbornjd** [comment]
Digging into this further, it looks like this might actually be above my head. Modifying the KFOptions interfaces in the KalmanFitter reveals additional compiler errors related to the `DirectNavigator::State` having incompatible named objects with the `Navigator::State`. In particular, it looks like the `Navigator::State` is much more complex than the `DirectNavigator::State`, in that it has an enum of stages it can take and can also access layers in addition to volumes and surfaces.

Can a navigation expert confirm - is the `DirectNavigator` class out of date with regards to the scheme in which it actually navigates through surfaces, or is it just fundamentally different than the `Navigator`? If it is the second, then the `Actor` of the KF will have to be modified, while if it is the first then it is probably best for a navigation expert to address this issue.

**Comment by asalzburger** [comment]
This is handled with #521
