### ISSUE TITLE
DD4hep Plugin and DD4hep_SubdetectorAssembly

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#509]
Hello,

In defining a `DD4hep_SubdetectorAssembly`, as is done [here](https://acts.readthedocs.io/en/latest/plugins/dd4hep.html#prerequisites), what is the role of the "shape" and is it needed for ACTS? I believe `DD4hep_SubdetectorAssembly` will use an assembly if no shapes are provided. 

When the shape is included, it creates overlaps which I find using DD4hep's `checkOverlaps` tool. If I make shape the envelope of the subdetectors, then there is then 100% overlap with the subdetector's volumes. 

Thanks!

**Comment by whit2333** [comment]
@asalzburger , can you confirm the overlaps show up in the OpenDataDetector?

![image](https://user-images.githubusercontent.com/2065918/95615610-1b6f8980-0a2e-11eb-8f16-e67d61569cf9.png)

**Comment by asalzburger** [comment]
Apologies for the delay - collaboration SW took a bit of time out this week. Will come back to this early next week.

We have allocated new person power to fully validate the OpenData detector, so we can start with this question I believe.

**Comment by whit2333** [comment]
Let me know if there is anything I can do to help. Here is a link to the DD4hep [SubdetectorAssembly source](https://dd4hep.web.cern.ch/dd4hep/reference/SubdetectorAssembly__geo_8cpp_source.html).

**Comment by asalzburger** [comment]
WE have still a similar request with #430. Probably we can join these two issues and define a feature request (as discussed in the developer meeting).

**Comment by whit2333** [comment]
Well, I think the answer to my question is that the shapes do nothing in the dd4hep plugin. I think they are only to color the different detector regions red, green, and blue like in figure above.

Is this correct? If so please feel free to close the comment.
