### ISSUE TITLE
Streamline: covarianceTransport and covTransport  (was ACTS-539)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#52]
[GitLab issue: #540](https://gitlab.cern.ch/acts/acts-core/issues/540)

Original author Andreas Salzburger @ asalzbur

Streamline the naming of covTransport and covarianceTransport() for the EigenStepper and AtlasStepper.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:53:15](https://gitlab.cern.ch/acts/acts-core/issues/540#note_2484674)

 Original author ATS Jenkins @ atsjenkins

[Andreas Salzburger](https://gitlab.cern.ch/asalzbur) mentioned this issue in [a merge request of acts/acts-core](https://gitlab.cern.ch/acts/acts-core/merge_requests/458):
'Material memory update and mapping synchronization'

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-03-28 11:41:20](https://gitlab.cern.ch/acts/acts-core/issues/540#note_2486379)

 What do we think here? I think @ fklimpel changed around some things. Can you say what the situation is?

**Comment by paulgessinger** [comment]
[Original comment by: fklimpel at 2019-05-27 16:41:29](https://gitlab.cern.ch/acts/acts-core/issues/540#note_2615005)

 Imo this can be closed

**Comment by paulgessinger** [comment]
@msmk0, you were working on something along these lines right?

**Comment by msmk0** [comment]
Yes, @FabianKlimpel and me are still working on this.

**Comment by asalzburger** [comment]
This is anyway renamed already `performCovarianceTranspor` and `covarianceTransport`, which serves the purpose I'd say.
