### ISSUE TITLE
Bug or reasonable difference in propagator?

### ISSUE THREAD

**Issue by baschlag** [acts-project/acts#538]
During the integration of the ACTS AMVF in Athena we see weird behaviour in the Acts propagator (which seems to be the reason for the CI failing in the [Athena MR making Acts AMVF the default](https://gitlab.cern.ch/atlas/athena/-/merge_requests/37283)):

## q221(MC): Propagator works
During the vertex finding procedure, track parameters need to propagated to a target surface. In the q221 (MC) jobs, this works perfectly fine with the Acts propagator: The Acts propagator output matches almost perfectly the desired output of the Athena counterpart:

For both Athena and Acts, we start with the exact same track parameters/cov
```bash
startParams:   -0.0221815
     31.1604
     1.00391
     0.22439
-0.000381957
startCov:     0.054821 -0.000948335  -0.00164172 -6.97253e-06 -3.71139e-07
-0.000948335      1.10029  0.000144049   0.00161201 -3.44353e-08
 -0.00164172  0.000144049  5.01301e-05  3.80508e-07  1.80901e-08
-6.97253e-06   0.00161201  3.80508e-07  2.39546e-06 -2.01608e-11
-3.71139e-07 -3.44353e-08  1.80901e-08 -2.01608e-11  1.59298e-10
```
and target surface with (normal/rotation/translation):
```bash
targetsurface: normal0.119543
0.187672
 0.97493
targetsurface: transform rot -0.453819   0.883039   0.119543
 -0.863053  -0.468954   0.187672
  0.221782 -0.0180025    0.97493
targetsurface: transform translation   -0.5
   -0.5
29.9303
```
In the q221 jobs, the track parameters after propagation match perfectly:
Athena:
```bash
params after prop:     0.274617
-3.64911e-08
     1.00363
     0.22439
-0.000381957
cov after prop:    0.0553702  0.000204313  0.000109909  0.000360974  2.22684e-08
 0.000204313    0.0556698   0.00165167 -2.22035e-05  3.75411e-07
 0.000109909   0.00165167  5.01464e-05  2.07757e-08  1.82123e-08
 0.000360974 -2.22035e-05  2.07757e-08   2.3959e-06 -2.02366e-11
 2.22684e-08  3.75411e-07  1.82123e-08 -2.02366e-11  1.59298e-10
```
Acts (modulo a 10e3 factor for GeV/MeV conversion):
```bash
params after prop:     0.274617
-3.64277e-08
     1.00363
     0.22439
   -0.381957
cov after prop:    0.0553702  0.000204313  0.000109909  0.000360974  2.22684e-05
 0.000204313    0.0556698   0.00165167 -2.22035e-05  0.000375411
 0.000109909   0.00165167  5.01464e-05  2.07758e-08  1.82123e-05
 0.000360974 -2.22035e-05  2.07758e-08   2.3959e-06 -2.02366e-08
 2.22684e-05  0.000375411  1.82123e-05 -2.02366e-08  0.000159298
```
This is consistent throughout the entire vertexing procedure and the final results (in terms of vertices etc) match perfectly.

## q431 (data): Propagator fails?
For the q431 job (data, causing the CI to fail) however we see something weird: 
Even though we (again) start with the exact same track parameters/cov and the same target surface, e.g.
```bash
startParams:   -0.371565
     38.382
  -0.295243
    2.89637
-0.00029725
startCov:    0.0313482    0.0153704 -0.000889735   1.9054e-05 -2.74565e-07
   0.0153704     0.497015 -0.000364382  0.000835053 -6.87239e-08
-0.000889735 -0.000364382  2.62282e-05 -4.78563e-07  1.22657e-08
  1.9054e-05  0.000835053 -4.78563e-07  1.44215e-06 -7.53549e-11
-2.74565e-07 -6.87239e-08  1.22657e-08 -7.53549e-11  1.09102e-10
```
and
```bash
targetsurface: normal  0.232297
-0.0705376
 -0.970084
targetsurface: transform rot  0.645113   -0.72792   0.232297
 -0.735248  -0.674117 -0.0705376
  0.207941  -0.125291  -0.970084
targetsurface: transform translation-0.495723
-0.891667
  33.3359
```
we get different end parameters after the propagation:
Athena:
```bash
params after prop:    0.718249
0.000709028
  -0.294803
    2.89637
-0.00029725
cov after prop:    0.0258374 -0.000644707  0.000400159  0.000160719  1.27507e-07
-0.000644707    0.0326876  0.000775795  -0.00011876  2.35211e-07
 0.000400159  0.000775795  2.60801e-05  -3.3395e-07  1.20922e-08
 0.000160719  -0.00011876  -3.3395e-07  1.44205e-06 -7.52963e-11
 1.27507e-07  2.35211e-07  1.20922e-08 -7.52963e-11  1.09102e-10
```
vs. Acts:
```bash
params after prop:    0.720224
7.10543e-14
  -0.294804
    2.89637
   -0.29725
cov after prop:    0.0258466 -0.000651326  0.000400072  0.000160771  0.000127492
-0.000651326     0.032692  0.000775855  -0.00011878  0.000235222
 0.000400072  0.000775855  2.60804e-05 -3.34278e-07  1.20926e-05
 0.000160771  -0.00011878 -3.34278e-07  1.44215e-06 -7.53549e-08
 0.000127492  0.000235222  1.20926e-05 -7.53549e-08  0.000109102
```
There are cases where the differences are even bigger and they may not seem large here, but given that they almost match 100% in the case of MC, it is weird that they never do for data. These tiny differences unfortunately lead to quite big differences (due to inversion etc.) in track weights which eventually explode and the vertexing results are significantly different compared to the Athena version.
- We checked the magnetic field, which is alright and does not seem to be wrong. 
- Geometry should not make any difference here (?), since we are in the beam pipe for the vertexing. 
- I get the same results if I run this in Acts standalone.

Do you have any ideas what could go wrong here and what the reason could be? Noemi and me couldn't figure it out so far.
This is a blocker for the Acts AMVF integration in Athena. Any help is appreciated.

Thanks a lot!
@paulgessinger @asalzburger @msmk0 @robertlangenberg @FabianKlimpel @Corentin-Allaire

**Comment by paulgessinger** [comment]
The target is a virtual surface? So can't be affected by alignment or anything, right?

**Comment by paulgessinger** [comment]
Related question: do we even expect numerical identity w.r.t. to the ATLAS propagation?

**Comment by FabianKlimpel** [comment]
"I get the same results if I run this in Acts standalone."
Same difference between AtlasStepper and EigenStepper or the same result for the EigenStepper in Acts & Athena?

**Comment by asalzburger** [comment]
After discussing with @baschlag - I think the issue is the following:
- in MC we use a nominal beam line in ATLAS w/o tilt, hence the q221 test runs through
- in data, however, we respect the beam tilt w.r.t ATLAS, i.e. the Vertexing runs in the beam line reference frame

We need to make sure the ActsAMVF wrapper picks up the beam condition CondAlg and uses this.

**Comment by baschlag** [comment]
This indeed seems to fix the issue and it is was not an ACTS-related problem. Thanks!

**Comment by asalzburger** [comment]
Great that this is understood!
