### ISSUE TITLE
Clean-up of GeantinoRecording files

### ISSUE THREAD

**Issue by FabianKlimpel** [acts-project/acts#539]
The Geant4 related files for the GeantinoRecording are still in a deprecated style (comments, print statements) and need some clean-up.

**Comment by Corentin-Allaire** [comment]
I was having a look at the Geantino recording to do some clean-up and I notice that in the SteppingAction still had commented code related to Geant4 full recording that was originally supposed to be split from the material mapping stepping action. @msmk0 you meantion in issue #111 that this would be needed soon, is it still the case ? If it is I can try to implement this as part of this issue and if not I will remove the comment.

**Comment by msmk0** [comment]
Yes, I think this still needs to be done.
