### ISSUE TITLE
Surface globalToLocal  question

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#544]
Hello,

I have a quick question about the surface globalToLocal function. [Here it says](https://github.com/acts-project/acts/blob/master/Core/include/Acts/Surfaces/Surface.hpp#L289)
>  Since some surface types need the global momentum/direction to resolve sign ambiguity this is also provided
...
>  @param momentum global 3D momentum representation (optionally ignored)

What types of surfaces need this direction/momentum parameter?

Could this parameter have a default value, eg `{0,0,0}`? I am guessing it is mostly not used?

Cheers,
Whit

**Comment by asalzburger** [comment]
Hi, 

it is only the straw surface and the perigee Surface (both line surface types) that need the momentum direction, and yes it is ignored for all other types.

It is part of the method signature to allow the same code in a polymorphic surface container. Not sure we want to default it there though (in the base class) but we could do so in the types that don't use it?
