### ISSUE TITLE
Test Coverage: Unit tests for geometric digitization (was ACTS-509)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#55]
[GitLab issue: #509](https://gitlab.cern.ch/acts/acts-core/issues/509)

Original author Andreas Salzburger @ asalzbur

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-04-08 15:56:53](https://gitlab.cern.ch/acts/acts-core/issues/509#note_2511537)

 I have added two unit tests, one for the `RectangleSegmentation`, one for the `PlanarModuleStepper`, both are part of  !542

**Comment by msmk0** [comment]
@asalzburger I will close this unless you object.

**Comment by asalzburger** [comment]
This can be closed the reworked Digitization from #388 will address this.
