### ISSUE TITLE
Propagator / Stepper rework for Free propagation

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#561]
Hey @msmk0, @FabianKlimpel, @XiaocongAi  and @HadrienG2 (for information).

I have started to play around with clarifying the roles of Stepper (+state), Propagator (+state), etc.
As we had discussed, a clearer separation would be:

- `Stepper`: does only the mathematical stepping in free parameters

- `Navigator`: finds out if we are on surface and returns this surface to the Propagator

- `Propagator`: takes `Surface` and `StepperState` and makes a `BoundState`, leaves `FreeState` either way.

Hence, the `ActionList`  would either run through an API on a `BoundState` or and a `FreeState`, never a mixture.
The actors are then allowed to modify the `BoundState` or `FreeState` and at the end of the ActionList the Propagator sets the new `StepperState` for continuation.

**Comment by asalzburger** [comment]
I have written two different types and benchmarked then:

- a `std::variant` version based on explicit dispatching:

```c++
// Variant generator test
  size_t num_iters = 0;
  const auto varaint_bench_result = Acts::Test::microBenchmark(
      [&] {
          auto state = stateGenerator(num_iters++);
          std::visit(overloaded {
            [&](FreeState& free) { std::for_each(consumers.begin(), consumers.end(), [&](const auto& c){ c(free);});  },
            [&](BoundState& bound) { std::for_each(consumers.begin(), consumers.end(), [&](const auto& c){ c(bound);});  }
        }, state);
      },
      1, toys);
```

And a second version on based on branching:

```c++

  // Branched generator test
  const auto branched_bench_result = Acts::Test::microBenchmark(
      [&] {
        if ((num_iters++)%2){     
          auto free = FreeState(stateGenerator.fGenerator.fpar, stateGenerator.fGenerator.fcov);       
          std::for_each(consumers.begin(), consumers.end(), [&](const auto& c){ c(free);});  
        } else {
          auto bound = BoundState(stateGenerator.bGenerator.lpar, stateGenerator.bGenerator.lcov);       
          std::for_each(consumers.begin(), consumers.end(), [&](const auto& c){ c(bound);});  
        }
      },
      1, toys);

```

They are practically the same in execution speed.

**Comment by asalzburger** [comment]
Most of the time spent in these examples is in creating the `FreeState` or `BoundState` - and here comes my worry for such a design.

In the current design, the `Actors` are kind of listeners and they jump into place when they appear to have an action to be done. E.g. The `KalmanActor` does not react on any surface that is reached, but only on ones that are sensitive and/or have a measurement attached. 

In the proposed design, however, we would create a bound state not on demand, but on any surface that is reached, which computationally certainly not ideal.

For the `FreeState` the situation is a bit more relaxed, as it exists already in some sort within the `StepperSate`.

**Comment by FabianKlimpel** [comment]
Sounds reasonable. Let me propose that we use a lazy evaluated object for the state: We use an object (for example the stepper state itself) that stores the state. An access could be performed via the `stepper.bound/freeState(state.stepping)` method. If a state was already created after a step, then a flag could indicate it or one could test that the jacobian is an identity. If it wasn't called after a step by any actor/aborter then it isn't created. From the perspective of an actor/aborter, it would be just a function call or a data access.

**Comment by asalzburger** [comment]
Hi, of course I thought about the lazy evaluation, but this will not work easily with the aim to decouple the bound/free translation from the Stepper. Will think about it.

**Comment by FabianKlimpel** [comment]
We pass in any case the propagator state through all actors/aborters. So a simple struct with a `boundState` and `freeState` getter could be passed as additional argument. This would need the `state.stepping` as argument in order to build the state. If you want to re-create this object after each step then you could implement an internal state variable e.g. as `std::optional` to indicate whether the state was already produced. If you would like to keep this object then one could either destruct the state after all actors/aborters are called or test whether the jacobian is an identity.

**Comment by asalzburger** [comment]
Yeah, I was thinking along the lines, I will update my mockup

**Comment by asalzburger** [comment]
Changing to use `std::optional` indeed is a good step.

```shell
11:54:59    ActionList     INFO      Execution stats (variant): 10000000 runs of 1 iteration(s), 488.2ms total, 0.0470+/-0.0000µs per run, 47.000+/-0.001ns per iteration
11:55:02    ActionList     INFO      Execution stats (branched): 10000000 runs of 1 iteration(s), 389.7ms total, 0.0380+/-0.0000µs per run, 38.000+/-0.001ns per iteration
11:55:05    ActionList     INFO      Execution stats (do nothing): 10000000 runs of 1 iteration(s), 383.9ms total, 0.0370+/-0.0000µs per run, 37.000+/-0.001ns per iteration
```

**Comment by asalzburger** [comment]
So, the infrastructure overhead from using `std::variant` via an explicit branching is ~100ms per 10 million steps, I will do a quick test how many steps we can expect for a single `<mu>~200` event.

**Comment by FabianKlimpel** [comment]
I assume `do nothing == std::optional`. How did you choose between bound and free states? Did you store both in the same object?

**Comment by asalzburger** [comment]
Do nothing is the pure execution time of the micro benchmark, which is mainly spent in clock time getting.

Now, properly timed, I think we can go with the `std::variant` type:

```shell
33.52% const auto branched_bench_result = Acts::Test::microBenchmark(
33.34% const auto varaint_bench_result = Acts::Test::microBenchmark(
33.11% const auto sterile_bench_result = Acts::Test::microBenchmark(
0.02% ACTS_INFO("Execution stats (variant): " << varaint_bench_result);
0.02% ACTS_INFO("Execution stats (branched): " << branched_bench_result);
```

**Comment by HadrienG2** [comment]
> Changing to use `std::optional` indeed is a good step.
> 
> ```shell
> 11:54:59    ActionList     INFO      Execution stats (variant): 10000000 runs of 1 iteration(s), 488.2ms total, 0.0470+/-0.0000µs per run, 47.000+/-0.001ns per iteration
> 11:55:02    ActionList     INFO      Execution stats (branched): 10000000 runs of 1 iteration(s), 389.7ms total, 0.0380+/-0.0000µs per run, 38.000+/-0.001ns per iteration
> 11:55:05    ActionList     INFO      Execution stats (do nothing): 10000000 runs of 1 iteration(s), 383.9ms total, 0.0370+/-0.0000µs per run, 37.000+/-0.001ns per iteration
> ```

Not sure if this is what you fixed when you talked about being "properly timed" in your later comment, but `Acts::Test::microBenchmark` is definitely _not_ meant to be used with runs lasting less than a fraction of microsecond. You should tune up the iteration count until the run duration is much longer than the time it takes to measure the clock and much shorter than your OS scheduler tick rate (20~80µs is a good compromise on my Linux machines).

**Comment by asalzburger** [comment]
Hi @HadrienG2, apologies, that was not a criticism of the `microBenchmark` which is super useful.

What I meant is that I ran it through a timing profiler and checked how much is spent inside the benchmark test.

**Comment by asalzburger** [comment]
Ok, here's my suggestion for the `Stepper` interface and access:

- we make all the members private but declare the `EigenStepper` friend of the `EigenStepper::State` 
- then all actors and aborts anyway have to go through the new lazily initialised Free/BoundState hierarchy
- the Steppers however have direct access for modifying the state (which should be optimal)

@FabianKlimpel @msmk0  - any thoughts?

**Comment by FabianKlimpel** [comment]
Where will you store the "new lazily initialised Free/BoundState"?
Making all things private sounds reasonable if applicable. I assume that the stepper classes would need more methods in order to modify all members of the state that are currently modified directly by actors/aborters. Maybe there are even more problems coming up that I cannot foresee but for the `AtlasStepper` a pure method based access to the state members is definitely the way to go

**Comment by msmk0** [comment]
I am not yet convinced that we need to introduce a lazily initialized bound state. What are the cases, in a typical propagation, where we arrive on a surface but do not require the local parametrization. For all detector surface, the local position is needed to lookup measurements, material, etc.. The same is true for approach surface that can hold material. This leaves boundary surfaces: can they hold material or are they always sterile?

With a lazily initialized state we might introduce quite a bit of code that has little effect in a realistic setup. In that case, I would prefer to keep the logic simple, i.e. always create the local presentation on all surfaces, and take the (hopefully minor) performance hit. Of course, this should be quantified, but I want to avoid that we commit to early to this lazy initialization scheme.

**Comment by paulgessinger** [comment]
My understanding was that @asalzburger asserted that creating a local state on all surface is prohibitively expensive. 
I could imagine this to be especially problematic for extrapolation through a calorimeter, or the TRT, with a **huge** number of surfaces.

If a surface does not have a measurement nor material attached, I don't think local parameters are neeed.

**Comment by asalzburger** [comment]
The problem is not so much the local parameterisation itself, that's `only` a local to global operation (however, that is not cost free). The actually problem is the transport of the covariance matrix and the transform into the surface frame.

```shell

2.06 s  100.0%	0 s	 	ActsIntegrationTestPropagationEigenConstant (36064)
2.06 s  100.0%	4.00 ms	 	 Acts::Result<Acts::RiddersPropagator<Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator> >::result_type_helper<Acts::SingleCurvilinearTrackParameters<Acts::SinglyCharged>, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> >::action_list_type>::type, std::__1::error_code> Acts::RiddersPropagator<Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator> >::propagate<Acts::SingleCurvilinearTrackParameters<Acts::SinglyCharged>, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> > >(Acts::SingleCurvilinearTrackParameters<Acts::SinglyCharged> const&, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> > const&) const
1.97 s   95.8%	3.00 ms	 	  std::__1::vector<Eigen::Matrix<double, 6, 1, 0, 6, 1>, std::__1::allocator<Eigen::Matrix<double, 6, 1, 0, 6, 1> > > Acts::RiddersPropagator<Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator> >::wiggleDimension<Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> >, Acts::SingleCurvilinearTrackParameters<Acts::SinglyCharged> >(Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> > const&, Acts::SingleCurvilinearTrackParameters<Acts::SinglyCharged> const&, unsigned int, Acts::Surface const&, Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, std::__1::vector<double, std::__1::allocator<double> > const&) const
1.86 s   90.2%	10.00 ms	 	   Acts::Result<Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator>::result_type_helper<Acts::SingleBoundTrackParameters<Acts::SinglyCharged>, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> >::action_list_type>::type, std::__1::error_code> Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator>::propagate<Acts::SingleBoundTrackParameters<Acts::SinglyCharged>, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> >, Acts::SurfaceReached, Acts::PathLimitReached>(Acts::SingleBoundTrackParameters<Acts::SinglyCharged> const&, Acts::Surface const&, Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<> > const&) const
1.14 s   55.3%	21.00 ms	 	    Acts::Result<Acts::PropagatorResult<Acts::SingleBoundTrackParameters<Acts::SinglyCharged> >, std::__1::error_code> Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator>::propagate_impl<Acts::PropagatorResult<Acts::SingleBoundTrackParameters<Acts::SinglyCharged> >, Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator>::State<Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<Acts::SurfaceReached, Acts::PathLimitReached> > > >(Acts::Propagator<Acts::EigenStepper<Acts::ConstantBField, Acts::StepperExtensionList<Acts::detail::GenericDefaultExtension<double> >, Acts::detail::VoidAuctioneer>, Acts::detail::VoidNavigator>::State<Acts::PropagatorOptions<Acts::ActionList<>, Acts::AbortList<Acts::SurfaceReached, Acts::PathLimitReached> > >&) const
527.00 ms   25.6%	7.00 ms	 	    Acts::detail::boundState(std::__1::reference_wrapper<std::__1::any const>, Eigen::Matrix<double, 6, 6, 0, 6, 6>&, Eigen::Matrix<double, 6, 6, 0, 6, 6>&, Eigen::Matrix<double, 8, 8, 0, 8, 8>&, Eigen::Matrix<double, 8, 1, 0, 8, 1>&, Eigen::Matrix<double, 8, 6, 0, 8, 6>&, Eigen::Matrix<double, 8, 1, 0, 8, 1> const&, bool, double, Acts::Surface const&)
472.00 ms   22.9%	5.00 ms	 	     Acts::detail::covarianceTransport(std::__1::reference_wrapper<std::__1::any const>, Eigen::Matrix<double, 6, 6, 0, 6, 6>&, Eigen::Matrix<double, 6, 6, 0, 6, 6>&, Eigen::Matrix<double, 8, 8, 0, 8, 8>&, Eigen::Matrix<double, 8, 1, 0, 8, 1>&, Eigen::Matrix<double, 8, 6, 0, 8, 6>&, Eigen::Matrix<double, 8, 1, 0, 8, 1> const&, Acts::Surface const&)
```

**Comment by asalzburger** [comment]
You really want to spend the time to do the `boundState(...)` only when needed.

**Comment by msmk0** [comment]
> If a surface does not have a measurement nor material attached, I don't think local parameters are needed.

As far as I understood it, you often need local parameters (maybe not the covariances) to lookup local materials and/or measurements.

I am not questioning the results that @asalzburger has shown. I am asking whether they are representative of a typical propagation in a full experiment. I fear that they are not. The integration tests propagate between just two surfaces; mostly in a constant field and for short distances. I expect there to be few (free) stepper calls for every to-surface transformation. Will this be the same for a real experiment where you have many steps, navigation overhead, etc.?

Some of the code in `covarianceTransport` and `boundState` might need to happen regardless of the potential lazy initialization. This is also running within the `RiddersPropagator` which runs the same propagation many times for a single particle; if the numbers are the totals, they are maybe overcounting the impact?

My aim here is to caution against prematurely implementing a particular solution until we have everything in place to measure its implact. We can move the surface handling to the `Propagator` without the lazy-initialization first. Then see how much the non-lazy initialization costs us and only if it is prohibitively then in a realistic setting, should we consider implementing it that way. Whether to handle the to-local transformation lazily or not is something that we do not need to decide now.

**Comment by asalzburger** [comment]
I also run the `PropagationTest` through the `TrackML` detector. Approach surfaces e.g. are often only necessary for doing the lookup of the surface candidates, and there's no much else to do.

Before we write lengthy paragraphs, lets make a test version and time it :-)

**Comment by paulgessinger** [comment]
@msmk, but you should be able to tell **if** a surface has a measurement just from the surface itself. And you can check **if** a surface has material without a location as well.

**Comment by msmk0** [comment]
Yes, that is true. As @asalzburger let's time a realistic version.

**Comment by msmk0** [comment]
Work is ongoing e.g. in #577 .

**Comment by robertlangenberg** [comment]
being worked on !744

**Comment by baschlag** [comment]
Reopening since I guess this is still WIP, isn't it? In fact, I'm still waiting for this feature to implement my generic track linearizer on top of it. Any news here on the current status?

**Comment by baschlag** [comment]
Hi @asalzburger, I haven't been following the status of this work in the last months. Is there any update regarding the rework? I still like to implement the generic track linearizer on top of it.
Cheers
