### ISSUE TITLE
Potential issue for non-collider detector

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#568]
One potential problem to use Acts for a non-collider detector aligned along global z is, when the track direction is parallel to global z, the covariance might have `Nan` value since the `sinTheta` is used in the denominator during the global<=>local jacobian transform, e.g. [here](https://github.com/acts-project/acts/blob/master/Core/include/Acts/Surfaces/detail/Surface.ipp#L86).
Another similar issue could be that, the update to the covariance matrix due to material effects might be very large if the `sinTheta` is close to zero, e.g. [here](https://github.com/acts-project/acts/blob/master/Core/src/Propagator/detail/PointwiseMaterialInteraction.cpp#L35).

**Comment by msmk0** [comment]
I do not think this is Acts-specific. This is a general feature of any parametrization using `theta`-like angles. They all have a parameter ambiguity/singularity. This can not be fixed.

For forward experiments one has to use either the free parametrization (which has no such singularity) or a true local parametrization, i.e. one where the two direction angles are defined e.g. as deviations from the local normal direction. These slope-like direction parameters have some other nice features, e.g. they allow conversion from free parameters without trigonometric functions, but adding them to Acts in a general fashion will be a huge amount of work.

**Comment by XiaocongAi** [comment]
Right, I think we don't have to worry about too much about this singularity issue, which happens only when the track direction has a `theta` at exactly `0`. This is very very unlikely to happen. If it really happens, the track reco will just fail. 

The parametrization with the local direction angles might help, but it is not very necessary and we don't have the manpower for this moment.

Hence, I will close this now.
