### ISSUE TITLE
Optimize creating cells from simulated hits (was ACTS-471)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#57]
[GitLab issue: #473](https://gitlab.cern.ch/acts/acts-core/issues/473)

Original author Julia Hrdinka @ jhrdinka

The slowest part of the digitization & clustering is currently the creation of the cells from simulated hits, which is currently done in 3D by intersection (<https://gitlab.cern.ch/acts/acts-core/blob/master/Core/src/Digitization/PlanarModuleStepper.cpp#L27>). For planar modules it is sufficient to do that step in 2D and take the incident angle into account. Therefore creating the steps can be optimized, which should speed up the digitization.

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-03-28 11:55:17](https://gitlab.cern.ch/acts/acts-core/issues/473#note_2486470)

 @ jhrdinka can you evaluate whether this can be closed?

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2019-04-17 10:44:20](https://gitlab.cern.ch/acts/acts-core/issues/473#note_2532800)

 The issue still exists, but again, I would like to move the geometric digitisation part to `acts-fatras`

**Comment by asalzburger** [comment]
Closing this one, let's revisit when digitisation is moved (as discussed).
