### ISSUE TITLE
Bug: CKF efficiency drops at phi=+/-pi/2 for Generic detector

### ISSUE THREAD

**Issue by XiaocongAi** [acts-project/acts#571]
It's noticed that the CKF efficiency drops at phi=+/-pi/2 for the Generic Detector as below:
![image](https://user-images.githubusercontent.com/30073719/98217206-77a0cd00-1f4a-11eb-8d18-ac5d48032902.png)
However, this phenomenon is not obvious for the OpenData Detector as below:
![image](https://user-images.githubusercontent.com/30073719/98229965-e0904100-1f5a-11eb-9ac9-3d18d91870e3.png)

For the Generic Detector, the number of measurements on the track has a drop at phi=+/-pi/2 as below:
![image](https://user-images.githubusercontent.com/30073719/98231234-6f518d80-1f5c-11eb-9188-638a38d59349.png)

While for the OpenData Detector, this is not observed:
![image](https://user-images.githubusercontent.com/30073719/98231315-8f814c80-1f5c-11eb-8695-536ce456767a.png)

@asalzburger , any idea of the possible reason for this, i.e. propagation starting from the truth seed with phi=+/-pi/2 is not able to find the truth hits for the Generic Detector?

**Comment by asalzburger** [comment]
Hi, this could be a problematic binning - i.e. we do not fill the surfaces correctly into the bins and hence they never appear in the CKF search?

**Comment by XiaocongAi** [comment]
@asalzburger Do you mean that the navigator is not aware of those surfaces?

**Comment by XiaocongAi** [comment]
With the recent test using 100 ttbar events (mu = 200) with the GenericDetector, const B field and using smeared starting parmeters, the efficiency drop at phi=+/-pi/2 is not obvious any more as below:
![image](https://user-images.githubusercontent.com/30073719/128028262-16dfa704-7b78-4c77-b920-f78ad515d107.png)

NB: The efficiency fluctuation in the above plot is probably related with the cut of number of measurements when defining the efficiency, i.e. in some phi region with overlapped modules, the efficiency is likely to be higher.

But as  the mentioned issue is not observed any more, so I will close it for now.
