### ISSUE TITLE
Fatal Error in local-to-global transformations

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#579]
Sometimes when running the `Acts::Propagator`, there are cases where the `CovarianceEngine` throws a fatal error when trying to perform a global to local transformation [here](https://github.com/acts-project/acts/blob/c95a6b10a79036615c5df5838091c3b8e5d6c224/Core/src/Propagator/detail/CovarianceEngine.cpp#L184). This fatal error throws an exception and then immediately stops the code from continuing to process, rather than just returning an error message and continuing. I think it would be an improvement if instead an error message was thrown that could be caught at the user level of the API, e.g. as in 

```
auto result = propagator.propagate(arguments);

/// If there was this global-to-local transformation problem, then result.ok() == false
if(!result.ok())
   /// The user can then do whatever they want to here
   std::cout << "there was a global to local transformation problem" << result.error() << std::endl; 
```

This way the error does not crash the code and the user can handle it however they want (e.g. by skipping that particular propagation).

**Comment by osbornjd** [comment]
Updating this issue with the slides that I showed in today's developer meeting. The issue is that (if I understood correctly) in the path limit aborter logic the aborter can be triggered without flagging that the target surface is not set. Thus, the aborter is triggered, signaling that the target surface has been reached, but (in some cases) the target surface has not actually been reached and thus the global to local transformation cannot be performed on the surface.

Here are the slides that I showed which describe this bug and show the verbose output:

[propagationBug.pdf](https://github.com/acts-project/acts/files/5554790/propagationBug.pdf)

**Comment by osbornjd** [comment]
@asalzburger do you have an estimate of when you might be able to looking at this? Just curious as we'd like to update our Acts version, but only after this is in.

**Comment by asalzburger** [comment]
I will put it on my list for Thursday, so I hope we can check/update this by the end of the week.

**Comment by osbornjd** [comment]
@asalzburger is there any update on the timescale for this?

**Comment by osbornjd** [comment]
@asalzburger any update on this?

**Comment by HadrienG2** [comment]
As further motivation for fixing this, I discovered in the process of implementing #482 that we do also get those sort of issues in the AtlasStepper unit tests already...

However, I'm surprised that @osbornjd observes an exception here, because ACTS_FATAL does not throw exceptions (yet). Which is precisely why the issue in the AtlasStepper unit test was not seen before.

**Comment by osbornjd** [comment]
The exception is caught on the sPHENIX end, which means that somehow the ACTS_FATAL is throwing/doing something that the sPHENIX code doesn't like and interprets as an exception being thrown. If the ACTS_FATAL only returns an error that can be caught, then it would be very puzzling why an exception is caught since our code just looks like this:

```
auto result = propagateTrackState(trackParams, sl);
if(result.ok()) {	  
    auto trackStateParams = std::move(**result);
    /// Do some other stuff
}
else {
 continue;
}
```

where the result that is obtained from `propagateTrackState` is just the result returned from the Acts propagator, i.e.:

```
auto result = propagator.propagate(params, sl.referenceSurface(), options);
if(result.ok())
  return std::move((*result).endParameters);
else
  return result.error();
```

**Comment by HadrienG2** [comment]
I just went through the entire Logger implementation as part of implementing #687, so I'm quite sure that ACTS_FATAL is not special in any way, at least if you use the default Acts logger as opposed to plugging into an sPHENIX-specific logging mechanism. Therefore, I suspect something else must be happening here.

If you have a build with debug symbols handy, running it through GDB with `catch throw` enabled should help you get a stack trace at the point where the exception is thrown, which will help us understand better what's going on here.

**Comment by asalzburger** [comment]
There still must be some underlying problem in the local to global transformation, right?

**Comment by osbornjd** [comment]
Just to confirm, I have checked that somehow there is an error caught within Acts, i.e. the propagator call:
```
auto result = propagator.propagate(params, sl.referenceSurface(), options);
```
is never returned. So somehow this FATAL log is printed but doesn't do anything (since the log itself isn't special), but it is symptomatic of some crash that occurs further down the line after the FATAL log is printed.

**Comment by osbornjd** [comment]
I traced through the Acts code to understand what is going on. We are using version 1.1 as we've been waiting for this bug to be fixed before updating, but it may have already been fixed in a previous unrelated PR (or this bug was never marked as possibly fixed).

In v1.1, the propagator can seg fault [here](https://github.com/acts-project/acts/blob/f6ebeb9a28297ba8c54fd08b700057dd4ff2a311/Core/src/Propagator/detail/CovarianceEngine.cpp#L173). If the global to local transformation returns something that is inconsistent with the surface tolerance, all that occurs in the FATAL log is given and then the result value is attempted to be accessed. If the transformation was inconsistent with the surface, the value is still attempted to be accessed, and thus there is a segmentation fault.

In the most recent v6.0, the transformation is delegated to this function [here](https://github.com/acts-project/acts/blob/12f1247583b684e48f9011773a38d891196d1847/Core/src/Propagator/detail/CovarianceEngine.cpp#L192), where the result is accessed. In this function where the result is accessed, the possibility of an exception is properly handled [here](https://github.com/acts-project/acts/blob/3af34d99de9fa7278e113caf7f9caf735157bdaa/Core/src/EventData/TransformationFreeToBound.cpp#L29), such that the result of the transformation is not accessed if the transformation returned an error.

If the result returns an error, this means that the `bp[eBoundLoc0]` and `bp[eBoundLoc1]` are left as 0 as they are initialized. Are these values then sent back to the result returned to the user? In other words, is there a possibility that there is no way to catch this error other than checking if the return local position values are [0,0]?

**Comment by paulgessinger** [comment]
Hm, the `lpResult.value()` just aborts in the error case, so the `operator[]` access should never happen I believe.

I honestly think the error should be handled further up the call chain, and these functions should return a result as well.

**Comment by osbornjd** [comment]
You're right that the operator `[eBoundLoc0/1]` access should never happen, which means I think they just remain as instantiated as 0. That means the only "flag" for an error in the current version is the FATAL log, which is not easy to detect as you mention.

**Comment by paulgessinger** [comment]
Ok. I think this function should in turn use `Result` to let the error bubble up if it encounters one.

**Comment by paulgessinger** [comment]
@osbornjd is it sufficient if the error propagation is fixed on master, or do you need this backported to a specific version?

**Comment by osbornjd** [comment]
@paulgessinger master is fine. We are running on v1.1 so we are quite old at this point and probably need to update anyway.

In principle, I could fix up our v1.1 with something similar to your PR to master, but it seems like a recipe for possible issues down the road if we are using a "in house edited" version of Acts rather than a version that is released by the development team.

**Comment by paulgessinger** [comment]
Sounds good.

**Comment by osbornjd** [comment]
BTW, if you are curious to debug the actual problem, I don't think I'm doing anything fancy. All I do is take a set of track parameters and run the propagator to an arbitrary cylindrical surface that I create. In other words, it is just :

```

  return std::visit([params, targetSurf, this]
		    (auto && inputField) -> BoundTrackParamPtrResult {
      using InputMagneticField = 
	typename std::decay_t<decltype(inputField)>::element_type;
      using MagneticField      = Acts::SharedBField<InputMagneticField>;
      using Stepper            = Acts::EigenStepper<MagneticField>;
      using Propagator         = Acts::Propagator<Stepper>;

      MagneticField field(inputField);
      Stepper stepper(field);
      Propagator propagator(stepper);

      Acts::Logging::Level logLevel = Acts::Logging::FATAL;

      auto logger = Acts::getDefaultLogger("PHActsTrackProjection", logLevel);
      
      Acts::PropagatorOptions<> options(m_tGeometry->geoContext,
					m_tGeometry->magFieldContext,
					Acts::LoggerWrapper{*logger});
     
     /// Here params is a set of Acts::SingleBoundTrackParameters and 
    /// targetSurf is a std::shared_ptr<const Acts::Surface> that is a cylindrical surface constructed at an arbitrary radius centered at (0,0,0)
      auto result = propagator.propagate(params, *targetSurf, 
					 options);
   
      if(result.ok())
	return std::move((*result).endParameters);
     
      return result.error();
   },
     std::move(m_tGeometry->magField));

```

**Comment by paulgessinger** [comment]
@FabianKlimpel mentions the same or a similar error can show up in one of the integration tests if the parameters are chosen (in)correctly. Can you help reproduce this decoupled from @osbornjd's setup?

**Comment by paulgessinger** [comment]
@asalzburger said that he could imagine it's because of inconsistent tolerances between to-surface-propagation and free-to-bound conversion. I faintly remember we had ruled this out as the culprit, however. Does anyone

**Comment by paulgessinger** [comment]
I will also look into the `AtlasStepper` test to see if it reproduces.

**Comment by osbornjd** [comment]
> @asalzburger said that he could imagine it's because of inconsistent tolerances between to-surface-propagation and free-to-bound conversion. I faintly remember we had ruled this out as the culprit, however. Does anyone

I think we had discussed this in one of the developer meetings when I first brought this bug up. I think Andi had suggested that the tolerance for the conversion be a settable parameter/argument, such that one could "dictate" what is acceptable and what is not.

**Comment by robertlangenberg** [comment]
Exception is now thrown, underlying floating point issue to be analyzed
