### ISSUE TITLE
Refine `debugLog` throughout acts-core (was ACTS-457)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#59]
[GitLab issue: #458](https://gitlab.cern.ch/acts/acts-core/issues/458)

Original author Andreas Salzburger @ asalzbur

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:52:35](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2483892)

 Original author ATS Jenkins @ atsjenkins

[Andreas Salzburger](https://gitlab.cern.ch/asalzbur) mentioned this issue in [a merge request of acts/acts-core](https://gitlab.cern.ch/acts/acts-core/merge_requests/408):
'Extrapolator prototype'

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:52:36](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2483898)

 Original author Hadrien Benjamin Grasland @ hgraslan

Here is a summary of the suggestions that I made on MR 408:
 * We may want to centralize the many debugLog methods in a single place
 * Whether we do this or not, we may want them to converge towards a single interface style.
 * Given that debugLog internally uses an std::stringstream, passing an std::stringstream& to the logging lambda may be both more efficient and cleaner than requiring the lambda to return an std::string.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:52:36](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2483907)

 Original author Hadrien Benjamin Grasland @ hgraslan

Another suggestion made at the time: we currently have several instances of this set of struct members:
```cpp
    bool        debug         = false;
    std::string debugString   = "";
    size_t      debugPfxWidth = 30;
    size_t      debugMsgWidth = 50;
```
It would probably be better to turn this into a nullable unique_ptr to a debug settings struct, as it will take up less room in memory in release mode and allow less repetition in struct members.

If we like, we'll also be able to factor out common debugLog-like functionality as a member of such a struct.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:52:37](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2483914)

 Original author Andreas Salzburger @ asalzbur

I agree, I will make such a struct and integrate it first in the Propagator schema.

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-03-28 11:58:50](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2486484)

 I was thinking about this mechanism, also for the FSM navigator (#573). I like the concept that you can decide at the end of the propagation or navigation that verbose logging is of interest for this particle, and **only then** dump it to the screen. I do think, however, that we should try to make this work with the `ACTS_*` logging macros. 

What we could do is this: have a logger that gets *initialized*, and then collects verbose output if its configured to record the corresponding level, and also set a *threshold* level, which triggers a dump of all accumulated messages of lower severity, and then all remaining messages until it's *reinitialized*. This could then be a generic thing.

What do you think? @ msmk @ hgraslan @ asalzbur

**Comment by paulgessinger** [comment]
[Original comment by: hgraslan at 2019-03-28 13:54:02](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2486933)

 I would be in favor of having some way to make logging immediate. The current deferred logic is extremely hostile to debugging:

- Printing all propagator logs at the end makes it hard to figure out the actual message history when other log sources like `std::cerr` come into play.
- If propagation freezes or crashes, no logs get printed, so manual duplication of the logging logic (either with a debugger or std::cerr) is needed to figure out what's going on.

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-03-28 15:01:13](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2487158)

 Hm but it does make sense I think. For instance, I think it's extremely useful to restrict output to only certain types of propagations, for instance those who suffer navigation failures. That doesn't really work if we don't have a mechanism for it, and grepping the output to figure out things like this is pretty hard.

**Comment by paulgessinger** [comment]
[Original comment by: hgraslan at 2019-03-28 15:14:22](https://gitlab.cern.ch/acts/acts-core/issues/458#note_2487207)

 Maybe we could have a toggle between immediate and deferred mode? This way, we could get either behavior depending on which is most appropriate for the debugging task at hand?

As far as I can see, this would all be confined into the debugLog implementation, so it wouldn't have a dramatic impact across the codebase.

**Comment by paulgessinger** [comment]
[Original comment by: asalzbur at 2020-02-04 09:44:47](https://gitlab.cern.ch/acts/acts-core/issues/458#note_3162227)

 I think this should be revisited.

**Comment by asalzburger** [comment]
Closing this one.
