### ISSUE TITLE
Bug (Major): Problem with CKF, drop in efficiency, high values of chi2

### ISSUE THREAD

**Issue by jadz1** [acts-project/acts#596]
Hello, 
After I generate a sample (ttbar or ParticleGun), and do the simulation step with a Generic detector (TrackML-like), I do the reconstruction using CKF, and I get an efficiency versus eta that has two very deep drops in it (around |η|~2.5). This issue appears when using ParticleGun or Pythia8. You can see an example in this plot here in the case of a muon PG with 1000 events. 

￼
![Pasted Graphic](https://user-images.githubusercontent.com/74740928/99778651-3eed2000-2b14-11eb-829a-f4cf3b84bea3.png)

Since it’s a TEfficiency plot, I am able to “decompose” the plot into the passed (numerator) and total (denominator) histograms. You can see that the bug is actually coming from the passed histogram. 
￼
<img width="940" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/74740928/99778690-4ca2a580-2b14-11eb-991d-1f23241abdb0.png">

I tried to look if in this region it is less probable to have hits, maybe the detector layout is the problem, so I ran the ActsExampleTruthTracksGeneric after adding a variable to get the number of hits in Examples/Io/Root/src/RootTrajectoryParametersWriter.cpp  and I got the following plot, 
￼
<img width="761" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/74740928/99778707-54fae080-2b14-11eb-954d-7f1f48d3efc7.png">

So it is clearly not a problem in the simulation but in the CKF. We have enough hits, hence enough number of measurements that the CKF should run correctly.

One important cut in the CKF is the chi2 value, in the ACTS, the example sets it at 15, however, when plotting the chi2 versus eta, we could see a problem here, where in the region where we have this drop of efficiency, we can get chi2 values up to a couple thousands.. 
￼
![Pasted Graphic 3](https://user-images.githubusercontent.com/74740928/99778737-5d531b80-2b14-11eb-9b2f-49edd0cfe299.png)

The efficiency does get better when we increase the chi2.. but of course, the fake rate would also increase 
Do we have any idea why chi2 is bad in these regions? It should certainly originate from the propagation of the errors in these regions, shouldn’t it? 
I looked also at the same plot for the different sub detectors 
￼
<img width="1004" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/74740928/99778746-62b06600-2b14-11eb-9bde-7ef9a3870d23.png">

and the problem is propagating in the all the volumes 
In order to fix this, maybe one should look at the hit resolution and the error propagation? The hit is more "elliptical" than "spherical" for this eta range, so it might be affecting the reconstruction? 

Any idea on how to fix this issue please? 

Thank you, 
Tagging @XiaocongAi with whom I discussed..

**Comment by XiaocongAi** [comment]
Hi @jadz1 , thank your for those checks. As we discussed privately, we can probably play with the measurement resolution, the seed resolution and the detector a bit. We are currently changing the inputs of CKF to use more dedicated truth smearing to mimic the measurements. With that change and the Open Data Detector,  we might have a better understanding of the reason for this issue.

**Comment by robertlangenberg** [comment]
@XiaocongAi, you mentioned this has probably already been resolved some weeks ago?
