### ISSUE TITLE
Remove `clone()` infrastructure from Geometry

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#6]
[GitLab issue: #725](https://gitlab.cern.ch/acts/acts-core/issues/725)
Referenced by the following MRs on GitLab: [!805](https://gitlab.cern.ch/acts/acts-core/-/merge_requests/805)

The clone() infrastructure for geometry is unused, should be removed.

**Comment by asalzburger** [comment]
This has been merged and is done.
