### ISSUE TITLE
Track Quality / Chi-Square calculation (was ACTS-299)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#60]
[GitLab issue: #300](https://gitlab.cern.ch/acts/acts-core/issues/300)

Original author Valentin Volkl @ vavolkl

Given a set of measurements and a fitted track, it would be useful to have a routine that calculates the weighted distance of the track from the measurements.

**Comment by asalzburger** [comment]
Closing this one, superseded by @XiaocongAi 's development on the KalmanFilter.

**Comment by paulgessinger** [comment]
@asalzburger is it? I think this refers to a global track chi2 calculation, which I think we don't have at the moment.

**Comment by asalzburger** [comment]
Oh, I thought this was done - I will check with @XiaocongAi.

**Comment by paulgessinger** [comment]
I'll reopen until clarified.
