### ISSUE TITLE
DiscSurface.globalToLocal not working as advertised (was ACTS-280)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#61]
[GitLab issue: #282](https://gitlab.cern.ch/acts/acts-core/issues/282)

Original author Shaun Roe @ sroe

Tests show that DiscSurface.globalToLocal is not working as documented; either the functionality or documentation is wrong. The documentation says of the bool return type :
_boolean indication if operation was successful (fail means global position was not on surface)_
however the following tests do not support this and are mutually inconsistent:
```cpp
double rMin(1.0), rMax(5.0), halfPhiSector(M_PI/8.);
DiscSurface discSurfaceObject(pTransform, rMin, rMax, halfPhiSector);
Vector3D point3DNotInSector{0.0,1.2,0};
// test shows point is not on surface
BOOST_TEST(discSurfaceObject.isOnSurface(point3DNotInSector, true) == false); //passes
//... so the following should be false:
BOOST_TEST(discSurfaceObject.globalToLocal(point3DNotInSector, ignoredMomentum, returnedLocalPosition) == false);// test fails
```

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:50:54](https://gitlab.cern.ch/acts/acts-core/issues/282#note_2481876)

 Original author Andreas Salzburger @ asalzbur

Hi @ Shaun, I will investigate.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:50:54](https://gitlab.cern.ch/acts/acts-core/issues/282#note_2481882)

 Original author Andreas Salzburger @ asalzbur

Ok, I see, actually this is a documentation issue, the globalToLocal and LocalToGlobal are only frame transformations,
the boundcheck needs to be done separately.

**Comment by paulgessinger** [comment]
[Original comment by: pagessin at 2019-03-28 12:22:42](https://gitlab.cern.ch/acts/acts-core/issues/282#note_2486624)

 Did anything come out of this? @ asalzbur @ sroe. Can we close this?

**Comment by asalzburger** [comment]
I will follow this up.

**Comment by asalzburger** [comment]
I just checked, this is fixed. 

The corresponding `UnitTests` now behaves correctly:
```
  BOOST_CHECK(!discSurfaceObject->isOnSurface(
      tgContext, point3DNotInSector, ignoredMomentum, true));  // passes
```

The point is not on surface, so the return type is false, the negation is true, so the check passes.
