### ISSUE TITLE
TriangleBounds.boundingBox()  is not centred on the triangle (was ACTS-279)

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#62]
[GitLab issue: #280](https://gitlab.cern.ch/acts/acts-core/issues/280)

Original author Shaun Roe @ sroe

The boundingBox is symmetric and always centred on (0,0) and is simply made large enough to encompass all the triangle vertices.

An example: if a triangle is constructed with vertices (1,1), (4,1), (4,5), the RectangleBounds bounding box vertices will be (-4,5), (4,5), (4,-5), (-4,-5), as returned by the boundingBox() method.

**Comment by paulgessinger** [comment]
[Original comment by: msmk at 2019-03-27 16:50:53](https://gitlab.cern.ch/acts/acts-core/issues/280#note_2481861)

 Original author Moritz Kiehn @ msmk

This uses `RectangleBounds` which are always centered around zero. From reading the code I have the feeling that this is a deliberate decision, but I'm not sure. Otherwise, this can be solved by extending the `RectangleBounds`.

**Comment by asalzburger** [comment]
As part of the visualisation update (and the according documentation), I will have a look if this is the case.

**Comment by asalzburger** [comment]
`TriangleBounds` have been deleted as they are just `PolyConvexBounds<3>`, closing this issue.
