### ISSUE TITLE
Build instructions and the minimal required versions for the dependencies

### ISSUE THREAD

**Issue by andriish** [acts-project/acts#635]
Hi all, 

there are two minor issues related to the documentation.

- Would you consider putting in the `README.md`  the build instructions for the LCG releases?

 - Also, in addition to the C++ standard support requirement, it could make sense to specify the minimal required versions for cmake, eigen and boost.

Best regards,
Andrii

**Comment by msmk0** [comment]
Hi @andriish,

thanks for bringing this up. The `README.md` is intentionally kept as short as it is. The full documentation is available at https://acts.readthedocs.io, which should be linked both in the `README.md` and on the Github page. Please let me know if that is not the case or if it is not clear where to look.

The full documentation contains both the specific versions required as well as build instructions for the LCG releases. I saw that it still mentions older LCG releases. This will be fixed.

I hope that clears your issues?

**Comment by msmk0** [comment]
P.S. I would prefer not to additional information and the version requirements to the `README.md`. Since then, there are two different places which **will** lead to inconsistencies over time.

**Comment by andriish** [comment]
Hi @msmk0 ,

ok, I see. Thanks for pointing to the docs. That solves the issue.
A very minor thing then is that  LCG95 has cmake 3.11 which doesn't support -B -S  options mentioned in the docs.

Best regards,
Andrii

**Comment by msmk0** [comment]
I am aware. We have recently moved to LCG97/98 and deprecated support for LCG95/96. The documentation needs to be updated.
