### ISSUE TITLE
Install custom CMake find modules

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#646]
Some of the optional dependencies do not provide CMake config files and are instead found using custom CMake find modules. When installing Acts these custom CMake find modules must be installed as well. Otherwise, using some plugins from an Acts installation (e.g. Onnx or Sycl) will break due to missing dependencies.

_Originally posted by @msmk0 in https://github.com/acts-project/acts/issues/637#issuecomment-748293886_

**Comment by benjaminhuth** [comment]
I have quickly tested some things and found a relatively easy way to do this (though I'm not sure if this is "idiomatic cmake")

In `cmake/ActsCreatePackageConfig.cmake` I added

```cmake
install(
    FILES ${CMAKE_CURRENT_LIST_DIR}/FindOnnxRuntime.cmake
    DESTINATION ${install_package_config_dir}/thirdparty
)   
```

and in `cmake/ActsConfig.cmake.in` I added

```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/thirdparty)
```

This installs e.g. the `FindOnnxRuntime.cmake` to `CMAKE_INSTALL_PREFIX/lib64/cmake/thirdparty`, and adds this to `CMAKE_MODULE_PATH` when using `find_package(Acts...)`. I thought it could be good to use a subfolder here to avoid that these files conflict with other projects, but not sure if this is necessary...

At least in my current project this works fine.

For the changes see also here: https://github.com/benjaminhuth/acts/tree/feature/install_find_files/cmake

**Comment by msmk0** [comment]
@benjaminhuth That looks like the right way to do it. I have seen this solution before in other packages.

To avoid clashes with other packages, the module should be installed to `${install_package_config_dir}/Modules` which would translate to `.../lib64/cmake/Acts/Modules`.

Please go ahead and open a PR for this.
