### ISSUE TITLE
ERROR TGeoTrd2 -> PlaneSurface: only works with (x/X)(z/Z) and (y/Y)(z/Z).

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#659]
Hi,
Got the error:
```
ERROR TGeoTrd2 -> PlaneSurface: only works with (x/X)(z/Z) and (y/Y)(z/Z).
```
What does this mean and how is it supposed to be fixed? Sorry I am a bit confused as to the notation and cannot seem to find anything in the documentation. 

Thanks

**Comment by whit2333** [comment]
@asalzburger I have tried adding `layerExtension->addType("axes", "definitions", "YZX");` in the dd4hep detector construction but it doesn't seem to register.

**Comment by asalzburger** [comment]
Is that a layer or a sensitive volume? It has to be at the right level attached. 

What this steers is the translation between conventions from TGeo and Acts::TrapezoidBounds with respecting the righthanded frame definition.

**Comment by asalzburger** [comment]
The notion is: XZ - X axis stays X axis, Z axis becomes new Y axis (resulting new Z axis is a cross product). If the axis is not capitalized it means that it is taken pointing the opposite direction.

xZ would then translate into negative X becomes new X, Z becomes new Y, new Z is again done by cross product.

**Comment by whit2333** [comment]
Does it need to be associated with sensitive volume?

**Comment by asalzburger** [comment]
Indeed, if the trd is the sensitive volume then yes.

**Comment by whit2333** [comment]
Thanks! Also worth pointing out for others that the construction can be done like this: `Acts::ActsExtension("XZY")` which is nice.

**Comment by whit2333** [comment]
Hi @asalzburger,

I have another question for you. I hope you don't mind.

```
                  WARNING D2A_CVH       Provided layers are not contained by volume ! Bailing out.
                  WARNING D2A_CVH       - zFromTransform: -370.5
                  WARNING D2A_CVH       - volumeZmin:-696, layerZmin: -695
                  WARNING D2A_CVH       - volumeZmax: -45, layerZmax: 695
                  WARNING D2A_CVH       - volumeRmin: 29, layerRmin: 539.885
                  WARNING D2A_CVH       - volumeRmax: 797.76, layerRmax: 796.76
                  WARNING D2A_CVH       [!] Problem with given dimensions - return nullptr and delete provided objects
                  WARNING D2A_CVH       Inconsistent dimensions given : zMin > zMax (-45 > -694 ) - return 0
```
I have no idea how to fix this. It is in a barrel detector, there are no overlaps the sensitive elements of each layer are contained within the cylinder layer  volume. I am confused by the error message because it it is not clear there is a problem with the layer/module geometry.

Do all the layers need to be in a larger cylinder volume?

Thanks again for your help!
