### ISSUE TITLE
Failing documentation build

### ISSUE THREAD

**Issue by msmk0** [acts-project/acts#661]
Some recent changes have broken the documentation build as can be seen e.g. in the [current master branch](https://github.com/acts-project/acts/runs/1740565809) or in this [pull request](https://github.com/acts-project/acts/pull/651/checks?check_run_id=1741520178).

This seems to appear for the first with the recent changes to [`BinningData`](https://github.com/acts-project/acts/pull/657) so @asalzburger should have a look what could have been the offending change there.

**Comment by paulgessinger** [comment]
Did you see my comment on mattermost?

**Comment by msmk0** [comment]
No, I did not.

**Comment by paulgessinger** [comment]
It worked in @asalzburger's PR before merging. So it can't really be related to the changes. I diffed the python dependencies we install for the doc build, and between the successful run on the PR and the failing run on master, breathe bumped from `4.26.0` to `4.26.1`. I would think that's the culprit.

**Comment by msmk0** [comment]
Thanks for looking into this into more detail. Lets fix the versions in the `docs/requirements.txt` file as an intermediate step then.

**Comment by paulgessinger** [comment]
I reported this at https://github.com/michaeljones/breathe/issues/624, see https://github.com/pybind/pybind11/pull/2828 for a possible workaround.

**Comment by paulgessinger** [comment]
This might be fixed by https://github.com/doxygen/doxygen/pull/8466, which is merged but waiting to be included in a release.
