### ISSUE TITLE
Geometry Surface Bug

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#668]
Hello @asalzburger ,

I am getting the following warning using the DD4hep geometry plugin.

```
                  WARNING D2A_CVH       Provided layers are not contained by volume ! Bailing out.
                  WARNING D2A_CVH       - zFromTransform: -370.5
                  WARNING D2A_CVH       - volumeZmin:-696, layerZmin: -695
                  WARNING D2A_CVH       - volumeZmax: -45, layerZmax: 695
                  WARNING D2A_CVH       - volumeRmin: 29, layerRmin: 539.885
                  WARNING D2A_CVH       - volumeRmax: 797.76, layerRmax: 796.76
                  WARNING D2A_CVH       [!] Problem with given dimensions - return nullptr and delete provided objects
                  WARNING D2A_CVH       Inconsistent dimensions given : zMin > zMax (-45 > -694 ) - return 0
```
The thing that sticks out to me is that last line. It is not clear to me what the volume/layer problem is other than the "-45" which I do not know the origins of. If I understand this   

Here is the Acts surfaces exported as .obj for just the barrel (which doesn't have the problem above).
![Screenshot_2021-01-22_13-07-23](https://user-images.githubusercontent.com/2065918/105534245-d147a680-5cb2-11eb-8ff9-b9d28bed2ced.png)

The problem above appears when I add only the outermost endcap layer. See here for the reference design:
![Screenshot_2021-01-22_13-12-27](https://user-images.githubusercontent.com/2065918/105535019-f12b9a00-5cb3-11eb-8c4d-2897a4baa86a.png)

If I remove the outermost barrel layer and include the outer most endcap layer, the surface error goes away. Here is the surface geometry:
![Screenshot_2021-01-22_13-15-33](https://user-images.githubusercontent.com/2065918/105535215-36e86280-5cb4-11eb-959d-baf779b7513b.png)

Does the endcap/barrel paradigm assume that a "bounding cylinder" of the endcap does not overlap with the bounding cylinder of the barrel?

Thanks
Whit

**Comment by asalzburger** [comment]
That should work though, any chance I can get the root file & setup to try it out? I do not understand the estimated z boundary - that does not make sense.

**Comment by asalzburger** [comment]
To answer the question: there can not be overlaps in the cylinders at all. However, when I look at this, one should be able to create a setup that works.

**Comment by asalzburger** [comment]
The Acts:TrackingGeometry relies on the fact that the volumes completely attach, because the boundary surfaces of the volumes act as portals into the next (that's how we avoid navigation searches). In this case you could try to shrink the envelope of the outer discs a bit.

**Comment by whit2333** [comment]
@asalzburger, I am confused by your statement. The layer geometries should or shouldn't touch?

**Comment by whit2333** [comment]
@asalzburger ,

If I remove a barrel layer and turn on the corresponding endcap layer (and nudge back 1cm so there is no overlap in the z direction), then I can make these:

Note that there are 5 layers of barrel/endcap.

2 layers endcap, 4 barrel:
![image](https://user-images.githubusercontent.com/2065918/105751358-85436e80-5f0b-11eb-8cd7-77a51d6d7ab3.png)

3 layers endcap, 3 barrel:
![image](https://user-images.githubusercontent.com/2065918/105751306-70ff7180-5f0b-11eb-9c0d-d64dac912917.png)

4 layers endcap, 2 barrel:
![image](https://user-images.githubusercontent.com/2065918/105751909-4235cb00-5f0c-11eb-81d9-834e7c1034c0.png)

5 layers endcap, 1 barrel:
![image](https://user-images.githubusercontent.com/2065918/105751833-27fbed00-5f0c-11eb-8014-ffbb9643a888.png)

**Comment by whit2333** [comment]
Here is where these warnings are printed:
https://github.com/acts-project/acts/blob/master/Core/src/Geometry/CylinderVolumeHelper.cpp#L550

**Comment by whit2333** [comment]
> That should work though, any chance I can get the root file & setup to try it out?

If you want to try something out, we have a pretty robust CI setup: https://eicweb.phy.anl.gov/EIC/detectors/topside
the detector constructors are in src:
- https://eicweb.phy.anl.gov/EIC/detectors/topside/-/blob/acts_v4/src/SiTrackerEndcap_geo.cpp
- https://eicweb.phy.anl.gov/EIC/detectors/topside/-/blob/acts_v4/src/SiTrackerBarrel_geo.cpp
- https://eicweb.phy.anl.gov/EIC/detectors/topside/-/blob/acts_v4/topside/silicon_tracker.xml
-

**Comment by whit2333** [comment]
@asalzburger Have you seen anything in the code that is causing problems?

**Comment by asalzburger** [comment]
Did not get around yet to this, as I am finishing the segmentation PR - will go through tomorrow though.

**Comment by whit2333** [comment]
I am still confused about the requirements for the tracking geometry caused by (I think) the combination of navigation requirements and current plugin implementation limitations.

Should a `CutoutCylinderVolumeBounds` be used instead of `CylinderVolumeBounds`?
What is the general strategy between the Cylinder-`VolumeBounds`, `VolumeBuilder`, `VolumeHelper`, and `Layer` classes?

Also, do you have any links to presentation materials discussing the acts geometry construction details?

**Comment by asalzburger** [comment]
@whit2333 - shall we schedule a call for the coming days? I think we should go through the requirement. I can find an evening spot as well.

**Comment by whit2333** [comment]
@asalzburger Sure. I sent you an email.
