### ISSUE TITLE
[Feature] - BinAdjustment.hpp not yet implemented for rectangular planar surfaces

### ISSUE THREAD

**Issue by SpencJ95** [acts-project/acts#677]
Label    - Feature

BinAdjustment.hpp is implemented only for cylindrical surfaces with cylinder and radial bounds. For material mapping with the FASER detector in calypso we also need to support rectangular bounds for planar surfaces. I am requesting that the code be modified to accomplish this.

**Comment by Corentin-Allaire** [comment]
Fixed in #705
