### ISSUE TITLE
Visualizing Layer Bounds?

### ISSUE THREAD

**Issue by whit2333** [acts-project/acts#683]
Hello,

Is there a way to visualize the layer bounds or volumes? I can visualize the surfaces following the examples (via .obj -> freecad) but I think I have a layer geometry issue that would be easier to understand if I could see the layer bounds.

**Comment by asalzburger** [comment]
Indeed, there are several possibilities.

What version are you running? 
I am not sure they are added to the obj viewer per default, but it's a three line change I can do quickly.

The other option is to run the propagation example and log every surface to be written out, then the root output has them via the approach flag.

A third version (new in v5) is to dump the geometry into a JSON file and look for the approach surface there.

**Comment by whit2333** [comment]
v4.1.0.  I was in the process of upgrading to version 4!! :)
