### ISSUE TITLE
Bad any cast with the ActsExampleGeometryDD4hep

### ISSUE THREAD

**Issue by Corentin-Allaire** [acts-project/acts#697]
Using the `ActsExampleGeometryDD4hep` result in a boost::bad_any_cast. I also tried to test it with `ActsExampleGeometryGeneric` and also encountered a boost::bad_any_cast.

Example command : `./../build/bin/ActsExampleGeometryDD4hep -n1 -j1 --mat-output-file geometry-map  --dd4hep-input ../Examples/Detectors/DD4hepDetector/compact/OpenDataDetector/OpenDataDetector.xml`

**Comment by asalzburger** [comment]
Hi, there was a missing ` | Obj` in the geometryOptions definition, it should be fixed with PR #699.

**Comment by HadrienG2** [comment]
Doesn't seem to be fixed: https://github.com/acts-project/acts/pull/706/checks?check_run_id=1864050040 .

**Comment by HadrienG2** [comment]
The strange thing is, the exact same sequence of commands works just fine on my local machine. So it seems dd4hep version dependent.

**Comment by paulgessinger** [comment]
No the problem is that we're not building DD4hep with `DDDetector`, but we need that.
