### ISSUE TITLE
Geometry examples behave badly when `--events` is not specified

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#707]
Basically, the examples will run for an indefinitely long time, and fill up your storage with billions of copies of the geometry if any kind of file output was enabled.

This is the result of an interaction between two bits of programmer cleverness:

- `Sequencer::Config::events` defaults to `SIZE_MAX` when `--events` is not specified, which is meant to ensure that the number of iterations to only be bounded by the number of events in the input file.
    * ...and if there is no input file, `Sequencer` initialization will bomb.
- But Geometry examples hijack `Sequencer::Config` without actually setting up a `Sequencer`, and therefore the check is never run in those examples.

The cleanest fix for this is probably to remove the magic number and make `Sequencer::Config::events` an `std::optional<size_t>`, with adjusted error checking on the side of both the `Sequencer` and the Geometry examples. Alternatively, Geometry examples could be reworked to actually use the `Sequencer` as intended.

**Comment by msmk0** [comment]
The `SIZE_MAX` bit was me. This is another example of trying to be clever and the cleverness biting you later on. Lesson to myself: do not try to be clever. `std::optional<size_t>` is probably the right way to go.

In my opinion, every example should use the sequencer.

**Comment by HadrienG2** [comment]
This is still around as of master 5038ab6070b8eb89966a80127816bb961c40c8c4 .
