### ISSUE TITLE
ActsExamplePropagationEmpty does not complete with default parameters

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#710]
By default, this example is configured with a maximal step size of 3m and a detector half-length of 10km (!), which means that propagation will abort with an error due to reaching the max step count (1000 steps) before reaching the end of the detector.

Which parameter would you prefer me to tune to fix that? Detector half-length or maximal step size?

**Comment by paulgessinger** [comment]
@asalzburger do you have thoughts on this?

**Comment by HadrienG2** [comment]
I confirm that this is still present as of master 5038ab6070b8eb89966a80127816bb961c40c8c4 .
