### ISSUE TITLE
Invariant masses in Bethe-Heitler process occasionally too large

### ISSUE THREAD

**Issue by FabianKlimpel** [acts-project/acts#717]
In some cases the momentum vectors of the electron and the photon are off the exact by a small amount. This leads to an increase in the invariant mass. As the invariant mass of the initial state is `m_e`, the difference becomes too large. This affects the corresponding unit test thresholds.
After a first look, the deviation does not occur exclusively for certain particle parameters (phi, theta, p). When printing the four vectors, the difference occurs only in the last digit (`1e-4` / `1e-5`). It could be a consequence of the calculation of the updated direction vector.

**Comment by paulgessinger** [comment]
For some reason I'm unable to assign @benjaminhuth

**Comment by asalzburger** [comment]
Ok, no worries, I assign to myself fo book keeping.

**Comment by robertlangenberg** [comment]
Reduced accuracy not an issue for fastsim
