### ISSUE TITLE
Inconsistent Boundary Surface orientations in Volumes

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#73]
Boundary surface orientation is somewhat arbitrary in the volume bounds.
Ideally this should/could be solved by:

- having predefined xy/yz/zx surfaces and using those
- rotate into position with well defined angles

This will need some changes for the `inside/outside` definition in `BoundarySurfaces` and needs careful adaption of the `BoundarySurfaceFace` enums.

Eventually, this will feed into the new world without layers.

Effectively, this will remove this convention (and comment):

```
/// The orientation of the Surfaces are in a way that the normal vector points
/// to the outside world.
```

as it is anyway meaningless once volumes are glued/attached.

Alternatively, now all boundary surface orientations will be deduced from the xy / yz / zx planes and angles.

This PR is a prerequisite of #14 which already assumes this reordering.

Finally, this will lead to a dropping of `BoundarySurfaceFace`, as glueing/attaching should be done using `polyhedron::extent()`.

**Comment by asalzburger** [comment]
![CuboidVolume00](https://user-images.githubusercontent.com/26623879/81312763-4ae92700-9087-11ea-9bae-799c0294d9eb.png)

[ x ] `CuboidVolumeBounds` done

**Comment by paulgessinger** [comment]
I see so much code needing to be rewritten in the ATLAS geometry building. :/

**Comment by asalzburger** [comment]
> I see so much code needing to be rewritten in the ATLAS geometry building. :/

And I will be the one to do it.

There shouldn't be any assumption on which way the normal vector points in the code, if there is, then that's bad code. Point is : it's consistent for one volume, as soon as you attach them, at least one is inconsistent.

This approach, makes it consistent throughout.

**Comment by asalzburger** [comment]
Besides, this statement

```
/// The orientation of the Surfaces are in a way that the normal vector points
/// to the outside world.
``` 

is already wrong for cylinder volumes, as the inner tube points into the volume.

**Comment by paulgessinger** [comment]
I meant mostly due to dropping the `BoundarySurfaceFace`. For the cylinder? Why? You can have the normals pointing to the center of the overall shape, but still towards the outside of the volume, which is between the inner and the outer cylinder boundary surface. Or am I thinking wrong here?

**Comment by asalzburger** [comment]
Sorry, we don’t need to drop the `BoundarySurfaceFace`, in fact it’s rather unrelated to this at all.

As a first step here, this will include a cleanup of the orientation of the boundary surfaces with respect to the volume. As a consequence, some formerly inwards pointing normal vectors will point outwards, so the glueing will need to be potentially updated.

**Comment by asalzburger** [comment]
![CylinderVolumeBounds00](https://user-images.githubusercontent.com/26623879/81741872-7dd45600-949f-11ea-9afa-892393b48c4e.png)

**Comment by asalzburger** [comment]
All volume bounds are updated, and unit tests are written for the correct inside/outside navigation.

The `GenericCuboidBounds` are currently kept unchanged.
