### ISSUE TITLE
ActsSimGeantinoRecordingDD4hep is too verbose

### ISSUE THREAD

**Issue by HadrienG2** [acts-project/acts#730]
Anyone who has ever run the `ActsSimGeantinoRecordingDD4hep` example with default parameters + OpenDataDetector input can attest that it is a remarkably effective way of losing your terminal history, unless you have set up your terminal for very large / unlimited buffering and made sure it's actually good enough at scrolling into a very long history.

Indeed, that example produces no less than 116746 lines of log during initialization. If you put that into a file, that's >13MB of text.

99.1% of that log (approx. 115.8k lines) comes from a single source, which is DD4hep's `Geant4Converter`. The purpose of this tool should be rather clear from its name: it takes a DD4hep geometry and turns it into a Geant4 one for simulation purposes. However, it would be nice if it were just a little less talkative in the process.

The Geant4Converter log, in turn, contains several different things, including relatively interesting and condensed info about the Geant4 settings used for translated material for example. But this small bit of info is drowned in a sea of almost always irrelevant details about how DD4hep translated every single detector element into its Geant4 equivalent, going down to the memory addresses at which each element of the original geometry and its Geant4 translation lie, and detailing every step from shape (surface/volume) and material translation to the positioning of every element in the final geometry. The latter accounts for the bulk of the log volume, as individual shapes are copied many times across a single geometry.

Now, in my opinion, part of the problem must be resolved on the DD4hep side here, in the sense that we're only configuring the Geant4Converter at `INFO` log level, and even though the semantics of log levels are highly subjective and open to endless debate, I think most people should agree that this level of detail belongs to a higher verbosity level, at least `DEBUG` and probably `VERBOSE` in our classification. Hence I'll open a companion bug report in their repository.

But since DD4hep's build system is what it is, people tend to stick to whatever old version they managed to get to work someday, which means that any fix that I convince upstream of accepting will not help the people who run our examples into a long while. Therefore, I think it might also be a good idea to reduce the log level that we request from DD4hep's Geant4Converter on our side.

What do you think?

**Comment by HadrienG2** [comment]
Upon further investigation, DD4hep handles log levels here quite a bit differently from what I expected and what we do. Basically, they log everything at the same log level (unless specific debug flags are tweaked), and the log level control of `Geant4Converter` only serves to state what debug level all output messages will share.

In that case, I think we will want to either make that `VERBOSE` and make sure that DD4hep honors the log level that's set for Acts by using the Acts logger (not sure if it does or doesn't at this point), and if that fails, just disable this specific DD4hep log entirely unless some debug flag is enabled.

I'll check the "interfacing with the Acts logger" part.

**Comment by HadrienG2** [comment]
So, DD4hep does allow us to plug their logging into our logger, but it may not be cheap. Not sure if that matters for logging though : if code is bound by logging performance, it's likely spamming stdout/stderr way too much for its own good... But here goes.

---

Basically, the interface that DD4hep expects is an extended form of printf's signature:

```cpp
size_t _the_printer_2(void* par, dd4hep::PrintLevel lvl, const char* src, const char* fmt, va_list& args);
```

...where...

- `par` is user-customizable, which allows you to use stateful functors like lambdas or `std::function` with a bit of glue code.
- `lvl` is a logging level
- `src` is the DD4hep source component
- `fmt` and `args` are the usual printf arguments

If the idea of providing a printf-style interface to Acts' logger does not appeal to you, you can also have DD4hep call sprintf for you and forward the resulting string to a lower-level interface:

```cpp
size_t _the_printer_1(void*, dd4hep::PrintLevel lvl, const char* src, const char* text);
```

Notice that this still has an `src` parameter, so you can tell which part of DD4hep the log comes from.

---

Meanwhile on the Acts side, if the component does not already have its own logger (and `DD4hepDetectorConstruction` does not), the expectation is to spawn a copy of the default logger and keep it around with this method:

```cpp
```

**Comment by HadrienG2** [comment]
So, DD4hep does allow us to plug their logging into our logger, but it may not be cheap. Not sure if that matters for logging though : if code is bound by logging performance, it's likely spamming stdout/stderr way too much for its own good... But here goes.

---

Basically, the interface that DD4hep expects is an extended form of printf's signature:

```cpp
size_t _the_printer_2(void* par, dd4hep::PrintLevel lvl, const char* src, const char* fmt, va_list& args);
```

...where...

- `par` is user-customizable, which allows you to use stateful functors like lambdas or `std::function` with a bit of glue code.
- `lvl` is a logging level
- `src` is the DD4hep source component
- `fmt` and `args` are the usual printf arguments

If the idea of providing a printf-style interface to Acts' logger does not appeal to you, you can also have DD4hep call sprintf for you and forward the resulting string to a lower-level interface:

```cpp
size_t _the_printer_1(void*, dd4hep::PrintLevel lvl, const char* src, const char* text);
```

Notice that this still has an `src` parameter, so you can tell which part of DD4hep the log comes from.

---

Meanwhile on the Acts side, if the component does not already have its own logger (and `DD4hepDetectorConstruction` does not), the expectation is to spawn a copy of the default logger and keep it around with this method:

```cpp
std::unique_ptr<const Logger> getDefaultLogger(
    const std::string& name, const Logging::Level& lvl,
    std::ostream* log_stream = &std::cout);
```

And here API impedance mismatch issues appear as we start wondering what should go into the `name` parameter:

- If it's the name of the Acts component (here `DD4hepDetectorConstruction`), then all is well, but we must either swallow DD4hep's `src` metadata or log both the name of the Acts component and that of the DD4hep component. The resulting output will therefore be either incomplete or unduly verbose.
- If it's the name of the DD4hep component, then we must either re-create an Acts-style logger every time DD4hep logs something in order to fill the "name" field right, or keep a global and properly synchronized hashtable keyed by every `src` identifier that ever came from DD4hep and use that as a cache.

In case that's not ugly enough yet, as every time initialization of global variables comes into play, we must also figure when initialization should take place.

- If it's at the time where DD4hep is used, then every Acts source file that calls DD4hep must remember to do it, and inevitably some source files won't remember to do it, resulting in inconsistent DD4hep logging.
- If we want to do it once for every user of DD4hep, then we bring into Acts the joy of global C++ constructors, which have a bad reputation for good reasons (look up "static initialization fiasco"). I'm also unsure how transparently we can do this when DD4hep is treated as a dynamically loaded optional plugin as in Acts.

---

None of this is impossible to work around, of course, but it does raise the question of how much we care about having DD4hep use the Acts logger properly. If we don't care much, it may be more efficient to just configure the DD4hep logger according to what we need to do and otherwise leave it alone.

**Comment by asalzburger** [comment]
Tagging @Corentin-Allaire here and @niermann999 - they might be able to help.

**Comment by Corentin-Allaire** [comment]
I had a look at this and at PR #731 and I think just changing the dd4hep log level is the is the best way to do it. For me, trying to use the Acts logger in DD4Hep is clearly not worth it. On top of that I am pretty sure I only looked at that part of the log once or twice to debug something so it is really not something critical. Maybe in your PR you could add and option in DD4HepDectorOption to change the dd4hep debug level directly ?

**Comment by HadrienG2** [comment]
Thanks for the input @Corentin-Allaire!

In the DD4hep detector options, we actually already have a `dd4hep-loglevel` setting which is meant to set the level of output verbosity on the Acts side. Given the name of this setting, it should probably control the verbosity of DD4hep itself as well.

Since DD4hep's log level is a global variable, I cannot exactly match the Acts semantics there, but probably setting the DD4hep log level at the time whether the Acts `DD4hepGeometryService` is instantiated would be a good enough approximation. I don't think `DD4hep` would tolerate having multiple geometry services in flight anyhow, given how much that library likes singletons...
