### ISSUE TITLE
Bug: some instances of std::optional are dereferenced without checking if they hold a value

### ISSUE THREAD

**Issue by gagnonlg** [acts-project/acts#755]
While investigating what happens with bound parameters when their covariance matrices are std::nullopt, we have found instances where the optional values are unconditionally dereferenced which is undefined behavior if the optional does not hold anything.

See attached file for a list of potential instances of this problem in the case of BoundTrackParameter::covariance(). Note that some of those may be legitimate if the optional is verified beforehand, we will have to check. Also, there may be other instances of this kind of pattern elsewhere, this should be verified as well.

See the following mattermost thread: https://mattermost.web.cern.ch/acts/pl/jap67ecwmir43pbyh68nn5jwjy

**Comment by gagnonlg** [comment]
Forgot to attach the file: [opt_deref.txt](https://github.com/acts-project/acts/files/6173206/opt_deref.txt)

**Comment by paulgessinger** [comment]
Good job. I think most of the unit tests can just get a quick `BOOST_CHECK(opt)` inserted to make it safe. The few other spots could have explicit errors or an `assert` instead.

**Comment by gagnonlg** [comment]
Tentatively fixed by #771 . 

@paulgessinger I'm only seeing now that you had self-assigned this one, I hope I didn't overstep!
