### ISSUE TITLE
SingleBoundTrackParameters.hpp: why is charge() constexpr?

### ISSUE THREAD

**Issue by cgleggett** [acts-project/acts#757]
When trying to compile acts with hipSycl, I encountered the following [issue](https://github.com/illuhad/hipSYCL/issues/501).

does `SingleBoundTrackParameters::charge()` in `Core/include/Acts/EventData/SingleBoundTrackParameters.hpp` need to be constexpr, especially since `get()` isn't?

The same applies to `Core/include/Acts/EventData/SingleFreeTrackParameters.hpp`

certainly there are no issues building if `constexpr` is removed.

**Comment by paulgessinger** [comment]
I think it's `constexpr` because it can be for CPU compilation. I don't think it has to be `constexpr`, so we could probably drop it if need be. 

Is `constexpr` a general problem in this respect, or is it a specific problem in this specific function? 

If it's the latter, we might have to think of a more robust way to use/not use `constexpr` depending on the environment.

**Comment by cgleggett** [comment]
These were the only places that this cropped up when I was compiling with hipSYCL. There may be others that were hidden by other problems that I haven't yet resolved....

From what Aksel wrote in the linked issue, `constexpr` is an issue in code that executes on GPUs if it calls a function that is not `constexpr`, so that there's a `__host__` vs `__host__ __device__` mismatch.

**Comment by paulgessinger** [comment]
I see. I don't think there is particular harm in removing `constexpr` here. I can't imagine it has significant performance impact.

**Comment by HadrienG2** [comment]
FWIW, `constexpr` has no performance impact per se. That would be C++20's `consteval`.

What `constexpr` was meant to do is only to force you to only use the language subset that **can** be evaluated at compile time, if the compiler feels like doing so. And it arguably fails at even that...
