### ISSUE TITLE
Bug - Segfault in CsvSimHitReader

### ISSUE THREAD

**Issue by baschlag** [acts-project/acts#774]
When running the [TruthTrackingExample](https://github.com/acts-project/acts/blob/master/Examples/Run/Reconstruction/Common/RecTruthTracks.cpp), the CsvSimHitReader randomly segfaults when calling the ```adopt_sequence``` function in this line (as already discussed with @XiaocongAi ):

https://github.com/acts-project/acts/blob/master/Examples/Io/Csv/src/CsvSimHitReader.cpp#L85

This is a blocker for the production of samples needed for the vertexing studies for the ACTS paper.

**Comment by baschlag** [comment]
Here are the steps that eventually lead to the segfault:
Event gen:
```bash
./ActsExamplePythia8  --events=200  --output-dir=data/gen/ttbar_mu30 --output-csv  --gen-cms-energy-gev=14000 --gen-hard-process=Top:qqbar2ttbar=on --gen-npileup=30
```
Simulation
```bash
./ActsExampleFatrasGeneric --input-dir=data/gen/ttbar_mu30   --output-dir=data/sim_generic/ttbar_mu30  --output-csv  --select-eta=-2.5:2.5 --select-pt-gev=0.4: --fatras-pmin-gev 0.4 --remove-neutral  --bf-constant-tesla=0:0:2
```

Truth tracking example that leads to the segfault:
```bash
./ActsExampleTruthTracksGeneric --input-dir=data/sim_generic/ttbar_mu30 --output-dir=data/reco_generic/ttbar_mu30 --bf-constant-tesla=0:0:2 --digi-config-file ../../Examples/Algorithms/Digitization/share/default-smearing-config-generic.json
```

**Comment by baschlag** [comment]
FYI @asalzburger @paulgessinger

**Comment by asalzburger** [comment]
Is closed.
