### ISSUE TITLE
Bug - KalmanFitterError in TruthTrackingExample

### ISSUE THREAD

**Issue by baschlag** [acts-project/acts#775]
Running ```ActsExampleTruthTracksGeneric``` on 500 mu=200 ttbar events yields more than 200 of these errors with current master:
```
TrackFitting   WARNING   Fit failed for track 1599 with errorKalmanFitterError:5
TrackFitting   ERROR     KalmanFilter failed: KalmanFitterError:5
```

Here is the entire chain to reproduce these errors
- Event gen:
```bash
./ActsExamplePythia8  --events=500  --output-dir=data/gen/ttbar_mu200 --output-csv  --gen-cms-energy-gev=14000 --gen-hard-process=Top:qqbar2ttbar=on --gen-npileup=200
```
- Simulation:
```bash
./ActsExampleFatrasGeneric --input-dir=data/gen/ttbar_mu200   --output-dir=data/sim_generic/ttbar_mu200  --output-csv  --select-eta=-2.5:2.5 --select-pt-gev=0.4: --fatras-pmin-gev 0.4 --remove-neutral  --bf-constant-tesla=0:0:2
```

- Truth tracking example with errors:
```bash
./ActsExampleTruthTracksGeneric --input-dir=data/sim_generic/ttbar_mu200 --output-dir=data/reco_generic/ttbar_mu200 --bf-constant-tesla=0:0:2 --digi-config-file ../../Examples/Algorithms/Digitization/share/default-smearing-config-generic.json
```

**Comment by asalzburger** [comment]
I could reproduce this and identified (on single muons) all of those failure as outside eta particles ...

**Comment by XiaocongAi** [comment]
I'm not sure which PR fixed this issue, but it seems this issue is not there any more. For example, I have rerun the examples and just saw 7 `KalmanFitterError:5` out of 100 ttbar mu = 200 events, which is reasonable. So I think we could close this issue now.
