### ISSUE TITLE
Improvement: Consider removing cache-less magnetic field overloads

### ISSUE THREAD

**Issue by Corentin-Allaire** [acts-project/acts#782]
Currently the `MagneticFieldProvider` define two pure virtual method to access the magnetic field without using the cache : `getField(const Vector3& position)` and `getFieldGradient(const Vector3& position, ActsMatrix<3, 3>& derivative)`. We should consider removing those as accessing the field without cache is not always possible (for example it is not possible in for the ATLASMagneticFieldWrapper used with athena).

**Comment by paulgessinger** [comment]
Looking at this now. One thing I noticed is that this removes most of the functionality of the B field access example:

https://github.com/acts-project/acts/blob/main/Examples/Run/MagneticField/BFieldAccessExample.cpp#L61-L69

Right now this checks how many mismatches there are (but it's not a unit test). I guess this example can still serve to show how to use the B field, but this functionality would go away with this change.
