### ISSUE TITLE
bug: solenoid magnetic field (defaults) in Examples looks corrupt

### ISSUE THREAD

**Issue by asalzburger** [acts-project/acts#784]
When running with the new `bf-solenoid` option I get many errors like this:

```sh
12:49:19    FatrasAlgori   ERROR     event 94 particle id=(1|0|382|0|0)|pdg=mu-|q=-1|m=0.105658|p=368.2 failed to simulate with error EigenStepperError:3: Step size adjustment exceeds maximum trials
```
I am running with this option:
```sh
--bf-solenoid-mag-tesla 2
```

None of these warnings appear either with the constant field nor with the ATLAS magnetic field map.

**Comment by paulgessinger** [comment]
This seems to only occur if the log level is not `DEBUG`. Suboptimal...

**Comment by paulgessinger** [comment]
For reference, I think I can reproduce this with

```console
bin/ActsExampleFatrasGeneric --bf-solenoid-mag-tesla 2 --skip 36623 -n1 -j1
```

**Comment by paulgessinger** [comment]
This is WEIRD as heck. When I run 

```console 
bin/ActsExampleFatrasGeneric --bf-solenoid-mag-tesla 2 --skip 36623 -n1 -j1 -l0
```

the final bit of output looks like this:

```
14:54:54    Simulation     VERBOSE   Step with size = 65.8949 performed
14:54:54    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (263.579,  +∞, 4166.31,  +∞ )
14:54:54    Simulation     VERBOSE   Step with size = 263.579 performed
14:54:54    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (1054.32,  +∞, 3902.73,  +∞ )
14:54:54    Simulation     VERBOSE   Step with size = 1054.32 performed
14:54:54    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (4217.27,  +∞, 2848.41,  +∞ )
14:54:54    Simulation     VERBOSE   Step with size = 2848.41 performed
14:54:54    Simulation     VERBOSE   Target: x | Path limit reached at distance 0
14:54:54    Simulation     VERBOSE   Stepping loop done.
14:54:54    FatrasAlgori   DEBUG     1 simulated particles (initial state)
14:54:54    FatrasAlgori   DEBUG     1 simulated particles (final state)
14:54:54    FatrasAlgori   DEBUG     13 simulated hits
14:54:54    EventStore#3   VERBOSE   Added object 'particles_initial'
14:54:54    EventStore#3   VERBOSE   Added object 'particles_final'
14:54:54    EventStore#3   VERBOSE   Added object 'simhits'
14:54:54    Sequencer      INFO      finished event 36623
14:54:54    Sequencer      INFO      Processed 1 events in 5.917056 ms (wall clock)
14:54:54    Sequencer      INFO      Average time per event: 5.218308 ms/event
14:54:54    Sequencer      DEBUG     Average time per algorithm:
14:54:54    Sequencer      DEBUG       Reader:EventGenerator: 53.861000 us/event
14:54:54    Sequencer      DEBUG       Algorithm:ParticleSelector: 33.381000 us/event
14:54:54    Sequencer      DEBUG       Algorithm:FatrasAlgorithm: 5.131066 ms/event
```

i.e. no error, although there is a navigation failure that causes the aborter to fire and terminate the propagation after 181 steps.

If I comment out [this line](https://github.com/acts-project/acts/blob/main/Core/include/Acts/Propagator/Propagator.ipp#L49), 

```cpp
ACTS_VERBOSE("Step with size = " << s << " performed");
```

the output looks like this:

```
...
14:52:21    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (0.828414,  +∞, 2826.34,  +∞ )
14:52:21    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (0.589397,  +∞, 2826.19,  +∞ )
14:52:21    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (0.15163,  +∞, 2826.05,  +∞ )
14:52:21    Simulation     VERBOSE   Target: 0 | Target stepSize (path limit) updated to (0.606518,  +∞, 2825.9,  +∞ )
14:52:21    Simulation     ERROR     Propagation reached the step count limit of 1000 (did 1000 steps)
14:52:21    FatrasAlgori   ERROR     event 36623 particle id=(1|0|1|0|0)|pdg=mu-|q=-1|m=0.105658|p=1.39521 failed to simulate with error PropagatorError:3: Propagation reached the configured maximum number of steps
14:52:21    FatrasAlgori   DEBUG     0 simulated particles (initial state)
14:52:21    FatrasAlgori   DEBUG     0 simulated particles (final state)
14:52:21    FatrasAlgori   DEBUG     0 simulated hits
14:52:21    EventStore#3   VERBOSE   Added object 'particles_initial'
14:52:21    EventStore#3   VERBOSE   Added object 'particles_final'
14:52:21    EventStore#3   VERBOSE   Added object 'simhits'
14:52:21    Sequencer      INFO      finished event 36623
```

i.e. the path limit is not updated as above, and the aborter does not fire, leading to the error seen by @asalzburger.

How on earth does 

```cpp
ACTS_VERBOSE("Step with size = " << s << " performed");
```

affect the path length accumulation?

**Comment by HadrienG2** [comment]
I saw this sort of things happen multiple times before, and each time it was a symptom of undefined behavior in the code. For example...

- If the code does out of bounds writes on a stack variable, then the addition of a print statement can affect the stack layout, and thus the appearance or disappearance of the bug's symptoms.
- If the code violates strict aliasing rules by e.g. casting `float*` to `int*`, the compiler can take incorrect optimization decisions, but may not take them in a presence of a print statement, which is a strong side effect (syscall) and thus a strong optimization barrier.
- If the code reads and displays the value of uninitialized memory, GCC can be more forgiving than clang (which would just delete everything), materializing some code that reads random junk. Again, stronger optimizations may be applied in the absence of an externally visible program side-effect.

**Comment by paulgessinger** [comment]
I ran a valgrind memcheck job yesterday (haven't looked at the results yet), that might shine some light on this. I guess this will tell me about unitialized memory, but corrupt stack access or strict aliasing problems might be hard to find.

The only case I can think of where we do any reinterpretation at all is the opaque B field cache type, but there I'm specifically using `char` in order to not violate strict aliasing (at least that's how I understand this stuff to work). Other than that: 🤷

**Comment by paulgessinger** [comment]
After having another look at the strict aliasing rules, maybe the B field cache is in fact in violation, therefore causing UB. If that's the case, that might be it. Will investigate on monday.

**Comment by HadrienG2** [comment]
Note that my list above was not exhaustive (only those case I personally experienced where printf + UB can mix weirdly), and you may also want to try out things like compiler sanitizers (ASan, UBSan...) that check for a lot more forms of C/++ UB than I can conveniently fit in a Github comment.

These two blog posts on such tools and their limitations may come in handy along the way:

- https://blog.llvm.org/2011/05/what-every-c-programmer-should-know_14.html
- https://blog.regehr.org/archives/1520

**Comment by paulgessinger** [comment]
Ok, I'm digging deeper.

1. I haven't been able to reproduce the error with `-O0`.
2. I found an unitialized value [here](https://github.com/acts-project/acts/blob/main/Core/include/Acts/MagneticField/InterpolatedBFieldMap.hpp#L154-L164):
   ```cpp
    constexpr size_t nCorners = 1 << DIM_POS;
    std::array<Vector3, nCorners> neighbors;
    const auto& cornerIndices = m_grid.closestPointsIndices(gridPosition);

    size_t i = 0;
    for (size_t index : cornerIndices) {
      neighbors.at(i++) = m_transformBField(m_grid.at(index), position);
    }
   ```
   Changing this to 
   ```cpp
    std::array<Vector3, nCorners> neighbors{Vector3{0,0,0}};
   ```
   suppresses the error. The reason is (I think) because `nCorners != cornerIndices.size()` at all times. If `cornerIndices.size() < nCorners` then a part of the `std::array` remains uninitialized unless it's initialized before to `Vector{0,0,0}`. **However** the B field value is incorrect in this case I suppose, so the index mismatch is probably a bug all by itself.
3. All of this is still a bug that only occurs after something broke in the navigation stream anyway. It occurs when the navigator has given up and the propagation is doing it's hail mary step forward until some limit is hit.

**Comment by paulgessinger** [comment]
Ok, follow up, the reason for the index mismatch is that `closestPointsIndices` does not return indices for neighbors which are out of bounds of the grid. The question then is what we do in this case? I'm tempted to actually go for `Vector3{0, 0, 0}` meaning zero field outside of the B field map. Do you have an opinion @asalzburger?

**Comment by paulgessinger** [comment]
Annoyingly, the uninitialized value does not suppress the error for me anymore today, on the same hardware and same settings. So back to square one.

**Comment by paulgessinger** [comment]
I opened #825. Note that doesn't fix the actual error we see here, it fixes the fact that this error sometimes shows up and sometimes doesn't (in my testing).

The reason why the navigation fails in the way seen here still needs to be investigated.

**Comment by paulgessinger** [comment]
Preliminary update on this: it seems like the navigation loses the target boundary 

```
Acts::CylinderSurface
     Center position  (x, y, z) = (0.0000, 0.0000, 0.0000)
     Rotation:             colX = (1.000000, 0.000000, 0.000000)
                           colY = (0.000000, 1.000000, 0.000000)
                           colZ = (0.000000, 0.000000, 1.000000)
     Bounds  : Acts::CylinderBounds: (radius, halfLengthZ, halfPhiSector, averagePhi) = (182.2003405, 3001.0000000, 3.1415927, 0.0000000)
```

at `(-46.4909 -176.181  1984.21)`, direction: `(-0.0580775 -0.0848079   0.994703)`.
The navigation then retries all boundary surfaces which are 

- The cylinder from above at `0,0,0` and radius `182.2`, whose intersection just became invalid (over the limit)
- The inner cylinder at `0,0,0`, and radius `20.4`, also over the limit
- The disk at `0,0,544.71` and radii `20.4` and `182.2`, also over limit
- The disk at `0,0,3001` and radii `20.4` and `182.2`, which is not intersected at all.

I'll look into why the intersection itself fails.

**Comment by paulgessinger** [comment]
Ok it seems to me that this is a simple overstepping error: 
```
-> pLimit, oLimit, cLimit: 5317.67, -0.1, -0.118337
```

The propagation oversteps to `-0.1188337` while the overstepping limit is `-0.1`, so the boundary becomes invalid, and the navigator cannot recover.

@asalzburger since you are most familiar with the overstepping logic, is this expected to happen from time to time, and can we tolerate it?

**Comment by paulgessinger** [comment]
As the error due to out of bounds interpolation is gone now, and the other error seems unrelated to the magnetic field, I'm closing this.
