### ISSUE TITLE
How do we do B field interpolation?

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#821]
Right now, `Grid` is used to store and retrieve B field values to interpolate between. `Grid` can be queried for neighbor indices for a given position, and will only return indices that corresponds to cells that exist, i.e. no neighbors that would be behind the edge of the map. 

Both `Grid`'s internal `interpolate` method as well as `FieldCell`, however, assume that there will always be a full set of neighbor indices. This appears to have caused UB related to #784. 

The question is, what do we do here? I think we have the following options:

1. Out-of-bounds B field values are `(0,0,0)`. This is easy to implement, but leads to wrong B field values in the border region of a field map.
2. Clamp to the last valid value. `Grid` can be configured to return the last valid bin value for out of bounds query positions. This doesn't affect the neighbor calculation however, those will still not include over-the-edge bins. This can be implemented, but is more difficult as we have to change the neighbor algorithm.
3. We error out if a field map is queried in the border region. This is very explicit, and probably the most correct approach.

Do we care about the exact validity of the interpolation at the grid borders? I think we don't as it's not well defined what we should do anyway. This doesn't really come up often as our field maps are typically larger than the tracking geometries, but apparently happens in case of the solenoid field map (#784). 

I would probably go for either option 1 or 3, with a slight preference for option 3.

/cc @asalzburger @HadrienG2

**Comment by HadrienG2** [comment]
I agree with your choices. If it doesn't introduce unsufferable overhead in this performance-critical part, proper error reporting is best. If it does introduce overhead, then returning nonsensical values is fine, since this code path should never be hit by non-buggy clients anyway.

**Comment by paulgessinger** [comment]
I need to add a loop (very likely unrolled) that does one `<` comparison between the local indices and the maximum number of indices. So the overhead should be negligible I think. I need to change all the interfaces to return our `Result` object though, but that should be ok I believe.

**Comment by HadrienG2** [comment]
Note that if Result is too costly, exceptions are another error reporting possibility that lies somewhere inbetween Result and silly output on the performance vs correctness continuum.

**Comment by paulgessinger** [comment]
I would prefer `Result` because it forces clients to handle errors.
