### ISSUE TITLE
Automatic build of non-system boost?

### ISSUE THREAD

**Issue by gagnonlg** [acts-project/acts#870]
Users have reported to me that our minimal boost version breaks the promise of minimal dependencies. For instance when building Acts on top of a base centos8 image (which only have Boost 1.66) one has to go through the trouble of installing another boost version in parallel, which depending on the environment can be non-trivial.

I know of other floss projects that simply bundle the right Boost version and use a -DUSE_SYSTEM_BOOST cmake option, for exactly this reason. However the size of the boost source code is more than 3 times that of the current ACTS source code so that is less than ideal. My CMake-fu is not great, but I think we could use the [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) to automatically build the right boost if the user requests it. We'd then need to find a way to include the .so's alongside ours without polluting the system.

Obviously, that needs to be discussed -- @paulgessinger  wdyt?

Cheers
L-G

**Comment by paulgessinger** [comment]
Yeah, I've kind of ran into this in a few cases, like on CentOS8. It is really annoying. Aside from the source code size, my other concern is that a full boost build takes quite some time. We don't need a full build, of course, but it might also be problematic to have a custom half-built version somewhere.

Probably still a good idea though.

**Comment by paulgessinger** [comment]
The other perspective is: how many boost components to we actually use in core and the plugins. As far as I can tell, it's 

```
Core/src/MagneticField/SolenoidBField.cpp
15:#include <boost/exception/exception.hpp>
16:#include <boost/math/special_functions/ellint_1.hpp>
17:#include <boost/math/special_functions/ellint_2.hpp>

Core/include/Acts/Surfaces/ConvexPolygonBounds.hpp
18:#include <boost/container/small_vector.hpp>

Core/include/Acts/Clusterization/Clusterization.hpp
15:#include <boost/config.hpp>

Core/include/Acts/Propagator/Propagator.hpp
35:#include <boost/algorithm/string.hpp>

Core/include/Acts/Propagator/Navigator.hpp
27:#include <boost/algorithm/string.hpp>

Core/include/Acts/Propagator/DirectNavigator.hpp
24:#include <boost/algorithm/string.hpp>

Core/include/Acts/Propagator/ActionList.hpp
18:#include <boost/hana/type.hpp>
19:#include <boost/hana/unpack.hpp>

Core/include/Acts/Propagator/AbortList.hpp
17:#include <boost/hana/type.hpp>
18:#include <boost/hana/unpack.hpp>

Core/include/Acts/Utilities/detail/MPL/type_collector.hpp
10:#include <boost/hana/filter.hpp>
11:#include <boost/hana/set.hpp>
12:#include <boost/hana/type.hpp>
``` 
and
```
Plugins/DD4hep/src/DD4hepLayerBuilder.cpp
30:#include <boost/algorithm/string.hpp>

Plugins/DD4hep/src/ConvertDD4hepMaterial.cpp
20:#include <boost/foreach.hpp>
21:#include <boost/tokenizer.hpp>

Plugins/TGeo/src/TGeoDetectorElement.cpp
26:#include <boost/algorithm/string.hpp>

Plugins/TGeo/src/TGeoSurfaceConverter.cpp
30:#include <boost/algorithm/string.hpp>
31:#include <boost/algorithm/string/predicate.hpp>
```

`boost::hana` is used for the measurement type generator, but is header-only. The elliptical integrals are used only for the solenoid field, and I think are also header-only. `small_vector` can probably be replaced, but I believe is also header-only. The string algorithm headers and tokenizer can probably be replicated relatively easily with custom code.

So I think we only need boost binaries if we enable the unit tests or the examples. Other than than, we seem to only use header-only components, or functionality could be rewritten. Bundling header-only components isn't that difficult, we could bundle only the include folders, keeping `thirdparty` small. The only thing I'd be a bit worried about here is possibly creating confusion which headers are used if the unit tests or examples are enabled.

**Comment by gagnonlg** [comment]
I just had a brief look at how boost is built, it seems like their bootstrap.sh script allows fine-grained control of which parts of the libraries actually get built. So it seems to me that a combination of ExternalProject (on the cmake side) and building only what we want would cover both the header-only and library dependencies with minimal fuss. 

To cover the header-only case properly, I think if we specify the right include path it will supersede anything that's on the system.

For the libraries if I'm not mistaken, in the worst case we need the filesystem, program_options, and test boost libraries. On my laptop a single-thread build of all these components takes about 2 minutes -- not bad! there remains the question of how these libraries should be treated as install time. On top of my head I see two options: either stick them in their own subdirectory in our lib/ directory and put that into the exectuable rpath (not sure how easy that is to do with cmake...) or link them statically which is not ideal. 

I'll see if I can rig something quickly with cmake, it seems mostly straightforward (famous last words...)

L-G
