### ISSUE TITLE
GeometryExample SEGFAULTs when using JSON writers

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#883]
I noticed the geometry example SEGFAULTs when you enable both `JsonSurfacesWriter` and `JsonMaterialWriter`.

On `main` (`e47dc58cc7d8718d2cb0da412b76699a9c50e0a1`)

```
bin/ActsExampleGeometryGeneric \
  --output-json \
  --output-dir geoex \
  --mat-output-file geoex/material \
  --json-write-sf-sensitive
```
crashes with a SEGFAULT in [MaterialMapJsonConverter](https://github.com/acts-project/acts/blob/main/Plugins/Json/src/MaterialMapJsonConverter.cpp#L326):
```cpp
if (lay->surfaceArray() != nullptr && m_cfg.processSensitives == true) {
  for (auto& ssf : lay->surfaceArray()->surfaces()) {
    if (ssf->surfaceMaterial() != nullptr ||
        m_cfg.processNonMaterial == true) {
      surfaceHierarchy.push_back(
          {ssf->geometryId(),
           defaultSurfaceMaterial(ssf->getSharedPtr())}); // GDB reports crash here
    }
  }
}
```

Using GDB, it seems it crashes when trying to execute `ssf->geometryId()`, manually printing in from GDB results in `virtual baseclass botch`, which I don't understand. It seems to me there is some kind of mismatch between what the compiler thinks is behind the `Surface*` and what is actually behind it.

This only seems to occur when running both writers, i.e. it works if I run
```
bin/ActsExampleGeometryGeneric \
  --output-json \
  --output-dir geoex \
  --mat-output-file geoex/material
```
without `--json-write-sf-sensitive` which makes it not go through the sensitive modules, or alternatively removing [`GeometryExampleBase.cpp:136`](https://github.com/acts-project/acts/blob/main/Examples/Run/Common/src/GeometryExampleBase.cpp#L136)

```cpp
sJsonWriter->write(context);
```

which runs **only** the `JsonMaterialWriter` without the `JsonSurfaceWriter` beforehand.

 This is very odd and kind of terrifying.

@Corentin-Allaire can you look into this?

**Comment by Corentin-Allaire** [comment]
Hi @paulgessinger, I am in vacation this week and next week so I will have a look at this (and the other issue you opened on the jsonwriting) when I am back (the 26/07). I agree with you this is kind of scary. One thing, if you have the time/opportunity (if not I will take care of it myself when I am back) :  if you invert the order of the `JsonMaterialWriter` and the `JsonSurfaceWriter` in `GeometryExampleBase.cpp` what happen ? If it work that would mean `JsonSurfaceWriter` does something weird in write that affect the surface ?

**Comment by paulgessinger** [comment]
Hey @Corentin-Allaire. No worries, whenever you're back is soon enough!

It seems to me like swapping the two writers indeed works, i.e. it doesn't SEGFAULT its seems.
