### ISSUE TITLE
cmake does not check for libexpat

### ISSUE THREAD

**Issue by andriish** [acts-project/acts#885]
After a sucessful cmake configuration I see
```
*** No rule to make target '/usr/lib64/libexpat.so', needed by 'lib64/libActsExamplesGeant4DD4hep.so'.  Stop.
``` 

Best regards,

Andrii

**Comment by paulgessinger** [comment]
This is a second order dependency we have through DD4hep I think. I'd be hesitant to add a check in ACTS' cmake configuration for this, since we don't depend on `libexpat` ourselves.
