### ISSUE TITLE
RootNuclearInteractionParametersWriter SEGFAULTs

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#914]
After fixing #877 via #911, I observe the RootNuclearInteractionParametersWriter failing with a SEGFAULT.

Opening this for reference.

**Comment by andriish** [comment]
Hi @paulgessinger ,

if you have a reproducible environment, list of commands and a stacktrace that would be great.
I could have a look and help to fix it while Fabian is busy with other things.

Best regards,

Andrii

**Comment by paulgessinger** [comment]
I get the problem when running

```
bin/ActsExampleHepMC3Histogram --input-dir hepmc3/
```

after the preparatory commands from #877, which produces the files in `hepmc3`.

Thanks for looking into this.

**Comment by andriish** [comment]
Well, the fix seems to be obvious after looking at stacktrace.
Also: multithreading seems to be a problem here as well.
