### ISSUE TITLE
Debug Information in Acts Seeder

### ISSUE THREAD

**Issue by osbornjd** [acts-project/acts#944]
The current implementation of the Acts seeding algorithm has no debug or verbose statements that could be turned on with the Acts logging functionality. It would be useful, for e.g. debugging when no seeds are found, if there were some options for understanding what the seeding algorithm is doing with the input that is provided to it, e.g. with some logging statements.

**Comment by AJPfleger** [comment]
As discussed in today's developers meeting, @osbornjd might have a quick look on the current status and then we will decide on how to proceed with this.

**Comment by AJPfleger** [comment]
It seems, the Seeder still lacks a lot of debugging print outs. Let's keep this PR open for now and have the next person working on the seeder pick it up again.

General outcome from the discussion: Add more logging-statement, that help to better understand, what currently is/was happening. If this becomes performance relevant, we could also think about a compiler-flag, that removes loggers below a certain level.
