### ISSUE TITLE
Reasonable default configurations?

### ISSUE THREAD

**Issue by robertlangenberg** [acts-project/acts#946]
The configuration in the example do not correspond to the detector used, the efficiency is not very good when it should be (nearly) 100%.

Similarly, the default-smearing-config-generic.json allows for 10 standard deviations in some volumes, not sure if that is a typo too. Also, not all volumes are configured (assuming the volumes are numbered 1,2,3...).

Since Acts users tend to run the examples with the default configuration, the example config should be reasonable.

**Comment by paulgessinger** [comment]
See #945

**Comment by robertlangenberg** [comment]
@paulgessinger yes #945 resolves the overly convoluted configuration, but doesn't make the values sensible. I'll edit the issue to only mention the flawed default configuration.

**Comment by gagnonlg** [comment]
About the volume ids, according to my notes at build level 3 for the generic detector we have:
```
volumeID=vol=1: { { { { BeamPipe::Barrel | { Pixel::NegativeEndcap | Pixel::Barrel | Pixel::PositiveEndcap } } | PST::Barrel } | { SStrip::NegativeEndcap | SStrip::Barrel | SStrip::PositiveEndcap } } | { LStrip::NegativeEndcap | LStrip::Barrel | LStrip::PositiveEndcap } }
volumeID=vol=2: { { { BeamPipe::Barrel | { Pixel::NegativeEndcap | Pixel::Barrel | Pixel::PositiveEndcap } } | PST::Barrel } | { SStrip::NegativeEndcap | SStrip::Barrel | SStrip::PositiveEndcap } }
volumeID=vol=3: { { BeamPipe::Barrel | { Pixel::NegativeEndcap | Pixel::Barrel | Pixel::PositiveEndcap } } | PST::Barrel }
volumeID=vol=4: { BeamPipe::Barrel | { Pixel::NegativeEndcap | Pixel::Barrel | Pixel::PositiveEndcap } }
volumeID=vol=5: BeamPipe::Barrel
volumeID=vol=6: { Pixel::NegativeEndcap | Pixel::Barrel | Pixel::PositiveEndcap }
volumeID=vol=7: Pixel::NegativeEndcap
volumeID=vol=8: Pixel::Barrel
volumeID=vol=9: Pixel::PositiveEndcap
volumeID=vol=10: PST::Barrel
volumeID=vol=11: { SStrip::NegativeEndcap | SStrip::Barrel | SStrip::PositiveEndcap }
volumeID=vol=12: SStrip::NegativeEndcap
volumeID=vol=13: SStrip::Barrel
volumeID=vol=14: SStrip::PositiveEndcap
volumeID=vol=15: { LStrip::NegativeEndcap | LStrip::Barrel | LStrip::PositiveEndcap }
volumeID=vol=16: LStrip::NegativeEndcap
volumeID=vol=17: LStrip::Barrel
volumeID=vol=18: LStrip::PositiveEndcap
```

**Comment by gagnonlg** [comment]
For the smearing widths it seems like I set them to the pixel widths I got from https://arxiv.org/pdf/1904.06778.pdf. Reflecting back on this, you are right that it's much too wide as only ~66% of the hits would be recorded by the pixel they really crossed...

**Comment by gagnonlg** [comment]
Looking at https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PUBNOTES/ATL-PHYS-PUB-2018-002/, Fig 11 a & b, For the ATLAS ID barrel it's closer to width/5

**Comment by gagnonlg** [comment]
I will go ahead and self-assign this. @robertlangenberg, do you agree that width/5 is a sensible default for the resolution?

**Comment by robertlangenberg** [comment]
I would have to guess, but if you read up on it, it should be fine? @asalzburger what do you think?

**Comment by gagnonlg** [comment]
Let's use width/sqrt(12) as discussed in today's dev meeting
