### ISSUE TITLE
Geantino recording broken?

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#980]
After #962 was merged, I get a large number of warnings like

```
15:43:56    SimParticleT   WARNING   No EventStore instance could be found for this event!
```
which I think makes the G4 primary generation not do anything. Is this expected or a bug @asalzburger? I think this only occurs when running with multiple threads.

**Comment by asalzburger** [comment]
No, this is certainly a bug, I've tested it though, but not after the merge - I will have a look!

**Comment by paulgessinger** [comment]
Hm, I also find that with `-j1` the output root file looks garbled. For instance, `v_eta` does not seem to be correctly populated at all.

**Comment by asalzburger** [comment]
I *think* we need to restrict this example to `-j1` due to the RunManager::GetEventID() static instance.

**Comment by asalzburger** [comment]
First fix should be there:
- [ ] https://github.com/acts-project/acts/pull/981
- [ ] Second needs a bit more thinking if this is possible

**Comment by paulgessinger** [comment]
Can we not use `thread_local` to communicate which thread is handling each event? I **think** we could simplify the entire `EventRegistry` to have a single instance of a `thread_local` object with pointers to the event store and so on. This automatically makes sure each thread has it's own copy, and we could get rid of the map and therefore event id as a key entirely.

**Comment by paulgessinger** [comment]
I'll try out the `thread_local` approach.

**Comment by plariono** [comment]
For me it doesn't work with the output below. When I revert to commit #950 it works fine. 

```
./ActsExampleGeantinoRecordingGdml -n100 --gdml-file geom_v3/alice3_v3.gdml --output-root
dyld: lazy symbol binding failed: Symbol not found: __ZN12ActsExamples7Options27readGeantinoRecordingConfigERKN5boost15program_options13variables_mapE
  Referenced from: /Users/lrnv/alice/tools/acts/acts/bin/./ActsExampleGeantinoRecordingGdml
  Expected in: /Users/lrnv/alice/tools/acts/acts/lib/libActsExamplesGeant4.dylib

dyld: Symbol not found: __ZN12ActsExamples7Options27readGeantinoRecordingConfigERKN5boost15program_options13variables_mapE
  Referenced from: /Users/lrnv/alice/tools/acts/acts/bin/./ActsExampleGeantinoRecordingGdml
  Expected in: /Users/lrnv/alice/tools/acts/acts/lib/libActsExamplesGeant4.dylib

zsh: killed     ./ActsExampleGeantinoRecordingGdml -n100 --gdml-file geom_v3/alice3_v3.gdml 
```

**Comment by paulgessinger** [comment]
Hey @plariono, that looks like a linking problem. I think what might be happening is  that the `GeantinoRecording` executable got renamed to `ActsExampleMaterialRecordingX`, so you're executing the old executable that likely hasn't been rebuilt in a while. Now apparently with #950 applied, you get a linking error from that old executable with the newly built shared libraries.

Long story short: can you try running `ActsExampleMaterialRecordingGdml` and/or wipe your build directory and do a fresh build?

**Comment by plariono** [comment]
Hi @paulgessinger, oh I see. I've run `ActsExampleMaterialRecordingGdml` and get the warning that you reported for all or nearly all events.

**Comment by paulgessinger** [comment]
Hm @plariono. This behavior was fixed for me with #1006. Is that included in the branch you're testing?

**Comment by plariono** [comment]
@paulgessinger Indeed #1006 was not included. With the up-to-date version I get this: 

```
./ActsExampleMaterialRecordingGdml -n100 --gdml-file geom_v3/alice3_v3.gdml --output-root
14:48:36    Sequencer      INFO      Added reader 'EventGenerator'

**************************************************************
 Geant4 version Name: geant4-10-07-patch-02    (11-June-2021)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************


 *** Break *** segmentation violation
[/usr/local/opt/root/lib/root/libCore.so] TUnixSystem::DispatchSignals(ESignals) (no debug info)
[/usr/local/opt/root/lib/root/libCore.so] SigHandler(ESignals) (no debug info)
[/usr/local/opt/root/lib/root/libCore.so] sighandler(int) (no debug info)
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/opt/geant4/lib/libG4run.dylib] G4RunManager::InitializeGeometry() (no debug info)
[/opt/geant4/lib/libG4run.dylib] G4RunManager::Initialize() (no debug info)
[/Users/lrnv/alice/tools/acts/acts/lib/libActsExamplesGeant4.dylib] ActsExamples::Geant4Simulation::Geant4Simulation(ActsExamples::Geant4Simulation::Config const&, Acts::Logging::Level) /Users/lrnv/alice/tools/acts/source/Examples/Algorithms/Geant4/src/Geant4Simulation.cpp:80
[/Users/lrnv/alice/tools/acts/acts/lib/libActsExamplesGeant4Common.dylib] ActsExamples::setupGeant4Simulation(boost::program_options::variables_map const&, ActsExamples::Sequencer&, G4RunManager*, std::__1::unique_ptr<G4VUserDetectorConstruction, std::__1::default_delete<G4VUserDetectorConstruction> >, std::__1::vector<G4UserRunAction*, std::__1::allocator<G4UserRunAction*> >, std::__1::vector<G4UserEventAction*, std::__1::allocator<G4UserEventAction*> >, std::__1::vector<G4UserTrackingAction*, std::__1::allocator<G4UserTrackingAction*> >, std::__1::vector<G4UserSteppingAction*, std::__1::allocator<G4UserSteppingAction*> >, std::__1::shared_ptr<Acts::TrackingGeometry const>, std::__1::shared_ptr<Acts::MagneticFieldProvider const>, bool) /Users/lrnv/alice/tools/acts/source/Examples/Run/Geant4/Common/Geant4.cpp:112
[/Users/lrnv/alice/tools/acts/acts/lib/libActsExamplesGeant4Common.dylib] ActsExamples::runMaterialRecording(boost::program_options::variables_map const&, std::__1::unique_ptr<G4VUserDetectorConstruction, std::__1::default_delete<G4VUserDetectorConstruction> >) /Users/lrnv/alice/tools/acts/source/Examples/Run/Geant4/Common/Geant4.cpp:159
[/Users/lrnv/alice/tools/acts/acts/bin/./ActsExampleMaterialRecordingGdml] main /Users/lrnv/alice/tools/acts/source/Examples/Run/Geant4/GdmlMaterialRecording.cpp:0
[/usr/lib/system/libdyld.dylib] start (no debug info)
```

**Comment by paulgessinger** [comment]
Ok that's odd. I must admit I haven't tested the GDML detector construction so it's possible there's a bug there.

**Comment by paulgessinger** [comment]
Hey @plariono, did this end up working with GDML?

**Comment by plariono** [comment]
Hi @paulgessinger, the ActsExampleMaterialRecordingGdml crashes for me. 

```
lrnv@Pavels-MacBook-Pro-3 bin % lldb -- ./ActsExampleMaterialRecordingGdml -n 1000 --gdml-file geom/alice3_v3.gdml
(lldb) target create "./ActsExampleMaterialRecordingGdml"
Current executable set to '/Users/lrnv/alice/tools/acts/acts/bin/ActsExampleMaterialRecordingGdml' (x86_64).
(lldb) settings set -- target.run-args  "-n" "1000" "--gdml-file" "geom/alice3_v3.gdml"
(lldb) run
Process 10760 launched: '/Users/lrnv/alice/tools/acts/acts/bin/ActsExampleMaterialRecordingGdml' (x86_64)
10:24:25    Sequencer      INFO      Added reader 'EventGenerator'

**************************************************************
 Geant4 version Name: geant4-10-07-patch-02    (11-June-2021)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************

Process 10760 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001034f5e28 libG4run.dylib`G4RunManagerKernel::DefineWorldVolume(G4VPhysicalVolume*, bool) + 168
libG4run.dylib`G4RunManagerKernel::DefineWorldVolume:
->  0x1034f5e28 <+168>: movq   0x10(%r13), %rax
    0x1034f5e2c <+172>: movq   0x58(%rax), %rax
    0x1034f5e30 <+176>: testq  %rax, %rax
    0x1034f5e33 <+179>: je     0x1034f6141               ; <+961>
Target 0: (ActsExampleMaterialRecordingGdml) stopped.
```

**Comment by paulgessinger** [comment]
Hm. @noemina indicated yesterday she observed crashes with the GDML loading (with the ITk GDML) as well. I'm not sure what happens here, it looks like it might in fact be during the GDML loading into G4 itself?

**Comment by noemina** [comment]
The problem I saw was related to the missing world volume in the gdml which was causing a crash the very beginning of the job you want to run. In my case, the gdml was containing a part of the ITk detector without its world volume. This means that the geometry doesn't exist (it is not defined --> segfault) at the center of the detector (if the subdetector is "empty" inside), because there is no world volume. The segfault is caused by the fact that geantinos are produced in the centre of the geometry, but if that's empty, some geometry pointers are missing hence leading to a segfault.
Can you please check that a world volume containing the entire geometry is present? In my case, adding it solved the problem.

**Comment by plariono** [comment]
Hi @noemina, it seems that I'm also missing the world volume.
I only have the world ref there:
```
    <volume name="cave">
      <materialref ref="CAVE_Air"/>
      <solidref ref="cave"/>
      <physvol name="barrel_1" copynumber="1">
        <volumeref ref="barrel"/>
        <positionref ref="barrel_1incavepos"/>
      </physvol>
      <physvol name="caveRB24_1" copynumber="1">
        <volumeref ref="caveRB24"/>
        <positionref ref="caveRB24_1incavepos"/>
      </physvol>
    </volume>
  </structure>
  <setup name="default" version="1.0">
    <world ref="cave"/>
  </setup>
```

**Comment by noemina** [comment]
Hello! Can you try making a "World" volume that contains your "cave"?

**Comment by plariono** [comment]
I added the world volume and it's not crashing anymore. thank you @noemina

**Comment by paulgessinger** [comment]
So this is essentially an assumption on our end that there is a "world volume" and if the GDML does not conform to that assumption, it SEGFAULTs?

Is there a way to detect this ahead of time and exit with an error message?

**Comment by noemina** [comment]
no, the "problem" (if any) is in the assumption from the G4 parser that the world volume is there, as this is how geometries are defined in G4 (you don't expect to have an empty volume in the middle of your detector). In other words, the problem can be translated in the way the geometry is dumped or written in gdml.
In any case, you want to get the world volume when running the geantino step recording, so the code is definitely fine.

**Comment by paulgessinger** [comment]
Ok. Then I'm closing this as solved.
