### ISSUE TITLE
[Bug] float custom scalar type for acts does not work

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/acts#982]
Acts does not compile with `-DACTS_CUSTOM_SCALARTYPE=float`

Following is the error message but I am pretty sure it is a tip of iceberg (I also got huge amount of warning messages from convesion double->float)
```
/home/beomki/projects/acts/acts/Core/include/Acts/Utilities/Intersection.hpp: In lambda function:
/home/beomki/projects/acts/acts/Core/include/Acts/Utilities/Intersection.hpp:36:46: error: narrowing conversion of ‘+Inf’ from ‘double’ to ‘Eigen::Matrix<float, 3, 1>::Scalar’ {aka ‘float’} inside { } [-Wnarrowing]
       std::numeric_limits<double>::infinity()};
                                              ^
/home/beomki/projects/acts/acts/Core/include/Acts/Utilities/Intersection.hpp: In constructor ‘constexpr Acts::Intersection<DIM>::Intersection() [with unsigned int DIM = 3]’:
/home/beomki/projects/acts/acts/Core/include/Acts/Utilities/Intersection.hpp:36:46: error: narrowing conversion of ‘+Inf’ from ‘double’ to ‘Eigen::Matrix<float, 3, 1>::Scalar’ {aka ‘float’} inside { } [-Wnarrowing]
/home/beomki/projects/acts/acts/Core/include/Acts/Utilities/Intersection.hpp: In lambda function:
```

**Comment by asalzburger** [comment]
Hi,

thanks @beomki-yeo - the custom scalar is a bit post-fitted, we did have everything on `double` at the beginning, it might need a good amount of work, cleanup to to have it fully worked through.

If we think that's a good idea (and needed), we should start a campaign going through the code and clearing it out.

And have a CI test that checks that no new PR breaks it.

**Comment by beomki-yeo** [comment]
Looks like it would be a super heavy job - We may try to handle the issue when we migrate traccc into acts core in the future

**Comment by paulgessinger** [comment]
Discussed in the meeting: unclear if this is a priority right now. Closing and will reopen in case this requirement comes up.
